mongodb/mongo-cxx-driver

SConstruct, src/SConscript.client, src/mongo/bson/bsonelement.h, src/mongo/bson/util/builder.h, src/mongo/config.h.in, src/mongo/db/dbmessage.cpp, src/mongo/platform/strnlen.cpp, src/mongo/platform/strnlen.h
=> CXX-451 polyfill strnlen for platforms that don't have it

src/mongo/bson/bsondemo/bsondemo.cpp, src/mongo/bson/bsonelement.h, src/mongo/client/examples/insert_demo.cpp, src/mongo/client/examples/simple_client_demo.cpp
also got rid of `using namespace std;` in bsondemo since that is pretty gross.
=> CXX-465 remove questionable typedefs and cleanup bsondemo

.mci.yml
New buildvariant, plus some refactoring of the config file to make this easier.
=> Add OS X buildvariant

.mci.yml, src/mongo/client/examples/authTest.cpp, src/mongo/integration/replica_set/read_preference.cpp, src/mongo/integration/standalone/dbclient_test.cpp
@samantharitter  can you review?
=> CXX-388 CXX-440 test against MongoDB 2.2

src/mongo/integration/standalone/dbclient_test.cpp
patch build in progress: https://mci.10gen.com/version/54c7ec623ff12237340000cb_0
@samantharitter can you review?
=> CXX-497 only create v0 indexes in tests if server is MMAPv1

.mci.yml
also bump 2.6 from 2.6.5 to 2.6.7
@samantharitter, can you review?
=> CXX-502 add 3.0 tasks to multiversion tests

src/bsoncxx/array/value.hpp, src/bsoncxx/array/view.hpp, src/bsoncxx/document/value.hpp, src/bsoncxx/document/view.hpp, src/bsoncxx/json.hpp, src/bsoncxx/oid.hpp
this is some initial documentation for the parts of the library that are pretty stable.
reviewers: @hanumantmk, @samantharitter
=> CXX-524 document stable parts of BSON library

src/bsoncxx/array/value.hpp, src/bsoncxx/builder/basic/array.hpp, src/bsoncxx/builder/basic/document.hpp, src/bsoncxx/builder/basic/kvp.hpp, src/bsoncxx/builder/basic/sub_array.hpp, src/bsoncxx/builder/basic/sub_document.hpp, src/bsoncxx/builder/core.hpp, src/bsoncxx/builder/stream/array.hpp, src/bsoncxx/builder/stream/array_context.hpp, src/bsoncxx/builder/stream/closed_context.hpp, src/bsoncxx/builder/stream/document.hpp, src/bsoncxx/builder/stream/helpers.hpp, src/bsoncxx/builder/stream/key_context.hpp, src/bsoncxx/document/value.hpp, src/bsoncxx/types.hpp, src/bsoncxx/types/value.hpp
I mostly punted on documenting builder::stream as it wouldn't really help users much. Going to write separate bson examples for that.
=> CXX-524 document the rest of bsoncxx

src/bsoncxx/CMakeLists.txt, src/bsoncxx/json.cpp, src/bsoncxx/json.hpp, src/bsoncxx/test/bson_builder.cpp, src/bsoncxx/types.cpp
=> CXX-547 de-inline json.hpp

src/mongo/client/dbclient.cpp, src/mongo/client/dbclientinterface.h
i know we hate bool parameters, but a tag or enum seemed like overkill here.
=> CXX-516 support nolock in eval

SConstruct, src/mongo/bson/bson_validate.cpp, src/mongo/bson/bson_validate_test.cpp, src/mongo/bson/bsonobjbuilder.h, src/mongo/bson/util/builder.h, src/mongo/util/net/sock.cpp, src/mongo/util/net/ssl_manager.cpp
I skipped the following two SHAs from that range:
- 197fbbd - it wasn't clear that we wanted it or needed it
- afc23f0 - Please give this a close look. My read is that we don't need it, but the listX stuff has been a potent source of confusion.
=> CXX-559 Backport server r3.0.0-rc6..r3.0.1 changes

src/mongo/bson/bsonelement.cpp, src/mongo/client/sasl_client_authenticate_impl.cpp, src/mongo/client/sasl_scramsha1_client_conversation.cpp
Very small delta on this for the driver relevant changes between 3.0.1 and 3.0.2. These will flow into legacy-1.0.2 whenever that happens. No rush on this one, we haven't even shipped legacy-1.0.1 yet.
=> CXX-572 Backport server r3.0.1..r3.0.2 changes

.mci.yml
=> CXX-573 stop installing Mongo Orchestration manually

src/mongo/client/dbclientcursor.cpp, src/mongo/client/dbclientcursor.h, src/mongo/util/net/message_port.cpp
This is all of the code changes, and none of the clang format changes. The format work will go in under another ticket.
=> CXX-622 Backport server r3.0.5..r3.0.6 changes

src/bsoncxx/CMakeLists.txt
=> CXX-675 Static bsoncxx library wrongly called libbson.a

src/mongo/client/dbclientcursor.cpp, src/mongo/integration/standalone/dbclient_test.cpp
=> CXX-699 compute nextBatchSize() correctly

SConstruct, src/mongo/platform/random.cpp, src/mongo/platform/random.h, src/mongo/platform/random_test.cpp
Server SHAs
447aa61
946c96a
See CXX-666 for details on why these commits.
=> CXX-666 Backport server r3.0.6..r3.0.7 changes to the legacy driver

src/mongocxx/client.cpp, src/mongocxx/client.hpp, src/mongocxx/collection.cpp, src/mongocxx/collection.hpp, src/mongocxx/database.cpp, src/mongocxx/database.hpp, src/mongocxx/test/client.cpp, src/mongocxx/test/collection.cpp, src/mongocxx/test/collection_mocked.cpp, src/mongocxx/test/database.cpp
Also a drive by fixup of some missing MONGOCXX_PRIVATE tags on private constructors of these types.
=> CXX-608 Allow default construction of client, collection, database

src/mongocxx/test/write_concern.cpp, src/mongocxx/write_concern.cpp, src/mongocxx/write_concern.hpp
Fix issues from #331
un-expose underlying int values, fix name style, more tests
=> Fix issues from #331

examples/mongocxx/aggregate.cpp, examples/mongocxx/create.cpp, examples/mongocxx/index.cpp, examples/mongocxx/query.cpp, examples/mongocxx/remove.cpp, examples/mongocxx/update.cpp
A lot of unrelated clang-format changes here as well.
=> CXX-731 Examples must pass uri to client

src/mongo/crypto/mechanism_scram.cpp
Cherry-picked from server commit
618a5ef908ac5787eb80166ada3914f4db7d3c37 for SERVER-21016
=> CXX-657 Use constant time comparison for SCRAM1 signature comparisons

src/mongo/base/error_codes.err, src/mongo/platform/random.cpp
This is assuming no new commits on the v3.0 branch for 3.0.8.
=> CXX-724 Backport server r3.0.7..r3.0.8 changes

examples/bsoncxx/builder_basic.cpp, examples/bsoncxx/getting_values.cpp, src/bsoncxx/document/element.cpp, src/bsoncxx/document/element.hpp, src/bsoncxx/private/error_category.cpp, src/bsoncxx/test/bson_validate.cpp, src/mongocxx/collection.cpp, src/mongocxx/config/postlude.hpp, src/mongocxx/config/prelude.hpp, src/mongocxx/exception/error_code.hpp, src/mongocxx/exception/private/error_category.cpp, src/mongocxx/mock/mock.hpp, src/mongocxx/options/index.cpp, src/mongocxx/options/index.hpp, src/mongocxx/test/bulk_write.cpp, src/mongocxx/test/client.cpp, src/mongocxx/test/collection.cpp, src/mongocxx/test/collection_mocked.cpp, src/mongocxx/test/database.cpp, src/mongocxx/test/private/write_concern.cpp, src/mongocxx/validation_criteria.cpp, src/mongocxx/write_concern.cpp
Fixes the warnings identified in CXX-788 and several others.
=> CXX-788 Fix some -Wall warnings under clang and gcc

examples/mongocxx/bulk_write.cpp
=> CXX-802 Fix example to check before dropping collection

.mci.yml
https://evergreen.mongodb.com/version/568febb33ff1224e9a000487_0
=> CXX-747 Add OSX builder to evergreen project

.mci.yml, src/bsoncxx/document/value.cpp, src/bsoncxx/document/value.hpp, src/mongocxx/test/client.cpp, src/mongocxx/test/database.cpp
Do we want to add the ASAN builder before the memory leaks are resolved?
=> CXX-746 Add ASAN builder to evergreen project

src/mongocxx/private/ssl.hpp
=> SSL options c_str() fix

.mci.yml
Also, a drive by to add concurrency to our build.
=> CXX-864 Enable SSL and SASL in builders

src/mongocxx/database.cpp, src/mongocxx/database.hpp, src/mongocxx/test/database.cpp, src/third_party/catch/include/helpers.hpp
@xdg PTAL?
Also it looks like some things in `helpers.hpp` fell victim to clang-format...
=> CXX-875 database::has_collection throws if operation fails

examples/mongocxx/create.cpp, src/bsoncxx/builder/core.cpp, src/bsoncxx/document/element.cpp, src/bsoncxx/json.cpp, src/bsoncxx/test/bson_builder.cpp, src/bsoncxx/types.hpp
=> CXX-879 Remove int64_t constructor for b_date

src/mongocxx/pipeline.cpp, src/mongocxx/pipeline.hpp, src/mongocxx/test/collection.cpp
=> CXX-886 Implement lookup operator for aggregation

examples/mongocxx/CMakeLists.txt, examples/mongocxx/inserted_id.cpp
This expands on the example in the ticket to show result/type checking.
=> CXX-887 Add inserted_id example

examples/bsoncxx/builder_stream.cpp, src/bsoncxx/builder/core.cpp, src/bsoncxx/builder/core.hpp, src/bsoncxx/builder/stream/key_context.hpp, src/bsoncxx/test/bson_builder.cpp, src/bsoncxx/types.cpp
@Machyne @xdg @hanumantmk This is a minor feature enhancement
=> CXX-784 Allow stream in of doc or array views

.travis.yml
See https://jira.mongodb.org/browse/SERVER-25908 for background
=> CXX-1026 MongoDB apt repos no longer offer a stable alias

src/mongocxx/options/aggregate.cpp, src/mongocxx/options/aggregate.hpp, src/mongocxx/options/count.hpp, src/mongocxx/options/delete.hpp, src/mongocxx/options/distinct.cpp, src/mongocxx/options/distinct.hpp, src/mongocxx/options/update.cpp, src/mongocxx/options/update.hpp, src/mongocxx/test/CMakeLists.txt, src/mongocxx/test/options/aggregate.cpp, src/mongocxx/test/options/count.cpp, src/mongocxx/test/options/delete.cpp, src/mongocxx/test/options/distinct.cpp, src/mongocxx/test/options/find.cpp, src/mongocxx/test/options/find_one_and_delete.cpp, src/mongocxx/test/options/find_one_and_replace.cpp, src/mongocxx/test/options/find_one_and_update.cpp, src/mongocxx/test/options/index.cpp, src/mongocxx/test/options/update.cpp
Improved consistency of code style, added additional test coverage.
=> CXX-971 (part 1) Minor cleanup of options classes

src/mongocxx/model/delete_many.hpp, src/mongocxx/model/delete_one.hpp, src/mongocxx/model/insert_one.hpp, src/mongocxx/model/replace_one.cpp, src/mongocxx/model/replace_one.hpp, src/mongocxx/model/update_many.cpp, src/mongocxx/model/update_many.hpp, src/mongocxx/model/update_one.cpp, src/mongocxx/model/update_one.hpp, src/mongocxx/test/CMakeLists.txt, src/mongocxx/test/model/delete_many.cpp, src/mongocxx/test/model/delete_one.cpp, src/mongocxx/test/model/insert_one.cpp, src/mongocxx/test/model/replace_one.cpp, src/mongocxx/test/model/update_many.cpp, src/mongocxx/test/model/update_one.cpp
Improved consistency of code style, added additional test coverage.
=> CXX-971 (part 3) Minor cleanup of model classes

etc/clang_format.py
=> CXX-1049 Update clang_format.py to handle new file extension

src/mongocxx/options/aggregate.cpp, src/mongocxx/options/aggregate.hpp, src/mongocxx/options/count.cpp, src/mongocxx/options/count.hpp, src/mongocxx/options/create_collection.cpp, src/mongocxx/options/create_collection.hpp, src/mongocxx/options/delete.cpp, src/mongocxx/options/delete.hpp, src/mongocxx/options/distinct.cpp, src/mongocxx/options/distinct.hpp, src/mongocxx/options/find_one_and_delete.cpp, src/mongocxx/options/find_one_and_delete.hpp, src/mongocxx/options/find_one_and_replace.cpp, src/mongocxx/options/find_one_and_replace.hpp, src/mongocxx/options/find_one_and_update.cpp, src/mongocxx/options/find_one_and_update.hpp, src/mongocxx/options/index.cpp, src/mongocxx/options/index.hpp, src/mongocxx/options/update.cpp, src/mongocxx/options/update.hpp, src/mongocxx/test/options/aggregate.cpp, src/mongocxx/test/options/count.cpp, src/mongocxx/test/options/create_collection.cpp, src/mongocxx/test/options/delete.cpp, src/mongocxx/test/options/distinct.cpp, src/mongocxx/test/options/find_one_and_delete.cpp, src/mongocxx/test/options/find_one_and_replace.cpp, src/mongocxx/test/options/find_one_and_update.cpp, src/mongocxx/test/options/index.cpp, src/mongocxx/test/options/update.cpp
=> CXX-971 (part 5) Add collation to remainder of relevant options classes

src/mongocxx/model/delete_many.cpp, src/mongocxx/model/delete_many.hpp, src/mongocxx/model/delete_one.cpp, src/mongocxx/model/delete_one.hpp, src/mongocxx/model/replace_one.cpp, src/mongocxx/model/replace_one.hpp, src/mongocxx/model/update_many.cpp, src/mongocxx/model/update_many.hpp, src/mongocxx/test/model/delete_many.cpp, src/mongocxx/test/model/delete_one.cpp, src/mongocxx/test/model/replace_one.cpp, src/mongocxx/test/model/update_many.cpp
=> CXX-971 (part 6) Add collation to remainder of relevant model classes

.mci.yml
=> CXX-1088 Fix ARM variant to use latest server binary available

src/mongocxx/options/create_view.cpp, src/mongocxx/options/create_view.hpp, src/mongocxx/test/options/create_view.cpp
@xdg: PTAL.
Integration tests to come in a separate review.
=> CXX-971 (part 7) Add collation to create_view options

src/mongocxx/collection.cpp, src/mongocxx/test/collection.cpp
=> CXX-971 (part 11) Add collation support for non-find reads

src/mongocxx/collection.cpp, src/mongocxx/test/collection.cpp
=> CXX-971 (part 12) Add collation support for basic writes

src/mongocxx/collection.cpp, src/mongocxx/test/collection.cpp
=> CXX-971 (part 14) Add collation support for collection::create_index()

docs/content/mongocxx-v3/installation.md, src/bsoncxx/json.cpp, src/bsoncxx/json.hpp, src/bsoncxx/test/json.cpp
Preliminary implementation. I chose to *add* two functions, just like in PHP, to prevent BC from being broken.
=> CXX-1241: Implement Extended JSON spec

docs/content/mongocxx-v3/installation.md
=> CXX-1429 Add documentation for BSONCXX_POLY_USE_SYSTEM_MNMLSTC

src/bsoncxx/builder/core.cpp, src/bsoncxx/private/stack.hh
@hanumantmk PTAL. I think this does what we need.
=> CXX-1458 Don't bother closing bson subobjects in stack dtor

src/bsoncxx/document/view.cpp, src/bsoncxx/test/bson_get_values.cpp, src/mongocxx/test/collection.cpp
=> CXX-1476 Fix broken key lookup and add unit tests

src/bsoncxx/array/element.hpp, src/bsoncxx/array/view.cpp, src/bsoncxx/builder/core.cpp, src/bsoncxx/document/element.cpp, src/bsoncxx/document/element.hpp, src/bsoncxx/document/view.cpp, src/bsoncxx/private/itoa.cpp, src/bsoncxx/private/itoa.hh, src/mongocxx/collection.hpp, src/mongocxx/index_view.cpp, src/mongocxx/index_view.hpp, src/mongocxx/options/client.cpp, src/mongocxx/private/collection.hh, src/mongocxx/private/database.hh, src/mongocxx/private/index_view.hh, src/mongocxx/test/collection.cpp, src/mongocxx/test/gridfs/bucket.cpp
This is a grab bag of small fixes related to things that coverity flagged. LKM on slack if you want a link the report.
I'm going to drop some explanatory comments on each chunk of change.
PTAL @sgolemon, @hanumantmk
=> CXX-1488 Coverity fixes

src/mongocxx/options/change_stream.cpp
=> Cast maxAwaitTimeMS value to int64_t to avoid ambiguity issues

CMakeLists.txt, etc/calc_release_version.py
* calc_release_version.py script compatibility provided to python3
* version check system is improved little bit
Details available in commit descriptions.
=> Add python3 compatibility and fix build issue

.evergreen/debian_package_build.sh, .gitattributes, .mci.yml, debian/build_snapshot.sh, debian/gbp.conf, debian/libbsoncxx-dev.install, debian/libmongocxx-dev.install, debian/rules
Patch build for the new task: https://spruce.mongodb.com/version/5f03c5613066153d099fba2e/tasks
=> CXX-1738 implement debian-package-build task

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch, .mci.yml
Patch build: https://spruce.mongodb.com/version/5f1729f132f4173db372d3d3/tasks
=> CXX-1739 implement rpm-package-build task

src/mongocxx/test/spec/operation.cpp
This commit fixes two high impact coverity issues.
=> CID 113953/113952 Uninitialized pointer read

docs/content/_index.md, docs/content/legacy-v1/installation.md, docs/content/legacy-v1/tutorial.md, docs/content/mongocxx-v3/tutorial.md, docs/themes/mongodb/layouts/index.html, etc/releasing.md
I generated the site locally with hugo 0.54 and visually inspected the changed pages, comparing them to those on mongocxx.org for reference.
=> CXX-1587 update site generation for modern hugo

src/bsoncxx/types/bson_value/private/value.hh
Coverity bug: [link](https://coverity.corp.mongodb.com/reports.htm#v15130/p10044/fileInstanceId=31907160&defectInstanceId=19837368&mergedDefectId=114201)
=> CID-114201 Uninitialized scalar field

src/mongocxx/test/collection.cpp, src/third_party/catch/include/catch.hpp
CXX-2127 reported a build issue on arm macOS that was resolved in Catch v2.12.4.
=> CXX-2127 upgrade Catch2 to v2.13.4

debian/changelog, debian/control, debian/libbsoncxx-noabi.lintian-overrides, debian/watch
Additionally, I will cherry-pick these commits onto `master` after merging this PR.
=> Debian packaging for 3.6.2

.evergreen/build_snapshot_rpm.sh, .evergreen/mongo-cxx-driver.spec
Single-task patch build: https://spruce.mongodb.com/version/607f62d57742ae709cdd8895/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2226 vendor Fedora RPM spec file

src/bsoncxx/test/json.cpp
CXX-2234
Modifies extJSON tests to expect a space after base64 (due to a bugfix [CDRIVER-3958](https://jira.mongodb.org/browse/CDRIVER-3958)).
=> CXX-2234 Expect space after base64 in extJSON binary

.evergreen/build_example_projects.sh, .evergreen/build_snapshot_rpm.sh, .evergreen/compile.sh, .evergreen/debian_package_build.sh, .evergreen/find_cmake.sh, .evergreen/install_c_driver.sh, .evergreen/uninstall_check.sh, .mci.yml, etc/debug-core-evergreen.sh, etc/run-clang-tidy.sh, examples/projects/bsoncxx/cmake-deprecated/shared/build.sh, examples/projects/bsoncxx/cmake-deprecated/static/build.sh, examples/projects/bsoncxx/cmake/shared/build.sh, examples/projects/bsoncxx/cmake/static/build.sh, examples/projects/bsoncxx/pkg-config/shared/build.sh, examples/projects/bsoncxx/pkg-config/static/build.sh, examples/projects/mongocxx/cmake-deprecated/shared/build.sh, examples/projects/mongocxx/cmake-deprecated/static/build.sh, examples/projects/mongocxx/cmake/shared/build.sh, examples/projects/mongocxx/cmake/static/build.sh, examples/projects/mongocxx/pkg-config/shared/build.sh, examples/projects/mongocxx/pkg-config/static/build.sh
CXX-2211
Removes all usages of `xtrace` from shell scripts in the repo.
=> CXX-2211 Remove usages of xtrace in shell scripts

.mci.yml, src/bsoncxx/config/CMakeLists.txt, src/bsoncxx/config/libbsoncxx-static.pc.in, src/bsoncxx/config/libbsoncxx.pc.in, src/mongocxx/config/CMakeLists.txt, src/mongocxx/config/libmongocxx-static.pc.in, src/mongocxx/config/libmongocxx.pc.in
Patch build: https://spruce.mongodb.com/version/60fb3c39a4cf47264f5b96fd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2202 update ppc64le build platform

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Patch build: https://spruce.mongodb.com/version/60f9f04e0305b94cdeeb8e46/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2282 build RPMs in Fedora 35 environment

data/unified-format/test_files.txt, data/unified-format/valid-pass/observeSensitiveCommands.json, src/mongocxx/test/spec/monitoring.cpp
Validates that the test driver itself is respecting
observeSensitiveCommands properly.
Closes CXX-2325.
=> CXX-2325: Pull and fix for observeSensitiveCommands.json

src/mongocxx/test/CMakeLists.txt, src/mongocxx/test/versioned_api.cpp
=> CXX-2314 Add tests+examples for docs on the versioned server API

.evergreen/mongo-cxx-driver.spec, .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/61377caed1fe0702cac82444/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> sync RPM spec file for 3.6.5 release

generate_uninstall/CMakeLists.txt
=> CXX-2276 more precise empty directory pruning on install

.mci.yml
Full patch build: https://spruce.mongodb.com/version/61bd06f23627e05b81d58bb3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2423 workaround pip install failure on pc64le

src/mongocxx/test/client_side_encryption.cpp
See DRIVERS-2191 for motivation for this change.
=> CXX-2445 replace example.com with doesnotexist.local

docs/content/mongocxx-v3/installation/linux.md, docs/content/mongocxx-v3/installation/macos.md, docs/content/mongocxx-v3/installation/windows.md, etc/apidocmenu.md, etc/generate-all-apidocs.pl
Done as part of the latest 3.6.7 release.
=> update docs for 3.6.5, 3.6.6, and 3.6.7

src/mongocxx/test/versioned_api.cpp
This PR is a followup to https://github.com/mongodb/mongo-cxx-driver/pull/863.
The Versioned API tests were not updated to account for backports of the count command in API Version 1 for server versions [5.0.9](https://jira.mongodb.org/browse/BACKPORT-12171) and [5.3.2](https://jira.mongodb.org/browse/BACKPORT-12170). The recent updates to server versions in https://github.com/eramongodb/drivers-evergreen-tools/commit/5aa1ff7651e91b724234d820f2cae6d61737fbc4 exposed this issue when running Versioned API tests against server 5.0.9.
=> CXX-2464 Update Versioned API tests to correctly handle backports

src/mongocxx/database.hpp
Resolves CXX-2298. Applying the same pattern used to resolve CDRIVER-4074.
=> CXX-2298 Update createCollection() documentation with Time Series link

etc/calc_release_version.py
Includes changes made in the following commits, with adjustments for the
specifics of the C++ driver project.
mongodb/mongo-c-driver@aca53d43accc6c6d611adfb90c2a53bfe36d44af
mongodb/mongo-c-driver@a949c2a4ee2973415c5f8c29ca986de533a3f7ef
Evergreen patch build: https://spruce.mongodb.com/version/62c881662a60ed63416a4849/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2540 sync calc_release_version.py from C driver

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/633ee54c7742ae238d9a7b9d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Fix rpm package build

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/633ee88c3627e07378e4a944/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Fix rpm package build v3.7

README.md, etc/releasing.md
- remove link from public README
- in release procedure documentation note that auth is required
=> Evergreen link updates

.mci.yml
Workaround issue with newer sqlalchemy versions.
=> Sqlalchemy workaround

data/sessions/unified/implicit-sessions-default-causal-consistency.json
Full Evergreen patch build: https://spruce.mongodb.com/version/63dc30095623433cd3ee7228/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2548 sync causal consistency JSON test

data/collection-management/unified/clustered-indexes.json
=> Clustered Indexes for all Collections

data/crud/unified/aggregate-allowdiskuse.json, data/crud/unified/test_files.txt, src/mongocxx/test/spec/unified_tests/operations.cpp
=> Make allowDiskUse opt-out rather than opt-in in 6.0

examples/bsoncxx/getting_values.cpp
- add example of extracting a string
Motivated by request in CXX-2581.
=> CXX-2581 add example of extracting a string

etc/calc_release_version.py
Evergreen patch build: https://spruce.mongodb.com/version/646e3e3e9ccd4e1799389cce/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> CXX-2694 use setuptools rather than distutils (deprecated) for version calc

.evergreen/build_snapshot_rpm.sh, .evergreen/debian_package_build.sh, debian/control
Full patch build: https://spruce.mongodb.com/version/64de8a9da4cf47a4aa420542/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Fix packaging tasks

docs/content/mongocxx-v3/installation/_index.md
CXX-2623
Update documentation to inform user of Vcpkg and Conan packages as well as the new Docker image.
=> Inform user of Vcpkg and Conan packages and the new Docker image

etc/releasing.md, extras/docker/README.md
- Update release notes to include updates to the Docker Hub Overview.
- Check in current Docker Hub Overview as the file README.md
See overview here: https://hub.docker.com/r/mongodb/mongo-cxx-driver
=> add release notes to update Docker Hub overview

debian/changelog, debian/copyright, debian/libbsoncxx-noabi.lintian-overrides
=> Debian packaging 3.9.0-1

extras/docker/README.md
=> Update docker tag to 3.9.0 in documentation

data/index-management/createSearchIndex.json, data/index-management/createSearchIndexes.json, data/index-management/dropSearchIndex.json, data/index-management/listSearchIndexes.json, data/index-management/searchIndexIgnoresReadWriteConcern.json, data/index-management/updateSearchIndex.json
Sync tests from https://github.com/mongodb/specifications/pull/1485
=>  CXX-2799 sync tests from DRIVERS-2797

CHANGELOG.md
Slipped through https://github.com/mongodb/mongo-cxx-driver/pull/1078.
=> Fix typo in CHANGELOG entry

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/version/65e647b2d1fe0746b2315953/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Update rpm spec

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Evergreen patch build: https://spruce.mongodb.com/task/mongo_cxx_driver_latest_release_packaging_rpm_package_build_patch_ca45450a603294f93bae5c1087e68d922a39fbbd_65e64bd4306615b0c9abe37d_24_03_04_22_31_49/logs?execution=0
=> Update rpm spec (v3.10)

.evergreen/debian_package_build.sh, .mci.yml
Patch build: https://spruce.mongodb.com/version/664cfe44664435000778feda/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> Fix debian package build

src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/topology_description.cpp
Resolves CXX-3037. See ticket for details.
=> CXX-3037 Address Coverity issue 119926

etc/releasing.md
=> Update release instructions with suspension note (CXX-3012, CXX-3042)

examples/README.md, examples/mongocxx/mongodb.com/documentation_examples.cpp
[evergreen](https://spruce.mongodb.com/version/666c7eef283b1a00075c6a70/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[ticket](https://jira.mongodb.org/browse/CXX-2840)
Added docs example for projection with aggregation. Expanded server version check within the documentation_examples file and moved it to the top of the file for easier use. Fixed a broken link in the examples/README.
=> CXX-2840 Docs example request: Projection with aggregation expressions

etc/apidocmenu.md, etc/generate-all-apidocs.pl
=> Prepare to generate r3.10.2 release documentation

.mci.yml
Addresses `evergreen validate` warnings related to DEVPROD-7666.
=> Replace ubuntu1804-build -> ubuntu1804-large

.evergreen/spec.patch
Single-task patch build: https://spruce.mongodb.com/version/66c7974d1603a40007108826/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> rpm-package-build: post-release version bump

CHANGELOG.md, Doxyfile, README.md, etc/apidocmenu.md, etc/generate-latest-apidocs.pl
=> CXX-2789 Post-release changes for 3.11.0

.mci.yml, etc/releasing.md
Minor improvements to release instructions following the 3.11.0 release.
=> Update release instructions following r3.11.0

.evergreen/build_snapshot_rpm.sh, .evergreen/spec.patch
Changes needed post-3.11 release.
Evergreen patch build: https://spruce.mongodb.com/version/670417024991430007476fe4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> RPM packaging updates

src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/command_failed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/command_started_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/server_changed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/server_closed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/server_opening_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/topology_changed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/topology_closed_event.hpp, src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/topology_opening_event.hpp, src/mongocxx/test/client_side_encryption.cpp, src/mongocxx/test/gridfs/bucket.cpp, src/mongocxx/test/spec/unified_tests/runner.cpp
Resolves CXX-3114. Similar set of changes to those in https://github.com/mongodb/libmongocrypt/pull/888 and https://github.com/mongodb/mongo-c-driver/pull/1746.
=> CXX-3114 Fix and update references to Markdown MongoDB specifications

CHANGELOG.md
No significant changes required.
=> Update CHANGELOG for 4.0.0

etc/releasing.md
Documents the change corresponding to https://github.com/mongodb/mongo-cxx-driver/pull/1287.
=> Add instruction to update the check-augmented-sbom.sh script

.evergreen/config_generator/etc/distros.py
Applies [this wonderful suggestion](https://github.com/mongodb/mongo-c-driver/pull/1890#discussion_r1974067754) to the C++ Driver's distro list.
=> Use list unpacking operator for distro lists

etc/generate-latest-apidocs.sh, etc/releasing.md
This PR includes tweaks following the 4.1.1 release. See individual commits for descriptions.
=> Update release instructions

CHANGELOG.md, Doxyfile, README.md, etc/apidocmenu.md, etc/augmented.sbom.json, etc/cyclonedx.sbom.json, etc/generate-latest-apidocs.sh
Update changelog, docs, and SBOM serial number following the 4.1.3 release.
=> apply changes from 4.1.3 release
