mongodb/mongo-cxx-driver

.mci.yml

Note: the new buildvariant will only compile and run the unit tests.  The ssl and sasl libraries are not available for 32-bit windows, so we'll build without them and skip the client and integration tests.

Add a 32-bit windows buildvariant

---

README.md
SConstruct
etc/doxygen/config

There are two separate commits here, the BUMP and the post, along with more stubstantial than usual updates to the README. I figured, since we got this wrong for rc4 we should codereview.
The two commits need to be reviewed independently, not as cumulative edits.

Prepare for 1.0.0 release

---

src/mongo/driver/CMakeLists.txt

- fixes install target to actually install headers (currently nothing is installed)
- fixes install target to copy generated version.hpp from the build directory (without polluting the source tree)

fix mongocxx installation

---

src/mongo/logger/log_domain.h
src/mongo/logger/log_severity.h
src/mongo/logger/message_event.h

The change is meant to allow apps to hook user-defined log-callbacks in order for the driver's logs to be intercepted.
(see https://groups.google.com/forum/#!topic/mongodb-dev/dfc89gSvr7E)

Exported logging-related symbols

---

src/mongo/client/dbclient.cpp
src/mongo/integration/standalone/dbclient_test.cpp

Follow up of https://groups.google.com/forum/#!topic/mongodb-dev/oKnOaF56gto for the getMaxTimeMs() part:
- added static variable to hold the string "$maxTimeMS" in order to avoid mistakes
- adapted the tests in order to check if the *{m|M}axTimeMs() functions behave correctly

CXX-536: Query::getMaxTimeMs() does not use the correct field name

---

src/mongocxx/bulk_write.cpp
src/mongocxx/bulk_write.hpp
src/mongocxx/client.cpp
src/mongocxx/client.hpp
src/mongocxx/collection.cpp
src/mongocxx/collection.hpp
src/mongocxx/cursor.cpp
src/mongocxx/cursor.hpp
src/mongocxx/database.cpp
src/mongocxx/database.hpp
src/mongocxx/read_preference.cpp
src/mongocxx/read_preference.hpp
src/mongocxx/uri.cpp
src/mongocxx/uri.hpp
src/mongocxx/write_concern.cpp
src/mongocxx/write_concern.hpp

I think it is OK to expose the interface as suggested by @acmorrow using stdx::optional so that we reserve the right to optionally return a pointer but actually always do so in the implementation. Questions, comments, and tips are all welcome.

CXX-533 safely expose implementation to users

---

src/mongo/integration/standalone/dbclient_test.cpp

see: http://docs.mongodb.org/manual/reference/command/create/#dbcmd.create
still unsure why it was passing in the first place.

CXX-546 test should pass 'flags' option key instead of 'usePowerOf2Sizes'

---

SConstruct
src/mongo/bson/bson-inl.h
src/mongo/bson/bson_validate.cpp
src/mongo/bson/bson_validate_test.cpp
src/mongo/bson/bsonobjbuilder.h
src/mongo/bson/util/builder.h
src/mongo/client/dbclient.cpp
src/mongo/client/dbclient_rs.cpp
src/mongo/client/dbclientinterface.h
src/mongo/util/net/ssl_manager.cpp
src/mongo/util/net/ssl_options.h
src/mongo/util/version.cpp

Note that this is the backport of both 2.6.8 and 2.6.9. Server 2.6.8 had a client affecting bug, so we aren't going to be issuing a 26compat 2.6.8 release; opting instead to move on to 2.6.9 which contains the fix for the regression.
Please give it a look. There is more here than I expected. I'm particularly interested in someone evaluating the listCollections changes.

CXX-479 Backport server r2.6.7..r2.6.9 changes

---

SConstruct
src/SConscript
src/SConscript.client

This isn't pretty, but it gets rid of the annoying startup warnings and and delay when running things that aren't the examples.

CXX-500 Only start mongo-orchestration from Scons when running examples

---

src/mongo/integration/replica_set/read_preference.cpp

I am going to limit this to read_preference_test as that is the only place we have the problem of test setup failing.

CXX-599 call std::abort() if SetUpTestCase fails in read_preference_test

---

src/mongocxx/test/collection.cpp
src/mongocxx/test/collection_mocked.cpp

I'm not using the mocking framework here because there isn't a clean way to interpose distinct without
using private APIs of the C driver.

CXX-555 add test coverage for collection::distinct

---

src/bsoncxx/array/value.hpp
src/bsoncxx/b64_ntop.h
src/bsoncxx/config/prelude.hpp
src/bsoncxx/document/value.hpp
src/bsoncxx/types.hpp
src/mongocxx/client.hpp
src/mongocxx/collection.hpp
src/mongocxx/config/prelude.hpp
src/mongocxx/database.hpp

CXX-553 include inline keyword in inline macros

---

SConstruct
src/mongo/util/net/sock.cpp
src/mongo/util/net/ssl_manager.cpp
src/mongo/util/net/ssl_options.h
src/mongo/util/version.cpp

I'm being an optimist and assuming that server 2.6.10-rc0 will become server 2.6.10. If so, then these are the changes we would ship in the 26compat driver. Note that we would fix up the version before we did our label.

CXX-571 Backport server 2.6.9..2.6.10 changes

---

src/bsoncxx/oid.cpp

Had some issues regarding oids. Found a missing memcpy. The memcpy could be avoided by storing the result of a hex conversion directly in _bytes but the rest of the code seems to use the bson_oid_* functions so I just added the memcpy.

CXX-661 - Added missing memcpy in oid constructor.

---

src/mongo/integration/standalone/dbclient_test.cpp

the format of the profiling collection has changed.

CXX-698 make DBClientTest.Comment work on 3.1+ servers

---

.travis.yml

on travis now we only run the unit tests

CXX-708 make mongo-orchestration less flaky on travis

---

src/mongocxx/test/pool.cpp

switch max_align_t to global scope

Tests now pass on Evergreen

---

src/mongo/bson/util/builder_test.cpp

I have verified this on all support platforms & compilers in Evergreen including the 32-bit builders.

CXX-709: Fix reinterpret_cast for VS 2015

---

src/mongocxx/collection.hpp
src/mongocxx/result/insert_many.cpp
src/mongocxx/result/insert_many.hpp

(contrary to the comment, this isn't / wasn't used in our tests...)

CXX-635: fix visibility of insert_many constructor

---

src/mongocxx/result/bulk_write.cpp
src/mongocxx/result/bulk_write.hpp
src/mongocxx/result/delete.cpp
src/mongocxx/result/delete.hpp
src/mongocxx/result/insert_many.cpp
src/mongocxx/result/insert_many.hpp
src/mongocxx/result/replace_one.cpp
src/mongocxx/result/replace_one.hpp
src/mongocxx/result/update.cpp
src/mongocxx/result/update.hpp
src/mongocxx/test/result/delete.cpp
src/mongocxx/test/result/replace_one.cpp
src/mongocxx/test/result/update.cpp

The server and C driver both return int_32's for these commands, the bsoncxx `get_int64()` was causing and error.

CXX-681: fix bulk_write results to return int_32t values

---

src/mongo/client/dbclient.cpp
src/mongo/client/wire_protocol_writer.cpp
src/mongo/integration/standalone/dbclient_test.cpp

Per DRIVERS-250, when the a driver uses the legacy write operations to support unacknowledged writes, and the user sets bypassDocumentValidation, the driver should error.
Note: We cannot differentiate between a user setting bypassDocumentValidation to false, or if bypassDocumentValidation was simply initialized to false via default parameter at the moment. This could addressed, but I do not think it is worth the cost to differentiate these two scenarios.

CXX-689 Assert bypassDocumentValidation is not used with unacknowledged writes

---

src/mongo/client/write_concern_test.cpp

According to the [read and write concern spec](https://github.com/mongodb/specifications/blob/master/source/read-write-concern/read-write-concern.rst):
> An `Unacknowledged WriteConcern` is when (`w` equals 0) AND (`journal` is not set or is `false`).
This change adds a few simple unit tests to ensure our compliance. There are no other changes.

CXX-696: Add tests to verify spec compliance with unacknowledged write concerns

---

src/mongo/client/dbclient.cpp
src/mongo/client/dbclient_rs.h
src/mongo/client/dbclientinterface.h
src/mongo/client/write_result.cpp
src/mongo/client/write_result.h
src/mongo/integration/replica_set/basic.cpp

Per an update to DRIVERS-224, I added a test to verify `findAndModify` uses writeConcern correctly. This was important because `findAndModify` goes through a different code path the insert/update/delete.
Changes
1. Make `getMaxWireVersion` so that replica set connections can check it. This uses the primary. It is undefined if customers are using mixed version clusters.
2. Check `WriteResult` in `_findAndModify` to verify the writeConcern in this code path.

CXX-692 Check writeConcern errors in findAndModify

---

src/mongo/platform/random_test.cpp

I broke this when I cherry-picked this from the server, since the server version used C++11. Please see this mongodb-dev thread for context:
https://groups.google.com/forum/#!topic/mongodb-dev/BWcidH1EWaU

CXX-744 Fix incorrect types used to hold 64 bit values

---

.mci.yml
.travis.yml
CMakeLists.txt
examples/CMakeLists.txt
examples/bsoncxx/CMakeLists.txt
examples/mongocxx/CMakeLists.txt

Note: cmake must be configured with `-DBUILD_EXAMPLES=true` in order to build the example executables.

CXX-734: 'make examples' will run all examples

---

src/mongocxx/collection.cpp
src/mongocxx/options/aggregate.cpp
src/mongocxx/options/aggregate.hpp
src/mongocxx/options/count.cpp
src/mongocxx/options/count.hpp
src/mongocxx/options/distinct.cpp
src/mongocxx/options/distinct.hpp
src/mongocxx/options/find.cpp
src/mongocxx/options/find.hpp
src/mongocxx/options/find_one_and_delete.cpp
src/mongocxx/options/find_one_and_delete.hpp
src/mongocxx/options/find_one_and_replace.cpp
src/mongocxx/options/find_one_and_replace.hpp
src/mongocxx/options/find_one_and_update.cpp
src/mongocxx/options/find_one_and_update.hpp
src/mongocxx/test/collection_mocked.cpp
src/mongocxx/test/options/aggregate.cpp
src/mongocxx/test/options/find.cpp
src/mongocxx/test/options/find_one_and_delete.cpp
src/mongocxx/test/options/find_one_and_replace.cpp
src/mongocxx/test/options/find_one_and_update.cpp

I had a couple questions:
For the find options, why do we have both max_time and max_await_time? max_time is not used.
For the methods where the max_time is not used, should I investigate whether it's possible to pass it to the C driver yet?

CXX-751 - Specify timeouts with chrono

---

examples/CMakeLists.txt

When generating makefiles with CMake, a paralleized build such as "make -j8" does not work because the examples try to compile over a local installation which is not finished yet.
This can be solved by adding the right dependencies.
Jira issue: https://jira.mongodb.org/browse/CXX-774

CXX-774: Add dependencies to make paralleized build available

---

CMakeLists.txt
src/mongocxx/test/CMakeLists.txt

Fixes [CXX 781](https://jira.mongodb.org/browse/CXX-781) by introducing `THIRD_PARTY_SOURCE_DIR` variable set in root `CMakeLists.txt` file.
(Additionally corrects a typo in `clang-modernize` settings.)

CXX-781 CMake path incorrect when subproject

---

.mci.yml
.travis.yml

https://evergreen.mongodb.com/version/568ab75a3ff1222e7e0002c6_0
Do I need to do anything separate for travis?

CXX-795 - Add bsoncxx unit tests to evergreen builds

---

src/mongocxx/bulk_write.cpp
src/mongocxx/bulk_write.hpp
src/mongocxx/client.cpp
src/mongocxx/client.hpp
src/mongocxx/collection.cpp
src/mongocxx/collection.hpp
src/mongocxx/cursor.cpp
src/mongocxx/cursor.hpp
src/mongocxx/database.cpp
src/mongocxx/database.hpp
src/mongocxx/pool.cpp
src/mongocxx/pool.hpp
src/mongocxx/read_preference.cpp
src/mongocxx/read_preference.hpp
src/mongocxx/test/collection_mocked.cpp
src/mongocxx/test/pool.cpp
src/mongocxx/uri.cpp
src/mongocxx/uri.hpp
src/mongocxx/write_concern.cpp
src/mongocxx/write_concern.hpp

This weakens some tests. @Machyne I think maybe these were tests you added? I'd like to understand how much we think we have lost.
Also, I'm puzzled why we didn't get deprecation warnings for use in the tests. I will look into that .

CXX-786 Remove deprecated 'implementation' methods

---

src/mongocxx/bulk_write.cpp
src/mongocxx/bulk_write.hpp
src/mongocxx/collection.cpp
src/mongocxx/collection.hpp
src/mongocxx/insert_many_builder.cpp
src/mongocxx/options/bulk_write.cpp
src/mongocxx/options/bulk_write.hpp
src/mongocxx/test/bulk_write.cpp
src/mongocxx/test/collection.cpp

While looking into making an example for producing bulk writes per the user request in CXX-791, I noticed that the bulk write subsystem was a little broken.
The options for a bulk write belong on options::bulk_write, not on libmongocx::bulk_write, which should simply be an accumulator for model::write objects.
Instead, the options should be provided via options::bulk_write when creating a bulk_write object.

CXX-791 Options for bulk ops should be on the options::bulk_op type

---

src/bsoncxx/CMakeLists.txt
src/bsoncxx/string/view_or_value.cpp
src/bsoncxx/string/view_or_value.hpp
src/bsoncxx/test/view_or_value.cpp
src/bsoncxx/view_or_value.hpp
src/mongocxx/client.cpp
src/mongocxx/client.hpp
src/mongocxx/collection.cpp
src/mongocxx/collection.hpp
src/mongocxx/database.cpp
src/mongocxx/database.hpp
src/mongocxx/private/collection.hpp
src/mongocxx/private/database.hpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/collection_mocked.cpp
src/mongocxx/test/database.cpp

A new bsoncxx::string::view_or_value type that provides safe (null-terminated) conversion to const char*.

CXX-739 string::view_or_value

---

examples/mongocxx/bulk_write.cpp
src/mongocxx/result/bulk_write.cpp
src/mongocxx/result/bulk_write.hpp
src/mongocxx/result/replace_one.cpp
src/mongocxx/result/update.cpp
src/mongocxx/test/collection.cpp

The C driver does not return the inserted IDs in bulk_write results, so we won't either. It is not required by the CRUD spec (https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst).
I chose to have result::bulk_write::upserted_ids return a std::map<std::size_t, bsoncxx::document::element>, where the first element is the operation index in the bulk write, and the second is {"_id" : ...}. This is analogous to result::insert_many::inserted_ids.

CXX-798 - Fix result::bulk_write::upserted_ids and remove inserted_ids

---

src/bsoncxx/string/view_or_value.cpp
src/bsoncxx/string/view_or_value.hpp
src/bsoncxx/test/view_or_value.cpp
src/bsoncxx/view_or_value.hpp
src/mongocxx/collection.cpp
src/mongocxx/database.cpp

@acmorrow this PR contains the change we discussed earlier.
I also added a `.data()` method to the `string::view_or_value` class.  Doing so allows us a place to explain to use terminated() first, and also makes `view_or_value.terminated().data()` possible instead of having to write `view_or_value.terminated().view().data()`.

CXX-801 Use .terminated().data() to extract safe c-strings

---

.mci.yml
.travis.yml
src/mongocxx/test/collection_mocked.cpp

Note that we currently need -Wno-attributes to avoid being overwhelmed by warnings
generated by MNMLSTC core.

CXX-777 Build with Wall, Wextra and Werror to hold the line on warnings

---

.mci.yml
etc/ubsan.blacklist

This already passes in evergreen. Yay no undefined behavior!

CXX-425 Add UBSAN builder to evergreen

---

src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt
src/mongocxx/options/modify_collection.cpp
src/mongocxx/test/collection_mocked.cpp

Make it easier to select the other polyfills by not needing to explicitly disable mnmlstc at the same time. Also validate that the combination of options is sensible.

CXX-817 Improve bsoncxx polyfill options handling

---

src/bsoncxx/CMakeLists.txt

No point making things hard for users. Right now the only way to build the driver on Windows is with Boost, so default to that.

CXX-819 Default to boost polyfills on MSVC

---

.mci.yml

Currently red (https://evergreen.mongodb.com/version/569d4a2f3ff1227dfb000040_0) but has fixes for many of those issues pending in #441.

CXX-820 Add valgrind support on MCI

---

README.md
appveyor.yml

This adds a simple Windows Builder to the C++ driver master branch. This is just the Release build for the moment to help ensure submissions build on Windows.
It uses VS 2015 Update 1.

CXX-826 AppVeyor Integration

---

.mci.yml
.travis.yml
CMakeLists.txt
appveyor.yml
examples/CMakeLists.txt
examples/bsoncxx/CMakeLists.txt
examples/mongocxx/CMakeLists.txt
src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt
src/mongocxx/test/CMakeLists.txt

Also, don't build the examples as part of the 'all' target. Instead
require users to build them explicitly by building the 'examples'
target.

CXX-825 Use bigobj for the mocked library as well

---

src/mongocxx/options/create_collection.hpp
src/mongocxx/options/find_one_and_replace.hpp
src/mongocxx/options/find_one_and_update.hpp
src/mongocxx/options/modify_collection.hpp
src/mongocxx/validation_criteria.hpp

Note: the todos related to read_concern are fixed in the read_concern pull request.

CXX-821 Add links to document validation documentation

---

.mci.yml
etc/clang_format.py
src/bsoncxx/builder/basic/array.hpp
src/bsoncxx/builder/basic/sub_array.hpp
src/bsoncxx/builder/core.cpp
src/bsoncxx/builder/stream/array.hpp
src/bsoncxx/builder/stream/array_context.hpp
src/bsoncxx/builder/stream/document.hpp
src/bsoncxx/builder/stream/key_context.hpp
src/bsoncxx/builder/stream/single_context.hpp
src/bsoncxx/builder/stream/value_context.hpp
src/bsoncxx/document/element.hpp
src/bsoncxx/exception/error_code.hpp
src/bsoncxx/json.cpp
src/mongocxx/cursor.hpp
src/mongocxx/exception/error_code.cpp
src/mongocxx/exception/error_code.hpp
src/mongocxx/exception/server_error_code.cpp
src/mongocxx/exception/server_error_code.hpp
src/mongocxx/private/libmongoc.cpp

Since Travis runs on Ubuntu 12.04, we cannot use `-C` with `git` so we must continue to work around it.
Mac OS X 10.6 `tar` does not support `bzip2` compressed files.

CXX-835 Support lint when run from non-repository root

---

src/mongocxx/test/pool.cpp

This is hideous, but necessary when building with clang against libstdc++ from GCC 4.8.2. Fortunately it is:
- Only in a test
- Only needed in one place
So, I haven't bothered to try to macro it out.

CXX-865 Enable building with clang with libstdc++ from GCC 4.8

---

src/bsoncxx/builder/basic/sub_array.hpp
src/bsoncxx/builder/basic/sub_document.hpp

Linking to bsoncxx.dll (with VC++ 2015) fails because the `BSONCXX_API` macro instructs VC++ to `dllimport` the classes sub_array and sub_document while these classes are header only (and thus not exported by the dll).
Removing the macro fixes the issue.

CXX-893 Removed BSONCXX_API macro from non exported classes to fix link errors

---

examples/mongocxx/CMakeLists.txt
examples/mongocxx/connect.cpp
src/mongocxx/client.cpp
src/mongocxx/instance.cpp
src/mongocxx/logger.cpp
src/mongocxx/logger.hpp
src/mongocxx/pool.cpp
src/mongocxx/private/client.hpp
src/mongocxx/private/libmongoc_symbols.hpp
src/mongocxx/private/pool.hpp
src/mongocxx/private/ssl.hpp
src/mongocxx/test/pool.cpp
src/third_party/catch/include/helpers.hpp

@Machyne @xdg - please review.
@ajdavis - apparently, the C driver doesn't make owned copies of the strings passed in via http://api.mongodb.com/c/current/mongoc_client_set_ssl_opts.html. That is apparently documented, but pretty user hostile and definitely caused me some grief and time in the debugger. Any chance of changing that?

CXX-917 Make SSL actually work

---

src/mongo/client/dbclient.cpp
src/mongo/integration/standalone/dbclient_test.cpp

I manually tested this by issuing a kill -9 to mongod right before a call to getCollectionNames(), and ditto with getCollectionInfos().  I assume that this particular fix should be committed without tests, but let me know.
The error message is copy-pasted from elsewhere in this file.
@acmorrow, PTAL.

CXX-906 Fix null deref in getCollectionNames()/getCollectionInfos()

---

SConstruct

Initialization of `env["MONGO_SSL"]` on non-SSL builds was accidentally deleted when backporting `e5f5b4e` from the server repository, as part of legacy commit dc6e44b.  See the old initialization on the left-hand side of the diff at [SConstruct:935](https://github.com/mongodb/mongo-cxx-driver/commit/dc6e44bb#diff-cc8093822b396591a5530a463c87d048L935).

CXX-928 Fix bad merge of SConstruct in dc6e44b

---

appveyor.yml

Pin the C driver to 1.3.4 in Appveyor to match travis.

CXX-969 appveyor.yml - pin C driver to 1.3.4

---

CMakeLists.txt
src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt

Not an ideal solution: we still actually build the shared libraries, we just don't install them. Otherwise, we would need to conditionalize every block that references the shared library target with if (BUILD_SHARED_LIBS), which seems pretty bad. Not wanting the shared library is a pretty special case, so I'm OK with requiring them to build them, but avoiding installing.

CXX-957 Honor BUILD_SHARED_LIBS to a sufficient degree

---

examples/mongocxx/CMakeLists.txt
examples/mongocxx/get_values_from_documents.cpp

I wrote out the types long-hand instead of using 'auto' into order
to better educate readers about what types are being used.
I also omitted most error handling to keep the focus on working with
the cursor, documents, arrays and elements.

CXX-861 Add example iterating cursor and getting data out

---

src/bsoncxx/document/element.hpp
src/bsoncxx/json.hpp
src/bsoncxx/oid.hpp
src/mongocxx/client.hpp
src/mongocxx/collection.hpp
src/mongocxx/cursor.hpp
src/mongocxx/database.hpp
src/mongocxx/instance.hpp
src/mongocxx/pool.hpp
src/mongocxx/write_concern.hpp

This commit updates all the documented exception names to the current types
and adds 'throws' entries to several methods where they were omitted.
Also includes CXX-988 (Fix documentation of element::operator[]).

CXX-916 Fix documented exceptions

---

src/mongocxx/collection.cpp
src/mongocxx/test/collection.cpp

@xdg @jrassi @Machyne @bjori -
This improves the error handling after calling mongoc_collection_find_and_modify_with_opts. We need to handle two cases:
- The function returned false, but the 'reply' bson is not populated, in which case we simply throw an error wrapping the bson_error_t.
- The function returned false, but the reply bson IS populated, in which case we throw the raw server reply along with the bson_error_t.
I also added a regression test to verify the improvement, based on the repro in the original ticket. I was able to reproduce the original crash when running the test without the new error handling, and the fix does make the test pass and throw a meaningful exception.

CXX-986 Improve find_and_modify error handling

---

src/bsoncxx/array/value.hpp
src/bsoncxx/document/value.hpp

This is mostly academic as we are controlling the deleter here, so the wrong thing wasn't happening. However, there is at least one other difference between unique_ptr<T> and unique_ptr<T[]> (the existence of operator[]), and there may be others in the future. It seems better to say what we mean here. @hanumantmk PTAL.

Use correct unique_ptr types for document and array values

---

src/mongocxx/options/find.cpp
src/mongocxx/options/find.hpp
src/mongocxx/test/options/find.cpp

New options added:
- max
- max_scan
- min
- return_key
- show_record_id
- snapshot
These will replace the "modifiers" option.

CXX-1051 Add new options to options::find

---

.mci.yml
.travis.yml

libmongoc master has updated its libbson submodule to include
the fix that should allow us to remove `--disable-decimal-bid`.

CXX-1033 Re-enable decimal128 in libbson compilation for CI

---

src/mongocxx/options/create_collection.cpp
src/mongocxx/test/options/create_collection.cpp

Previously, options::create_collection::_no_padding was always
serialized incorrectly.

CXX-1072 create_collection::to_document(): serialize _no_padding fix

---

src/mongocxx/collection.cpp
src/mongocxx/hint.cpp
src/mongocxx/hint.hpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/collection_mocked.cpp
src/mongocxx/test/hint.cpp

First included commit is an ABI-breaking/API-breaking small refactor.  Second commit is the bugfix itself.
@acmorrow @xdg, PTAL.

CXX-1045 collection::count() serializes options::count::hint incorrectly

---

src/mongocxx/read_concern.cpp
src/mongocxx/test/read_concern.cpp

Fixes a bug where passing the empty string to
read_concern::acknowledge_string() would incorrectly set the read
concern level to read_concern::level::k_unknown, instead of the
correct value of read_concern::level::k_server_default.

CXX-1062 read_concern::acknowledge_string("") sets level to default

---

.mci.yml

The server no longer builds on RHEL 5, so the source server binary
link for the RHEL 5.5 Evergreen variant is out of date.

CXX-1088 RHEL 5 Evergreen variant should use v3.2-latest server binary

---

src/mongocxx/CMakeLists.txt
src/mongocxx/collection.cpp
src/mongocxx/database.cpp
src/mongocxx/database.hpp
src/mongocxx/options/create_view.cpp
src/mongocxx/options/create_view.hpp
src/mongocxx/pipeline.cpp
src/mongocxx/pipeline.hpp
src/mongocxx/private/pipeline.hh
src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/database.cpp
src/mongocxx/test/options/create_view.cpp

@acmorrow @xdg, PTAL.
I modeled the design of database::create_view() off of the approach taken for [JAVA-2286](https://jira.mongodb.org/browse/JAVA-2286).  Note that I couldn't find record of any other driver having a collMod helper, so I just went ahead and added the view-related options to options::modify_collection() (though I also filed [CXX-1058](https://jira.mongodb.org/browse/CXX-1058) to have us consider deprecating database::modify_collection() outright).
Follow-up work:
- Collation support for views will be addressed in [CXX-971](https://jira.mongodb.org/browse/CXX-971).
- Updating the 3.3 development series documentation link will be addressed in [CXX-1061](https://jira.mongodb.org/browse/CXX-1061).

CXX-999 Support read-only views

---

src/mongocxx/bulk_write.cpp
src/mongocxx/test/bulk_write.cpp

@xdg, PTAL.
Per discussion, this change is accompanied by mock tests only.  While integration tests would be preferable, using the existing bulk_write test infrastructure is more expedient, and we will eventually get partial integration test coverage for this change once the collation integration tests land for the collection class (specifically `collection::update_one()`, `collection::delete_one()`, etc).

CXX-971 (part 9) Add collation support for bulk_write class

---

src/mongocxx/exception/error_code.cpp
src/mongocxx/exception/error_code.hpp
src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/database.cpp
src/mongocxx/test_util/client_helpers.cpp
src/mongocxx/test_util/client_helpers.hh
src/mongocxx/test_util/mock.hh

@xdg, PTAL.
This is groundwork for the collation integration tests.

CXX-971 (part 8) Add client helpers to test_util

---

src/mongocxx/collection.cpp
src/mongocxx/test/collection.cpp

@xdg, PTAL.
Note that the existing collection integration tests do a weird mix of holding onto `bsoncxx::builder::stream::document` and `bsoncxx::document::value` local variables.  I've attempted to write new tests that are consistent with the existing tests (with the hope that we'll revisit integration testing in general within the next few months), but I'd be happy to make the new tests look somewhat different from the existing tests if you'd prefer.

CXX-971 (part 10) Add collation support for collection find/find_one

---

src/mongocxx/test/database.cpp

@xdg, PTAL.
Note that this change purely adds integration test coverage for `database::create_collection()` and `database::create_view()`.  Collation support for these methods was already added in #548 and #564 (respectively), due to the `to_document()` design of these options classes.

CXX-971 (part 15) Add collation integration tests for create_collection() and create_view()

---

src/mongocxx/options/find.hpp

@xdg, PTAL.
As part of the resolution of CXX-1056, we will go through all of the `@deprecated`-tagged method declarations and add MONGOCXX_DEPRECATED specifiers, including these two.

CXX-1051 Deprecate options::find::modifiers()

---

src/bsoncxx/types.hpp

We made conversion operators constant for bsoncxx types to make it possible to write like this:
```
const bsoncxx::types::value& value{ ... }; // some value extracted from a document element
bsoncxx::stdx::string_view str_view{ value.get_utf8() };
```
Without const qualifier I have to use intermediate non-constant variable:
```
bsoncxx::types::b_utf8 utf8{ value.get_utf8() };
bsoncxx::stdx::string_view str_view{ utf8 };
```

CXX-1159 Make unwrapping conversion operators constant

---

docs/content/mongocxx-v3/tutorial.md

Hey team, this is just a few minor typos in the tutorial. I'm not familiar with the C++ driver contribution process, so please let me know if I should file a JIRA ticket/edit the commit messages/etc.
In addition: I'm not familiar with formatting, so I don't exactly know how to fix this, but it seems that`h5` doesn't seem to have styling on [the tutorial page](https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/tutorial/). For example, see the "Get A Single Document That Matches a Filter" section; it's formatted the same as plain text.

minor: fix typos in tutorial

---

src/mongocxx/private/libmongoc.cpp
src/mongocxx/private/libmongoc.hh

This works around the GCC bug where it is interpreting the export attributes on the mongo-c-driver functions while constructing the mocks. Just suppress the warning in that narrow context with a diagnostic pragma.

CXX-1453 Suppress ignored attributes in test mocks due to GCC bug

---

src/bsoncxx/util/functor.hpp
src/mongocxx/private/libbson.cpp

These two commits don't address the central issue of CXX-1460, which is that GCC thinks there is an ambiguity between the scoped_bson_t constructors in C++17 mode, but clang requires both overloads. I'm not sure which compiler is in the right, yet.
In the meantime, this adds a clearly missing header, and adds some missing calls to `std::move` that were observed while looking into the implementation of `scoped_bson_t`.

CXX-1460 Small fixups

---

src/bsoncxx/document/element.cpp

In BSON document element class, the get_timestamp() accessor create a new b_timestamp object but with parameters timestamp and increment in the wrong order.

CXX-1553 Fix wrong call to b_timestamp ctor

---

src/mongocxx/options/ssl.hpp

```c++
///
/// If false, the driver will not verify the server's CA file.
///
/// @param allow_invalid_certificates
///   Whether or not to check the server's CA file.
///
/// @return
///   A reference to the object on which this member function is being called.  This facilitates
///   method chaining.
///
ssl& allow_invalid_certificates(bool allow_invalid_certificates);
```
Should be "If true, the driver will not verify the server's CA file."

fix allow_invalid_certificates documentation

---

docs/content/mongocxx-v3/tutorial.md

The header `<mongocxx/instance.hpp>` is missing on [Mongo CXX 3.0](http://mongocxx.org/mongocxx-v3/tutorial/) driver example, when the example is compiled a **core dump** error is issued. To fix, the `#include <mongocxx/instance.hpp>` was added to the example. The file / class its on */usr/local/include/mongocxx/v_noabi/mongocxx/instance.hpp*.

Missing header

---

cmake/BsoncxxUtil.cmake
examples/projects/bsoncxx/cmake/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake/static/CMakeLists.txt
examples/projects/mongocxx/cmake/shared/CMakeLists.txt
examples/projects/mongocxx/cmake/static/CMakeLists.txt

When trying to compile mongocxx driver against boost 1.71 I had to update boost linking. Note that using recent cmake (e.g 3.15) seems to fix the issue by introducing backward compatibility, but I think using Boost::boost is cleaner.

Cmake boost include

---

src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt

Similarly to https://github.com/mongodb/mongo-c-driver/pull/588:
Internally we rename the libraries we integrate as to avoid interference with the library versions already available on the target systems by giving them a prefix.
This PR allows users to specify, for example:
```
-DBSONCXX_OUTPUT_BASENAME:STRING=MYORG_bsoncxx
-DMONGOCXX_OUTPUT_BASENAME:STRING=MYORG_mongocxx
```
I used `BASENAME` as the flavor and/or version are appended later.
Alternatively, it would be also fine for us to add a prefix variable like `OUTPUT_NAME_PREFIX` or so but I was unable to find a good name that cannot be confused the target `PREFIX` property (e.g. `lib`)

Allow libbsoncxx and libmongocxx library names to be changed externally

---

docs/content/mongocxx-v3/installation.md

- also add links to CMake & Boost projects for context

Fix CXX-1899: Typos in install guide

---

src/mongocxx/collection.cpp

Mongo C++ Driver doesn’t populate the _writeConcern_ doc properly while sending a _find_one_and_update_ request to the mongo server. This was silently happening up until mongo 4.2 introduced stricter checks on the received payload. After which, a failure is seen.
This commit fixes _find_and_modify_ to populate _writeConcern_ in accordance with: https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/
More details: https://jira.mongodb.org/browse/CXX-2028

CXX-2028 fix writeConcern population in find_and_modify

---

src/mongocxx/test/collection.cpp

Test explicitly passing a write concern to a collection find_one_and_* function is applied correctly.

CXX-2028 Add regression test for write concern

---

.mci.yml
src/mongocxx/test/client_side_encryption.cpp

The tasks on the `ppc64le Ubuntu 16.04 (MongoDB Latest)` variant appear to be failing due to other reasons.

Skip FLE prose test on pre 4.2 servers

---

.mci.yml

MongoDB dropped support for MongoDB 4.2 in PowerPC Ubuntu 16.04:
https://docs.mongodb.com/manual/administration/production-notes/#ppc64le-mongodb-enterprise-edition
So the "latest" download for PowerPC Ubuntu 16.04 is actually a 4.1 development version. Based on the logs of [this task](https://evergreen.mongodb.com/task/cxx_driver_power8_ubuntu1604_compile_and_test_with_shared_libs_796c11cf072b2c5db23ce6492cb808bf4d6ff2c2_20_06_15_23_14_06): `db version v4.1.9-271-g501b707`
Client-Side Field Level Encryption is a 4.2 feature. I believe that version of mongocryptd is a development version that does not support the "isRemoteSchema" field, causing the:
```
mongocryptd error: BSON field 'insert.isRemoteSchema' is an unknown field.::
```
As a sidenote, this is an unreleased development …

CXX-2048 Temporarily skip tests on PPC Ubuntu 16.04

---

docs/content/mongocxx-v3/installation.md

Do not refer to boost versions older than 1.60.0.
Boost is not necessary when compiling with a C++17 compiler.

Clean installation docs boost references

---

src/mongocxx/instance.cpp

MSVC++ implements P0883 unconditionally, which changes the rules for std::atomic. It removes atomic's trivial constructor, and makes the default constructor value initialize the T.
Note that Mongo was not following the C++11 rules, because it used the atomic before calling atomic_init first. MSVC++ never implemented the C++11 rules and previously default initialized the T.
All versions of MSVC++ will provide constant initialization of the guarded value "current_instance". In old versions, atomic didn't implement P0883 due to bugs in the constexpr evaluator; in current versions the constexpr evaluator was fixed and atomic value initializes unconditionally. Therefore, this PR disables the check whenever MSVC++'s standard library is detected.
See https://github.com/microsoft/STL/issues/661 …

Disable trivially_constructible test for atomic on MSVC++.

---

.travis.yml
src/bsoncxx/test/bson_value.cpp
src/bsoncxx/types/private/convert.hh
src/mongocxx/client.hpp
src/mongocxx/options/encrypt.cpp
src/mongocxx/options/encrypt.hpp
src/mongocxx/test/client_session.cpp
src/mongocxx/test/client_side_encryption.cpp
src/mongocxx/test/spec/client_side_encryption.cpp
src/mongocxx/test_util/client_helpers.cpp
src/mongocxx/test_util/client_helpers.hh

- Remove non-essential getter with optional b_binary, which gives
an error with MNMLSTC and clang 3.6
- Remove redundant friend declaration
- Add explicit static casts for constructing a bson_value::view from
bson_value::value and std::string from string_view
- Fix session lambda to have a void return

CXX-2041 fix travis compile

---

.evergreen/compile.sh
.mci.yml
examples/projects/bsoncxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake-deprecated/shared/build.sh
examples/projects/bsoncxx/cmake-deprecated/static/CMakeLists.txt
examples/projects/bsoncxx/cmake-deprecated/static/build.sh
examples/projects/bsoncxx/cmake/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake/shared/build.sh
examples/projects/bsoncxx/cmake/static/CMakeLists.txt
examples/projects/bsoncxx/cmake/static/build.sh
examples/projects/mongocxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/shared/build.sh
examples/projects/mongocxx/cmake-deprecated/static/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/static/build.sh
examples/projects/mongocxx/cmake/shared/CMakeLists.txt
examples/projects/mongocxx/cmake/shared/build.sh
examples/projects/mongocxx/cmake/static/CMakeLists.txt
examples/projects/mongocxx/cmake/static/build.sh
src/mongocxx/test/spec/client_side_encryption.cpp
src/mongocxx/test/spec/util.cpp
src/mongocxx/test_util/client_helpers.cpp

- Upgrade Windows in matrix tasks to run "latest" and "4.4" as part of
matrix.
- Fix a test helper for lowercasing error messages.
- Skip FLE tests we cannot run on unsupported operations.
- Build on VS 2017 with /EHsc to prevent tests from failing due to
destructors not being called when exceptions are thrown. (CXX-2054)

CXX-2042 Add 4.4 tasks to evergreen

---

src/mongocxx/test/client_session.cpp
src/mongocxx/test/spec/util.cpp

[CXX-2062](https://jira.mongodb.org/browse/CXX-2062) is a fix to a flaky test failure from the test runner not using majority write concern to insert the initial data.
[CXX-1953](https://jira.mongodb.org/browse/CXX-1953) is a new (consistent) test failure due to a change in libmongoc's session pool behavior from [CDRIVER-3322](https://jira.mongodb.org/browse/CDRIVER-3322)

CXX-2062 + CXX-1953 (Insert test data with wc:majority + Fix session tests)

---

.mci.yml
data/read-write-concern/operation/default-write-concern-2.6.json
data/read-write-concern/operation/default-write-concern-2.6.yml
data/read-write-concern/operation/default-write-concern-3.2.json
data/read-write-concern/operation/default-write-concern-3.2.yml
data/read-write-concern/operation/default-write-concern-3.4.json
data/read-write-concern/operation/default-write-concern-3.4.yml
data/read-write-concern/operation/default-write-concern-4.2.json
data/read-write-concern/operation/default-write-concern-4.2.yml
data/read-write-concern/operation/test_files.txt
src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/sdam-monitoring.cpp
src/mongocxx/test/spec/operation.cpp
src/mongocxx/test/spec/read_write_concern.cpp
src/mongocxx/test/spec/util.cpp
src/mongocxx/test/spec/util.hh

- Reuse transaction spec runner for read/write concern integration tests.
- Allow empty read/write concern in spec tests.

CXX-1875 add read/write concern tests

---

src/bsoncxx/CMakeLists.txt
src/bsoncxx/types/bson_value/value.hpp
src/bsoncxx/types/bson_value/view.cpp
src/bsoncxx/types/bson_value/view.hpp
src/bsoncxx/types/bson_value/view_or_value.hpp
src/mongocxx/options/encrypt.cpp
src/mongocxx/options/encrypt.hpp
src/mongocxx/test/client_side_encryption.cpp

- implement bson_value::view_or_value
- change options::encrypt::key_id() to take a bson_value::view_or_value
In our original discussion of this, we talked about changing this method to take a bson_value::value, to avoid creating tricky lifetime semantics.  However, most of our options that take documents take a document::view_or_value.  This allows the user to decide whether to give the options class ownership (by std::move-ing in a document::value) or to intentionally pass in a view and manage the lifetime themselves.  I think this is the most consistent and flexible approach for bson_value, too.

CXX-2063 options::encrypt::key_id() takes a bson_value::view_or_value

---

debian/gbp.conf

This removes the one-line workaround we needed for the first waterfall build of the `debian-package-build` task.  It is now absolute.
Patch build: https://spruce.mongodb.com/version/5f0852bcd1fe076124055e41/tasks
(Note that the patch build title mentions CXX-1739, but the `debian-package-build` task in that build reflects the change in this PR.)

(Debian packaging) remove archive generation workaround

---

etc/make_release.py
etc/releasing.md
etc/requirements.txt

Ports the Google doc into markdown to be commit into the repo. I think it is worthwhile to have the release documentation committed in the repo. Even though it is not useful to outside users, it ties the release documentation to the source. In the future, if we need to backport fixes and do releases on older branches, it's much more convenient to have the release documentation reflect the state that is tied to the repo.
This also tweaks make_release.py based on what we learned releasing 3.6.0-rc0.
- add requirements.txt for dependencies
- add --skip-distcheck option
- fail if running on Python 2
- fix some pylint errors
- refactor running shell script

Add release documentation

---

src/bsoncxx/array/view.hpp
src/bsoncxx/document/view.hpp
src/mongocxx/cursor.hpp

Directly specify std::iterator_traits fields in classes

CXX-1111 Remove std::iterator inheritance

---

.mci.yml

Adds tests back after upgrading the PowerPC variant to Ubuntu 18.04.
Code coverage reports a decrease in client_side_encryption.cpp. I'm not sure why. Code coverage is only uploaded in Travis AFAIK, and Travis was never running CSFLE tests (since AWS credentials are not passed through).

CXX-2048 add back tests

---

.evergreen/spec.patch

This fixes the failure of {{spec.patch}} to apply as a result of downstream RPM spec.  Note that the task continues to fail because of an unrelated transient issue in the mock environment provisioning.
Evergreen patch build: https://spruce.mongodb.com/version/5f3aeafe7742ae2a6ba05436/tasks

CXX-2093 fix rpm-package-build task

---

src/mongocxx/events/topology_description.hpp

Using statement wasn't needed.

CXX-1726 Remove unnecessary using statement

---

src/mongocxx/options/auto_encryption.hpp
src/mongocxx/options/client_encryption.hpp

Fixes error "implicit instantiation of undefined template 'std::string'"
requested in mongocxx/options/auto_encryption.hpp:256:29:
stdx::optional<ns_pair> _key_vault_namespace;
and likewise in client_encryption.hpp.

Fix build with libcxx

---

.mci.yml
CMakeLists.txt
cmake/BsoncxxUtil.cmake
cmake/MongocxxUtil.cmake
examples/add_subdirectory/.gitignore
examples/add_subdirectory/CMakeLists.txt
examples/add_subdirectory/hello_mongocxx.cpp
src/bsoncxx/CMakeLists.txt
src/bsoncxx/test/CMakeLists.txt
src/mongocxx/CMakeLists.txt
src/mongocxx/test/CMakeLists.txt

Full patch build: https://spruce.mongodb.com/version/5f2ddb44a4cf47286d24b5d0/tasks
Note that the failures are not related to the changes in this PR.  Also, the new task of interest is called {{build_example_with_add_subdirectory}}.

CXX-1173 support integration via CMake add_subdirectory()

---

etc/releasing.md

To prevent future mishaps like the 3.6.0 documentation being updated on gh-pages, but the markdown changes not being pushed to master.

Add push instruction to release docs

---

src/bsoncxx/document/value.cpp
src/bsoncxx/document/value.hpp
src/bsoncxx/test/bson_get_values.cpp

[The ticket](https://jira.mongodb.org/browse/CXX-1842) asked to let values be implicitly converted to views, but it seems to already be able to do that. This PR focuses on the second half, which is to let values use view's methods.

CXX-1842 Make values have a superset of the view API

---

src/bsoncxx/exception/error_code.cpp
src/bsoncxx/exception/error_code.hpp
src/bsoncxx/test/bson_value.cpp
src/bsoncxx/types.hpp
src/bsoncxx/types/bson_value/value.cpp
src/bsoncxx/types/bson_value/value.hpp
src/bsoncxx/types/private/convert.hh

All of the tests are done and works. I'm still trying to figure out how to combine the constructors in `value.cpp` and `value.hpp`. As far as generic programming goes, a variadic template could work like:
```
value(const type id); // base case
template<typename T, typename ... Args>
value(const type id, T t, Args ...args);
```
But it'd need to be defined in the `value.hpp`. IIUC that would create a new function for every different combination of arguments used. Which would cause a lot of overhead (memory and compilation) since it'd be a fairly large function. 
There's also the open issue of how to handle errors. As of now I just throw an error but I'm also working on that too.

CXX-2067 Expose bson_value::value type constructors

---

docs/content/mongocxx-v3/tutorial.md

The stream builder and the basic builder are defined in separate headers. We should see the stream builder convenience methods in bsoncxx/builder/stream/helpers.hpp. To use the stream builder in our code, include the following header files.

Header file addition for stream

---

.clang-tidy
.mci.yml
etc/run-clang-tidy.sh

Moving the `check` options out of the script and into a file makes it easier to run clang-tidy locally. The next step would be actually fixing some of these bugs.
To run locally:
```
FIND="find src -type f \( -name \*.hh -o -name \*.hpp -o -name \*.cpp \) -not -path \"*third_party*\""
eval $FIND | xargs clang-tidy -p build
```

move clang-tidy check opts to file

---

.evergreen/debian_package_build.sh
.mci.yml
debian/README.Debian
debian/build_snapshot.sh
debian/changelog
debian/control
debian/patches/0002_skip_mnmlstc_extra_step.patch
debian/patches/series
debian/rules

Evergreen patch build: https://spruce.mongodb.com/version/5fa5a13b9ccd4e7a05535ca8/tasks
Note that after this PR is approved and merged I will cherry-pick the change onto the `releases/v3.6` branch.

(Debian packaging) CXX-1747 allow building Debian packages with MNMLSTC

---

src/mongocxx/client.cpp
src/mongocxx/client.hpp
src/mongocxx/test/client.cpp
src/third_party/catch/include/helpers.hpp

As it turns out, the `list_databases` overload that accepted a `bsoncxx::document::view_or_value` "filter" was really applying it as an options document. So we already support the `authorizedDatabases` option, and all options that can be passed to the `listDatabases` command.
This PR renames the argument and adds a test to ensure we can pass `authorizedDatabases` through.

CXX-1985 Rename filter to opts for list_databases

---

docs/content/contributing/_index.md

@kevinAlbs Per our conversation yesterday, this is an attempt to provide clear guidelines for contributing to our codebase. The server's guidelines are well defined, pretty close to how we already code, and default to the Google C++ style guide. I also linked the C++ Core Guidelines. Those guidelines should be a given but I linked them to avoid ambiguity.

Add coding style to contribution guidelines

---

README.md

As noted in this [community post](https://developer.mongodb.com/community/forums/t/compiling-mongo-cxx-driver-r3-6-1/12271/2?u=kevin_albertson), the README does not directly link to the installation documentation.

Add installation link to README

---

debian/changelog
debian/control
debian/libbsoncxx-noabi.lintian-overrides
debian/watch

I ran into an issue where `make_release.py` could not find the tarball it just created. Specifying that the tarball is in the build folder fixed the issue. This is already committed on the `releases/v3.6` branch.

Fix path to tarball

---

.mci.yml

`python -m virtualenv venv` stopped working because `virtualenv` is no longer installed on Ubuntu 18.04 hosts. I think this is related to MONGOCRYPT-297.
This changes to use the version of python available in the MongoDB toolchain on hosts that have it (which should be hosts aside from Windows).

Fix python on Ubuntu 18.04 hosts

---

src/mongocxx/test/client_side_encryption.cpp

This is not urgent. It is a small fix to CSFLE tests which prevent some flaky failures when run against replica sets.

CXX-2171 use wc/rc majority in CSFLE prose tests

---

src/mongocxx/test_util/client_helpers.cpp

I realized we were making _a lot_ (hundreds) of **isMaster** and **serverStatus** calls to the server per spec test. Profiler results for transaction tests (see images below) show that currently, 16.70% of the time is spent in the function `should_skip_spec_tests`. That function makes multiple roundtrips to the server. After this change, only 2.26% of the time is spent in `should_skip_spec_tests`—a pretty big improvement. 
I also timed `test_transactions_spec` locally before and after caching server results. Here's the results:
```
Before optimization
n=10 | min    | Q1     | med    | mean   | Q3     | max    | std
wall | 28.30  | 28.44  | 28.63  | 28.70  | 28.88  | 29.60  | 0.3865
user | 0.6500 | 0.6550 | 0.6750 | 0.6770 | 0.6975 | 0.7100 | 0.0226
sys  | 0.110  | 0.120  | 0.140  | 0.138 …
```

cache test network calls

---

data/unified-format/test_files.txt
data/unified-format/valid-pass/poc-change-streams.json
data/unified-format/valid-pass/poc-command-monitoring.json
data/unified-format/valid-pass/poc-crud.json
data/unified-format/valid-pass/poc-gridfs.json
data/unified-format/valid-pass/poc-retryable-reads.json
data/unified-format/valid-pass/poc-retryable-writes.json
data/unified-format/valid-pass/poc-sessions.json
data/unified-format/valid-pass/poc-transactions-convenient-api.json
data/unified-format/valid-pass/poc-transactions-mongos-pin-auto.json
data/unified-format/valid-pass/poc-transactions.json
src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/spec/unified_test_format.cpp
src/mongocxx/test_util/client_helpers.cpp
src/mongocxx/test_util/client_helpers.hh

Most of the changes are test syncs. This PR syncs the test in "valid-pass" and adds the logic for the "runOnRequirements" and "schemaVersion" parts of the test runner. I created a new branch for the unified test format.

CXX-1871 add runOnRequirements and schemaVersion

---

src/mongocxx/test/spec/entity.cpp
src/mongocxx/test/spec/entity.hh
src/mongocxx/test/spec/unified_test_format.cpp

This PR adds the logic for creating the rest of the entities. The only entities left are change streams which should should be done with operations. 
Note: the entity map keeps clients and other entities separate since the client must outlive all entities created from it. I left a comment above the member variables in "entity.hh" with more details.

CXX-1871 create entities (db,coll,session,bucket)

---

src/mongocxx/test/spec/entity.cpp
src/mongocxx/test/spec/entity.hh
src/mongocxx/test/spec/monitoring.cpp
src/mongocxx/test/spec/unified_test_format.cpp

This PR adds support for the `intialData` top-level field of the unified test format ([here](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#top-level-fields)).  
The only part left is actually running and verifying the operations.

CXX-1871 load initial data

---

.mci.yml
docs/content/mongocxx-v3/working-with-bson.md
examples/bsoncxx/builder_list.cpp
src/bsoncxx/CMakeLists.txt
src/bsoncxx/builder/core.hpp
src/bsoncxx/builder/list/array.hpp
src/bsoncxx/builder/list/document.hpp
src/bsoncxx/test/bson_builder.cpp

This ticket addresses the follow-up work outlined in:
- CXX-2130 Add append method for list builder
- CXX-2131 Add extract_document and extract_array methods for list builder
- CXX-2132 Remove builder::list in favor of builder::document and builder::array
More specifically,
CXX-2130: This provides a way to append additional elements to a BSON document or array created by the list builder. For example
```
/// This BSON array -> { "0" : "foo", "1" : [ "bar", "baz" ], "2" : "qui" } can be created over multiple lines.
builder::array arr = {"foo"};
arr += {"bar", "baz"};
arr += "qux";
```
See the `operator+=` in the document and array classes.
CXX-2131: This allows a `bsoncxx::document::value` and `bsoncxx::array::value` to be extracted from `builder::document` and `builder::array`, …

CXX-2130, CXX-2131, CXX-2132 BSON list builder follow-up

---

.github/workflows/compile-and-test-latest.yml

As of now, the failing "compile-and-test-latest" workflow shows no useful output when tests fail. This changes the build type in the GitHub action from our default (release) to debug. This should fix that problem.

build type debug for workflow

---

docs/content/mongocxx-v3/installation/windows.md

[CXX-1248](https://jira.mongodb.org/browse/CXX-1248)
Documents that Windows users should use `-DENABLE_EXTRA_ALIGNMENT` when configuring the C driver during installation.

CXX-1248 Document disabling extra alignment on windows

---

src/mongocxx/collection.cpp
src/mongocxx/private/index_view.hh

[CXX-1646](https://jira.mongodb.org/browse/CXX-1646)
We want to include a server reply in all thrown exceptions where possible. After a small audit, I've found only one potential instance of an unreturned raw server response after an error, and even this one is arguably unimportant.
I've looked through all calls of `throw_exception` and all creations of `operation_exception` and its implementers: `authentication_exception`, `bulk_write_exception`, `query_exception`, and `write_exception`. I'm fairly certain all exceptions created have no relevant server response to include (many wrap libmongoc functions that do not return the raw server reply) or already include a raw server response (`steal()`ing the BSON error document).

CXX-1646 Include server replies in all exceptions

---

.mci.yml
src/bsoncxx/test/json.cpp

CXX-2234
Adds spaces to two extended JSON tests that expect an output with "base64".
This should right a failure caused by the bug fix [CDRIVER-3958](https://jira.mongodb.org/browse/CDRIVER-3958). There are no other occurrences of `"base64":` in the CXX driver repo outside of spec test JSON.

CXX-2234 Expect spaces after base64 in extJSON binary

---

src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/spec/unified_tests/operations.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp
src/mongocxx/test_util/client_helpers.cpp
src/mongocxx/test_util/client_helpers.hh

CXX-2230
Bumps supported UTF schema version to 1.1.0. Allows `serverParameters` in `runOnRequirement`. Drafts test runner changes for defining `serverApi` on a `client` entity (can't actually implement this until CXX-2138). Adds a dozen missing functions to supported UTF operations.
Tested new features above against new versioned API spec tests. `serverParameters` seem to skip correctly and new operations appear to run without error.

CXX-2230 Upgrade unified test runner to version 1.1

---

etc/releasing.md

Adds a note to remind releaser to check Evergreen before proceeding with the release.

add note to release instructions to check evergreen

---

src/mongocxx/test/database.cpp

CXX-2237
Removes unneeded assertion for session count in listLocalSessions test causing intermittent failures.

CXX-2237 Remove session count assertion listLocalSessions test

---

.mci.yml

CXX-2255
Upgrades Ubuntu 16.04 tasks to Ubuntu 18.04 tasks in Evergreen.

CXX-2255 Upgrade to Ubuntu 18.04 for Evergreen tasks

---

.mci.yml
src/mongocxx/test/change_streams.cpp
src/mongocxx/test/client.cpp
src/mongocxx/test/client_session.cpp
src/mongocxx/test/client_side_encryption.cpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/database.cpp
src/mongocxx/test/gridfs/bucket.cpp
src/mongocxx/test/index_view.cpp
src/mongocxx/test/sdam-monitoring.cpp
src/mongocxx/test/spec/change_stream.cpp
src/mongocxx/test/spec/client_side_encryption.cpp
src/mongocxx/test/spec/command_monitoring.cpp
src/mongocxx/test/spec/gridfs.cpp
src/mongocxx/test/spec/mongohouse.cpp
src/mongocxx/test/spec/retryable-reads.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp
src/mongocxx/test/spec/util.cpp
src/mongocxx/test/transactions.cpp
src/mongocxx/test_util/client_helpers.cpp
src/mongocxx/test_util/client_helpers.hh

CXX-2254
Adds two new tasks `test_versioned_api` and `test_versioned_api_accept_version_two`. Adds a new test utility `test_util::add_test_server_api` to append server API options when `MONGODB_API_VERSION` environment variable is set. Uses `add_test_server_api` to add API version to connecting clients in tests where necessary.

CXX-2254 Add testing for versioned API

---

.mci.yml
data/command-monitoring/find.json
data/unified-format/valid-pass/poc-command-monitoring.json
data/unified-format/valid-pass/poc-transactions.json

Some of the recent changes in the C driver cause many tasks in the C++ driver build to fail (until CXX-2286 is done).  This change restores the failing tasks on the waterfall to a working state so that other work can continue.
Full patch build: https://spruce.mongodb.com/version/60e49b5ae3c33126420ccab1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CXX-2286 sync command-monitoring and unified-format tests

---

data/unified-format/test_files.txt
data/unified-format/valid-pass/redacted-commands.json
src/mongocxx/test/spec/monitoring.cpp
src/mongocxx/test/spec/monitoring.hh
src/mongocxx/test/spec/unified_tests/assert.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp

No functional changes, but checks that we see filtered events that bubble-up from the C driver. Also cleans up the unified-test-spec runner with some more thorough checking and error messages.

CXX-2290: Validate command filtering in event monitoring

---

.mci.yml
src/mongocxx/test/collection.cpp

Patch build (CXX-2328, only skip tests that call `getLastError`): https://spruce.mongodb.com/version/60ff4de90ae60664f190172b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Patch build (CXX-2328, `getLastError` test skip, and CXX-2269, test 5.0 servers): https://spruce.mongodb.com/version/60ff5b2732f41765b6270f4a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CXX-2328, CXX-2269

---

.evergreen/build_snapshot_rpm.sh
.mci.yml

Patch build: https://spruce.mongodb.com/version/6103241dc9ec440971d9d8f8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CXX-2282 use arm64 hosts for rpm-package-build

---

src/mongocxx/collection.hpp
src/mongocxx/exception/error_code.cpp
src/mongocxx/exception/error_code.hpp
src/mongocxx/options/private/server_api.hh
src/mongocxx/options/server_api.cpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/uri.cpp
src/mongocxx/uri.cpp

The documentation says that we should throw mongocxx::logic_error, but std::logic_error is thrown instead.
Note: at this time mongocxx::logic_error does not have support for error messages (the C++ standard does) 
Note: it's unclear to me why we don't throw mongocxx::invalid_argument instead (the C++ standard has this)
See: https://jira.mongodb.org/browse/CXX-2329
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>

CXX-2329 Change type of thrown exception to match documentation

---

docs/content/contributing/testing-mongocxx.md

Several tests require use of the [`configureFailPoint` command](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#configuring-fail-points) to trigger server-side errors. The command must be enabled via configuration file or command line option when starting `mongod`.
The `configureFailPoint` command is not yet documented; see [DOCS-10784](https://jira.mongodb.org/browse/DOCS-10784).
---
This PR is motivated by my experience following written instructions to run the test suite locally. After following instructions, several tests were failing due to the error: `no such command: 'configureFailPoint'`.
Diagnosing this issue was difficult due to the `configureFailPoint` command having little to no documentation. It is however mentioned in …

Add instructions to enable fail points for test suite

---

.mci.yml

Evergreen patch build: https://spruce.mongodb.com/version/612e93b82a60ed4552e92972/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CXX-2277 ignore deprecated declarations when building on release branches

---

docs/content/mongocxx-v3/client-side-encryption.md

https://github.com/mongodb/mongo-cxx-driver/blob/915586cb5a87524b1f1dc3944b38becd53391013/docs/content/mongocxx-v3/client-side-encryption.md#L86-L87
has git merge markers in the file (i.e. <<<<<< HEAD). These should be removed to improve readability of the documentation.

CXX-2364 Remove git merge markers from docs/content/mongocxx-v3/client-side-encryption.md

---

src/mongocxx/test/collection.cpp

Patch build: https://evergreen.mongodb.com/version/61316b580305b906ebc402e5?redirect_spruce_users=true
This change is already on the `master` branch.  Making it also on `releases/v3.6` would allow us to clean up the Evergreen waterfall, leaving only the known macOS Boost  failure as the only remaining failure.

CXX-2328 skip tests that call getLastError

---

etc/make_release.py

This script throws the error "No Github token found in file 'github_token.txt'" if the file contains a token with underscores and/or capital letters. This commit fixes that issue.

allow underscore and capitals in Github token

---

.mci.yml

Evergreen patch build: https://spruce.mongodb.com/version/614145d53627e0056293ee65/tasks
This is essentially the same change as mongodb/mongo-c-driver#867

CXX-2332 use Python from toolchain on Ubuntu 14.04 Evergreen hosts

---

.evergreen/build_snapshot_rpm.sh

Evergreen patch build: https://spruce.mongodb.com/version/6144ed892fbabe32c064de75/tasks
The failure on the base commit is what prompted me to implement this change.

dump mock logs if RPM build fails in Evergreen

---

src/bsoncxx/private/helpers.hh
src/bsoncxx/types/bson_value/view.cpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/database.cpp
src/mongocxx/test/uri.cpp
src/mongocxx/uri.cpp

Result of `python2 ./etc/clang_format.py format`.

CXX-2370 fix lint

---

src/bsoncxx/builder/stream/value_context.hpp

The static assert also fails for the latest intel compiler release (2021.4) with:
```
/root/mongo-cxx-driver-r3.6.2/src/bsoncxx/builder/stream/value_context.hpp(120): error: function "bsoncxx::v_noabi::builder::stream::key_context<base>::operator<<(const char (&)[n]) [with base=bsoncxx::v_noabi::builder::stream::closed_context, n=4UL]" returns incomplete type "bsoncxx::v_noabi::builder::stream::value_context<bsoncxx::v_noabi::builder::stream::key_context<bsoncxx::v_noabi::builder::stream::closed_context>>"
std::is_same<value_context, decltype(std::declval<value_context>() << 1 << "str")>::value,
^
detected during instantiation of class "bsoncxx::v_noabi::builder::stream::value_context<base> [with base=bsoncxx::v_noabi::builder::stream::key_context<bsoncxx::v_noabi::builder::stream::closed_ …
```

Disabled static_assert in value_context for intel compiler

---

data/crud/unified/aggregate-let.json
data/crud/unified/test_files.txt
src/mongocxx/options/aggregate.cpp
src/mongocxx/options/aggregate.hpp
src/mongocxx/test/spec/unified_tests/assert.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp

Full patch build: https://spruce.mongodb.com/version/62101824a4cf473735b8a229/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

CXX-2274 support 'let' option for aggregate command

---

src/mongocxx/test/collection.cpp

Ensure that the "details" field is included in errInfo on failure.
https://jira.mongodb.org/browse/CXX-2183
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>

CXX2183 - expose document validation failure details

---

src/bsoncxx/types.hpp

Other code that use the mongo-cxx-driver library might very well be compiled with -Wfloat-equal or even stricter compiler settings. Please include this minor fix to avoid such problems for people using the driver.
Used standard solution in types.hpp to compare double values, to avoid the warnings produced when compiling with -Wfloat-equal.

CXX-2458 Avoid warnings when compiling with -Wfloat-equal

---

src/mongocxx/test/versioned_api.cpp

The "Versioned API Example 5 " test is failing on latest servers in Evergreen.
This example assumes the count command is not in API version 1.
The count command was added to API version 1 in [SERVER-63850](https://jira.mongodb.org/browse/SERVER-63850).

CXX-2473 skip Versioned API Example 5 on 5.3+ servers

---

src/mongocxx/test_util/client_helpers.cpp

Consolidate output code for client-side encryption test check; make sure correct output is seen in all cases.
Behavior was correct but no output shown for case where no environment variables were set. Now cases where
tests are skipped or failed also show the correct output. Also cleans up the implementation a bit. 
(The test_utils change was introduced in "https://github.com/mongodb/mongo-cxx-driver/pull/848".)
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>

Fix test_util output for client-side encryption test check

---

src/third_party/catch/include/helpers.hpp

Our current Catch2 exception helper says that an exception "contains" a message, when it was actually 
/expected/ to contain that message. This fixes the output to not be misleading.
https://jira.mongodb.org/browse/CXX-2470
Signed-off-by: Jesse Williamson <jesse.williamson@mongodb.com>

improve output of Catch2 exception string matchers

---

data/client_side_encryption/types.json

Resync the error messages in the `types` CSFLE test to https://github.com/mongodb/specifications/commit/6a7158d51b4c41f2f4a9c1293c5e1dceb93ab5c2 to resolve test failures on mongocryptd 6.0.0-alpha. Do not pull in test changes to `expectations` made in [SPEC-1768](https://jira.mongodb.org/browse/SPEC-1768). Updating the test runner for the new which is still an open task for the C++ driver in CXX-2155
The `badQueries` test is not included in C++ driver tests due to CDRIVER-3387. Only the `types` test was resynced.

CXX-2488 resync types CSFLE test

---

.evergreen/install_c_driver.sh
.mci.yml
data/crud/unified/estimatedDocumentCount.json
data/mongohouse/estimatedDocumentCount.json
data/retryable-reads/estimatedDocumentCount-serverErrors.json
data/retryable-reads/estimatedDocumentCount.json
data/retryable-reads/test_files.txt
data/versioned-api/crud-api-version-1-strict.json
data/versioned-api/crud-api-version-1.json
src/mongocxx/collection.hpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp
src/mongocxx/test/spec/util.cpp

This PR resolves CXX-2464, which is unblocked by CDRIVER-4309.
In addition to updating the spec test files, the C++ unified test runner had to be updated to handle the `viewOn` and `pipeline` argument fields to `createCollection`, which were previously being ignored.
The unified test runner used the same comparison logic for server version strings and JSON schema version strings. However, server version string comparison _must not_ ignore patch numbers, whereas JSON schema version string comparison _must_ ignore patch numbers. This PR includes a drive-by fix to version string comparison in the test runner to correctly distinguish between the two cases.
As a drive-by improvement, the warning indicating an unsupported test file is being skipped was moved into the test section of the test …

CXX-2464 Use count instead of collStats for estimatedDocumentCount

---

.mci.yml

For reasons still unclear to me, Evergreen tasks related to [VS 2015 variants](https://spruce.mongodb.com/variant-history/cxx-driver/windows-2k8-release?selectedCommit=901) began [timing out](https://evergreen.mongodb.com/lobster/evergreen/task/cxx_driver_windows_2k8_release_compile_and_test_with_shared_libs_101c986e9d7d9357f82436e507b16a472397a33f_22_06_06_18_42_32/0/task#bookmarks=0%2C9759&l=1&shareLine=9714) after https://github.com/mongodb/mongo-cxx-driver/pull/863 was merged. I narrowed down the issue to a failure to kill the background mock KMS servers with `trap 'kill $(jobs -p)' EXIT HUP`.
This PR attempts to workaround/address this issue by using a similar pattern [as in the C driver](https://github.com/mongodb/mongo-c-driver/pull/879/files#diff-8fe3ebc712c8b34fee22f7bb419e8617725 …

Move mock KMS server creation into separate background task

---

.evergreen/install_c_driver.sh

Based on mongodb/mongo-c-driver@5b91ef0fadf4d0b536be69d47bb1bd7cfb056f63
I encountered the failure with the libmongocrypt part of the build when running a patch build for the `releases/v3.6` branch.
Evergreen patch build: https://spruce.mongodb.com/version/62c9b5b03e8e867ebc55419f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Inject mongoc source directory for building libmongocrypt

---

src/bsoncxx/array/view.hpp
src/mongocxx/read_preference.cpp
src/mongocxx/read_preference.hpp
src/mongocxx/test/read_preference.cpp

This PR resolves CXX-2415.
Despite [Read Preference Tags](https://www.mongodb.com/docs/manual/core/read-preference-tags/) being specified as an _array_ of tag sets (aka a tag set list), the C++ Driver does not provide an interface to directly set the tag set list as an array, requiring the user to manually convert a `bsoncxx` array into a document to use the [BSON document overload](https://github.com/eramongodb/mongo-cxx-driver/blob/2f4ca28d9962dab9974806633706e47eeac555a7/src/mongocxx/read_preference.hpp#L179) as a workaround. This PR adds an overload that accepts a `bsoncxx::array::view_or_value` to improve the user experience.
This PR also updates the documentation to be more accurate and consistent when referring to "tag set lists". It also updates tests to correctly set the tag set …

CXX-2415 Support setting tag set list with array

---

docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md
docs/content/mongocxx-v3/installation/windows.md
docs/themes/mongodb/layouts/partials/meta.html

- Add the meta tag to enable the `upgrade-insecure-requests` Content Security Policy.
- Fix incorrect version references.
The meta tag resolves mixed-content loading CSS and Javascript files when accessing https://mongocxx.org. https://mongocxx.org has already been updated.

CXX-2549 fix mixed-content errors over HTTPS

---

.mci.yml

Updates the Evergreen config file to use latest releases of libmongoc and libmongocrypt, resolving some TODO comments.
The libmongocrypt dependency is updated to 1.5.2 instead of 1.5.0 to include the bugfix for `RewrapManyDataKey`.

Update mongocrypt and mongoc dependencies to latest releases

---

.mci.yml

This PR is a followup to https://github.com/mongodb/mongo-cxx-driver/pull/883.
Despite being chronologically the more recent event, libmongoc release 1.22.0 does not contained the [required changes](https://github.com/mongodb/mongo-c-driver/commit/32be2647814af6fcb3d8a9ec430e17dc8b669462) needed for correct error handling in hint for unacknowledged writes tests introduced in https://github.com/mongodb/mongo-cxx-driver/pull/870.
This PR thus bumps `mongoc_version_default` to [2966c67d](https://github.com/mongodb/mongo-c-driver/commit/2966c67d69bc22c3f68fc4f2b2d2164b7cf5b665), which corresponds to the main branch equivalent of the final commit included in the 1.22.1 release. `mongoc_version_minimum` is bumped to `1.22.1` accordingly and to include the patch that enforces libmongocrypt …

Update libmongocrypt and libmongoc dependencies to required commits

---

src/mongocxx/test/change_streams.cpp

This PR does not necessarily resolve CXX-2337, but attempts to make more discernable the state and conditions when it does fail.

CXX-2337 Improve granularity of assertions for resumeToken prose test

---

src/bsoncxx/test_util/catch.hh

Improve readability of test suite output by supporting pretty-printing of `bsoncxx::document::value` objects.
As a drive-by fix, removed the redundant `StringMaker<stdx::optional<bsoncxx::document::view>>` specialization (handled by `StringMaker<stdx::optional<T>>`) that inadvertently leads to infinite self-recursion when invoked.

Add StringMaker specialization for bsoncxx::document::value

---

src/mongocxx/test/spec/unified_tests/runner.cpp

Evergreen tasks on zSeries RHEL 8.3 are failing due to what appears to be a flaky `-Wmaybe-uninitialized` warning being incorrectly triggered by a call to `to_json(bsoncxx::document::view)` in `add_to_map`. This PR resolves this issue by removing the redundant call to `to_json` and capturing the `params` variable directly, which happens to address the false-positive warning.
Initially, I suspected that the use of an uninitialized data member was being detected, but I could not identify such a data member. Trivial tweaks to `add_to_map` causing the presence or absence of the error suggested this is a false-positive warning.

Remove redundant to_json causing flaky warnings on zSeries RHEL 8.3

---

.evergreen/find_cmake.sh
.mci.yml
docs/content/mongocxx-v3/installation/_index.md

Evergreen patch build: https://spruce.mongodb.com/version/6307b35a5623437b34e1f3a2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The main thing to focus on in the patch build is the new build variants.

CXX-2530 add missing Debian 10, 11 and Ubuntu 20.04 build variants

---

.mci.yml

This PR resolves CXX-2492 and is a followup to https://github.com/mongodb/mongo-cxx-driver/pull/871.
Changes verified by [this patch](https://spruce.mongodb.com/version/6308fa943627e02c58eab150).

CXX-2492 Add zSeries RHEL 8.3 for Latest

---

src/bsoncxx/CMakeLists.txt
src/bsoncxx/test_util/catch.hh
src/bsoncxx/test_util/to_string.hh
src/mongocxx/test/spec/monitoring.cpp
src/mongocxx/test/spec/unified_tests/assert.cpp
src/mongocxx/test/spec/unified_tests/assert.hh

Further improve readability of test suite output by supporting pretty-printing of `bsoncxx::types::bson_value`'s `view`, `value`, and `view_or_value` objects.
Also extends printing support to `bsoncxx::document::view_or_value`.
As a drive-by fix, adds a missing `return` in the `StringMaker` specialization for `stdx::optional<T>`. Prior to this fix, all `stdx::optional<T>` were being printed as `{nullptr}` even if not-null due to the result of the call to `convert` being discarded rather than being returned.
The existing `to_string(bsoncxx::types::bson_value::view_or_value)` implementation in `src/mongocxx/test/spec/unified_tests/assert.cpp` was relocated into a new file `src/bsoncxx/test_util/to_string.hh` as an inline function for convenience and use by both the bsoncxx and mongocxx …

Add StringMaker specialization for bsoncxx::types::bson_value types

---

.mci.yml
data/client_side_encryption/awsTemporary.json
data/client_side_encryption/test_files.txt
src/mongocxx/test/spec/client_side_encryption.cpp

This PR address CXX-2172.
No changes were necessary to the C++ Driver interface to support AWS temp creds.
The CSE legacy unified test runner was updated to support the new `awsTemporary` and `awsTemporaryNoSessionToken` KMS providers used to test AWS temp creds by the new `awsTemporary.json` test file.
The Evergreen config file was updated to support the generation of AWS temp creds as the new `MONGOCXX_TEST_AWS_TEMP_*` environment variables using the same pattern as applied in https://github.com/mongodb/mongo-c-driver/pull/1109.
Changes were verified by [this patch](https://spruce.mongodb.com/version/63376bace3c3315b40d5dd12). Failures on PowerPC and zSeries RHEL variants appear to be due to unrelated issues with Python package dependencies and will be addressed separately.

CXX-2172 Support AWS temporary credentials

---

.mci.yml
etc/make_release.py
src/mongocxx/CMakeLists.txt

- Update the minimum libmongoc version check in cmake scripts.
The required libmongoc dependency was increased to 1.22.1 in https://github.com/mongodb/mongo-cxx-driver/pull/884.

CXX-2584 update min libmongoc version in cmake

---

docs/content/mongocxx-v3/tutorial.md

According to the ticket [here](https://jira.mongodb.org/browse/CXX-1817?jql=text%20~%20%22get_string%22), element method get_utf8 renamed into get_string, and merged in with version 3.7.0. But the documentation tutorial leads users to use get_string and it is somewhat time consuming to understand which one to use for earlier-version-users of 3.7. A simple comment may help readers about this.

Add a comment about renamed element method to docs

---

data/unified-format/valid-pass/observeSensitiveCommands.json
data/unified-format/valid-pass/redacted-commands.json

- Sync the tests updated in
https://github.com/mongodb/specifications/commit/735a667672c758617821e3c5dda99c551e007375

CXX-2614 sync tests impacted by removal of MONGODB-CR

---

src/mongocxx/test/database.cpp

Fixes a compiler error when building `test_driver`:
```
$ cmake --build cmake-build --target test_driver -- -j16
```
Results in:
```
[4/5] Building CXX object src/mongocxx/test/CMakeFiles/test_driver.dir/database.cpp.o
FAILED: src/mongocxx/test/CMakeFiles/test_driver.dir/database.cpp.o 
ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBSONCXX_TESTING -DMONGOCXX_TESTING -DMONGO_CXX_DRIVER_COMPILING -I/Users/kevin.albertson/code/mongo-cxx-driver-CXX2284/src/third_party/catch/include -I/include -I/Users/kevin.albertson/code/mongo-cxx-driver-CXX2284/src/mongocxx/.. -I/Users/kevin.albertson/code/mongo-cxx-driver-CXX2284/cmake-build/src/mongocxx/.. -I/Users/kevin.albertson/code/mongo-cxx-driver-CXX2284/src/bsoncxx/.. …
```

remove unused var in `Database integration tests`

---

src/mongocxx/config/CMakeLists.txt
src/mongocxx/config/private/config.hh.in
src/mongocxx/instance.cpp

- Prepend compiler ID, compiler version, and C++ standard to the [Handshake platform string](https://github.com/mongodb/specifications/blob/9319b1a8cb4e7909871e893e24919ecabc00495b/source/mongodb-handshake/handshake.rst#client-platform)
The [Handshake](https://github.com/mongodb/specifications/blob/9319b1a8cb4e7909871e893e24919ecabc00495b/source/mongodb-handshake/handshake.rst) is the first command performed upon establishing the connection to MongoDB.
The Handshake includes metadata in the `client` field, so a client can identify itself. The Handshake metadata appears in `mongod` logs.
Here is a formatted log from `mongod` from a C++ driver connection before this change:
```json
{
"t": {
"$date": "2022-12-21T12:02:28.088-05:00"
},
"s": "I",
"c": "NETWORK",
"id": 51800,
"ctx": "conn11", …
```

CXX-2284 Append platform data to handshake

---

data/client_side_encryption/fle2-Compact.json
data/client_side_encryption/test_files.txt

CXX-2503
Add FLE 2 test for compactStructuredEncryptionData
Drivers need to sync the new fle2-Compact test to this commit: https://github.com/mongodb/specifications/commit/09ee1ebc481f1502e3246971a9419e484d736207
There are no functional changes needed.

Add FLE 2 test for compactStructuredEncryptionData

---

.mci.yml
docs/content/mongocxx-v3/installation/windows.md
examples/projects/bsoncxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake-deprecated/static/CMakeLists.txt
examples/projects/bsoncxx/cmake/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake/static/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/static/CMakeLists.txt
examples/projects/mongocxx/cmake/shared/CMakeLists.txt
examples/projects/mongocxx/cmake/static/CMakeLists.txt
src/bsoncxx/stdx/make_unique.hpp

- Remove requirement for /Zc:__cplusplus
The current [documented install instructions](https://mongocxx.org/mongocxx-v3/installation/windows/#:~:text=For%20building%20with%20Visual%20Studio%202017) note:
> For building with Visual Studio 2017 (without a C++17 polyfill), it is necessary to configure with an additional option, /Zc:__cplusplus to opt into the correct definition of `__cplusplus` (problem described here):
> 
> ```
> 'C:\Program Files (x86)\CMake\bin\cmake.exe' .. \
>     -G "Visual Studio 15 2017 Win64"            \
>     -DCMAKE_CXX_STANDARD=17                     \
>     -DCMAKE_CXX_FLAGS="/Zc:__cplusplus"         \
>     -DCMAKE_PREFIX_PATH=C:\mongo-c-driver       \
>     -DCMAKE_INSTALL_PREFIX=C:\mongo-cxx-driver  \
> ```
Setting `CMAKE_CXX_FLAGS` appears to have the …

CXX-2629 Remove requirement to set `/Zc:__cplusplus` in MSVC flags

---

src/mongocxx/options/auto_encryption.hpp
src/mongocxx/options/encrypt.hpp

Queryable Encryption in Public Technical Preview
CXX-2523
Queryable Encryption is in Public Technical Preview.
Queryable Encryption should not be used in production and is subject to
backwards breaking changes.

Queryable Encryption in Public Technical Preview

---

src/mongocxx/gridfs/bucket.cpp
src/mongocxx/test/gridfs/bucket.cpp

Hello,
Here is a patch to fix the limit value computed to returned the correct number of chunks in a partial download.
Without this patch, a `download::read` on 2 chunks throws an execption because the `chunks` cursor was exhausted.
Cheers

CXX-2650 Fix limit value in open_download_stream

---

data/client_side_encryption/fle2-CreateCollection.json
data/client_side_encryption/fle2-EncryptedFields-vs-EncryptedFieldsMap.json

- Update fle2-CreateCollection and fle2-EncryptedFields-vs-EncryptedFieldsMap with updated state collection names
See https://github.com/mongodb/specifications/pull/1382. These tests are expected to fail against latest server builds until this update is applied.

CXX-2658 update fle2 tests

---

data/client_side_encryption/fle2-CreateCollection.json
data/client_side_encryption/fle2-EncryptedFields-vs-EncryptedFieldsMap.json
examples/mongocxx/change_streams.cpp
src/mongocxx/change_stream.hpp

- Revise change stream example to show iterating indefinitely.
- Parameterize URI, db, and collection name in change stream example.
- Revise comments in `change_stream.hpp`.
Similar to cursors, change streams are iterated by sending the `getMore` command to the server. The server reply may contain zero, one, or multiple documents in a batch. Here is an [example response](https://gist.github.com/kevinAlbs/ccaf7b2af36189d5f82dbab14cdff41c) from a `getMore` on a change stream.
CXX-2659 proposes a simpler iteration API. This PR is intended to improve the documentation for the existing API.
The change_streams example can be built with `cmake --build cmake-build --target change_streams`. Events can be produced with a separate script:
```python
from pymongo import MongoClient
import time
cl = …
```

CXX-2441 revise docs and example of change streams

---

src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/change_streams.cpp

- Iterate exactly one document in change stream examples.
- Make notifications for change stream examples on a separate thread.
DRIVERS-436 requests examples to use on https://www.mongodb.com/docs/manual/changeStreams/.
The `Changestream Example` code examples in the C++ driver does not match the requested examples in DRIVERS-436.
The examples requested in DRIVERS-436 request iterating one document:
```java
// Start Changestream Example 1
MongoCursor<Document> cursor = inventory.watch().iterator();
Document next = cursor.next();
// End Changestream Example 1
```
The C++ driver example may print 0, 1, or many documents:
```c++
change_stream stream = inventory.watch();
for (auto& event : stream) {
std::cout << bsoncxx::to_json(event) << std::endl;
}
```
This has been changed to iterate …

CXX-2580 fix change stream examples

---

docs/content/mongocxx-v3/tutorial.md
examples/mongocxx/CMakeLists.txt
examples/mongocxx/inserted_id.cpp
examples/mongocxx/tutorial.cpp

- Add `tutorial.cpp` with code snippets from `tutorial.md`.
- Satisfy requests from CXX-2582
- e1f0d6e80337889000161bac6568a76414725dad add an example of getting inserted IDs.
- c33534f4f905bb63999c4434c0175f0e61f67b9f renames `coll` to `collection`.
- 9d28594e64768167405590ef856f744e08ab33fc distinguishes result variables to make examples easier to copy-paste.
- Make several changes to `tutorial.cpp`. Notably:
- 69f1e757ed67654d094a461de45a5dfa357ad1c0 fixes a compile error.
- 40113e6c455775864fc44813d8866a554f1cc04b simplifies the examples to use only three documents.
- 60da85a9d31a30fabead3d28e308f7e1f11cf6e8 replaces prints with assertions.
- Apply updates from `tutorial.cpp` to `tutorial.md`.
Adding `tutorial.cpp` with assertions is intended to make it easier to verify correctness of …

CXX-2582 revise tutorial

---

docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md
docs/content/mongocxx-v3/installation/windows.md
etc/apidocmenu.md
etc/generate-all-apidocs.pl

Completes the last step of [Generate and Publish Documentation](https://github.com/mongodb/mongo-cxx-driver/blob/6af37f81dfc64d1bcd33b993515a7c50e83654bb/etc/releasing.md#generate-and-publish-documentation)
> Merge the commit containing these changes into the master branch. This may require pushing the commit to a fork of the C++ Driver repository and creating a pull request.

Update documentation for r3.7.1 release

---

docs/content/mongocxx-v3/configuration.md
docs/content/mongocxx-v3/installation/advanced.md
docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md

This PR changes the main installation instructions to use standard directories. Installing to non-standard directories, as well as common fixes to failures to load libraries, have been moved to the "Advanced Configuration and Installation Options" instructions.
Documentation can be locally built with `cmake --build cmake-build --target hugo`.
The error described in CXX-2579 is due to the runtime loader being unable to find the C++ driver libraries.
IMO installing to non-standard directories is not a common enough use case to add to the main installation instructions.
The C driver [Unix install instructions](https://mongoc.org/libmongoc/current/installing.html#preparing-a-build-from-a-git-repository-clone) do not set `CMAKE_INSTALL_PREFIX`.
A section named `Installing to non-standard …

CXX-2579 use standard directories in main install instructions

---

.evergreen/install_c_driver.sh
.mci.yml

This PR unblocks CXX-2517 and other CXX Driver work that depend on libmongocrypt 1.7.0. Verified by [this patch](https://spruce.mongodb.com/version/642d80740305b96c2d9a1f10).
The minimum C Driver version was bumped to the current latest commit (https://github.com/mongodb/mongo-c-driver/commit/9ef1cc99517a6fb89cc59d34ac6c5999d044b8e1) in anticipation of upcoming CXX-2517 work. The minimum C Driver version should eventually be updated to be 1.24.0 once it is released (documented as a TODO comment).
The `add_expansions_to_env` parameter is used to simplify the `install_c_driver` EVG function by removing redundant (re)definitions of EVG expansions as environment variables. The EVG function can now invoke the script directly without additional setup required.
The `install_c_driver.sh` script …

CXX-2517 Use C Driver scripts to install libmongoc and libmongocrypt

---

src/mongocxx/options/aggregate.cpp
src/mongocxx/test/collection_mocked.cpp
src/mongocxx/test/options/aggregate.cpp

This PR resolves CXX-2670; see ticket for details. Verified by [this patch](https://spruce.mongodb.com/version/6434475561837d53df609a1d).
Updated tests in src/mongocxx/test/collection_mocked.cpp and src/mongocxx/test/options/aggregate.cpp to ensure all options currently supported by `options::aggregate` are properly tested. Options that were not being properly tested include:
- collation
- comment
- hint
- let
- readConcern
- readPreference
- writeConcern
Only `readConcern` was missing in `mongocxx::options::aggregate::append`.
Other `options` types may require an audit to confirm all their corresponding options are being propertly tested in `collection_mocked.cpp`.

CXX-2670 ensure readConcern is included in aggregate options document

---

examples/mongocxx/mongodb.com/documentation_examples.cpp

CXX-2671
Fix was introduced in: https://github.com/mongodb/mongo-cxx-driver/pull/952

re-enable testing on DB version 7+

---

.mci.yml
src/mongocxx/options/auto_encryption.hpp
src/mongocxx/test/client_side_encryption.cpp

CXX-2433
CXX-2596
CXX-2608
* Test mongocryptd is not spawned when shared library is loaded
* Drivers MUST run all tests with mongocryptd on at least one platform
for all tested server versions (4.2+).
* Drivers MUST run all tests with crypt_shared_ on at least one platform
for all tested server versions (4.2+). For server versions < 6.0,
drivers MUST test with the latest major release of crypt_shared_
(currently 6.0). Using the latest major release of crypt_shared_ is
supported with older server versions.

FLE 1.0 Shared Library

---

data/client_side_encryption/legacy/bypassedCommand.json
examples/mongocxx/mongodb.com/runcommand_examples.cpp
src/mongocxx/test/client.cpp

- Remove use of `collStats` and `currentOp`
See DRIVERS-2232:
> collStats and currentOp will produce a deprecation message in 6.0 and are candidates for removal in another major release.
The `runCommand Example 2` example, which used `collStats`, was removed. This example was added for the documentation team in DRIVERS-448. DOCSP-21320 requests removing `runCommand Example 2` from documentation.

CXX-2637 Remove use of `collStats` and `currentOp`

---

etc/releasing.md

Add a step to update homebrew packages.

Update release process to include homebrew

---

.mci.yml
etc/make_release.py

Both CXX-2344 and CXX-2394 are resolved by https://github.com/mongodb/mongo-c-driver/pull/1256. This PR bumps the minimum libmongoc version to the corresponding commit (https://github.com/mongodb/mongo-c-driver/commit/f14370ea8130a645080dc6f78342f53b25ddb339) to document this dependency and resolution.

CXX-2344 CXX-2394 Bump minimum libmongoc version to f14370ea

---

.mci.yml
etc/make_release.py
src/mongocxx/test/client_side_encryption.cpp

- update C driver test dependency to https://github.com/mongodb/mongo-c-driver/commit/98995b5d9e31768ae02be265e3debe43ec35cff8
- add prose test specified in DRIVERS-2441
See https://github.com/mongodb/mongo-c-driver/pull/1259 for the corresponding C driver changes.

CXX-2599 add prose test and upgrade C test dependency

---

src/mongocxx/options/auto_encryption.hpp
src/mongocxx/options/encrypt.hpp

- Remove "Public Technical Preview" from QE Equality API
Changes are requested in the "Downstream Changes Summary" of DRIVERS-2614

CXX-2689 Remove "Public Technical Preview" from QE Equality API

---

.mci.yml

This fixes the following evergreen build failures that were happening when building the example programs.
```
[2023/06/13 17:45:14.598] Cloning into 'mongo-c-driver'...
[2023/06/13 17:45:14.598] CMake Error at mongo-c-driver/CMakeLists.txt:1 (cmake_minimum_required):
[2023/06/13 17:45:14.598]   CMake 3.15 or higher is required.  You are running version 3.11.0
[2023/06/13 17:45:14.598] -- Configuring incomplete, errors occurred!
```

Use the latest CMake when building examples

---

.evergreen/build_snapshot_rpm.sh
.mci.yml

Evergreen patch build: https://spruce.mongodb.com/version/648b66d91e2d17b9b2a8bac2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
This addresses the problem with Fedora 36 being too old to use with mock. However, because the C++ driver is currently dependent on C driver functions which won't land in a release until 1.24.0, the task is still broken. However, after C driver 1.24.0 gets picked up by Fedora, the task should turn green all on its own.

Fix rpm-package-build

---

.mci.yml
examples/projects/bsoncxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/bsoncxx/cmake-deprecated/static/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/shared/CMakeLists.txt
examples/projects/mongocxx/cmake-deprecated/static/CMakeLists.txt
src/mongocxx/test/spec/unified_tests/runner.cpp

As a first step for CXX-2661, adds macos-1100 equivalent tasks for existing macos-1014 tasks. Removal of old macos-1014 tasks would fully resolve CXX-2661.
Additionally, tasks on ubuntu1404 were moved to ubuntu2204 per distro guidelines, resolving CXX-2657 and ongoing failures in the waterfall.
The Apple Clang compiler on the macos-1100 distro appears to have a new warning enabled, `-Wrange-loop-analysis`, which are also addressed by this PR.
Verified by [this patch](https://spruce.mongodb.com/version/6483715a5623430694937114).
Example projects were updated to replace Windows-only special handling of the conditional Boost dependency, and instead generically detect the use of the Boost polyfill library via the `CMakeCXXSymbolExists` module to detect the presence of the …

CXX-2661 Add macos-1100 tasks and move ubuntu1404 -> ubuntu2204

---

README.md
docs/content/_index.md
docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md
docs/content/mongocxx-v3/installation/windows.md
etc/apidocmenu.md
etc/generate-all-apidocs.pl

- Applies documentation changes for r3.8.0 onto the master branch. 
These changes were already applied to the r3.8.0 documentation. Applying to the master branch is noted in the [Generate and Publish Documentation](https://github.com/mongodb/mongo-cxx-driver/blob/2e645d047108e4e30265eb53d00dcd28f903bc42/etc/releasing.md#generate-and-publish-documentation) release step:
> Checkout the master branch. Push the commit containing changes to etc/ and docs/. This may require pushing the commit to a fork of the C++ Driver repository and creating a pull request.

Update r3.8.0 release documentation

---

etc/make_release.py
etc/releasing.md
etc/requirements.txt

- fdbc24ff3 pin to `jira` commit and use `SIGNATURE_RSA`
- 014f7c58c clarify DOCSP ticket is generated
- c4a9fdac9 replace "major" with "minor"
Pinning to `jira` commit was motivated by an observed error attempting the release:
```
% python ./etc/make_release.py --jira-creds-file ~/.secrets/jira_creds.txt --github-token-file ~/.secrets/github_token.txt --dry-run r3.8.0
[...]
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://jira.mongodb.org/rest/api/2/serverInfo
text: oauth_problem=signature_method_rejected
response headers = {'Date': 'Wed, 21 Jun 2023 14:07:11 GMT', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '39', 'Connection': 'keep-alive', 'WWW-Authenticate': 'OAuth realm="https%3A%2F%2Fjira.mongodb.org", …
```

Update release documentation

---

src/bsoncxx/array/element.cpp
src/bsoncxx/array/element.hpp
src/bsoncxx/array/view.cpp
src/bsoncxx/document/element.cpp
src/bsoncxx/document/element.hpp
src/bsoncxx/document/view.cpp
src/bsoncxx/test/bson_types.cpp

This pull request will include the name of the nonexistent key in the exception message thrown when the value is attempted to get fetched.
Prior to this PR, when the user would attempt to fetch the value of a nonexistent key, such as
```
auto some_message = doc["sceret"].get_string().value;
```
the error message would be as follows:
```
cannot get string from an uninitialized element: unset document::element"
```
This is unhelpful and quite frustrating for the user as it doesn't provide any information as to what key was uninitialized. If the user has a bunch of `get_string()` or `get_value()` calls across their process, it would be tedious to have to go through each one to figure out where exactly the program failed.
It's important to remember that the exception above is not thrown when …

CXX-2120 Handle nonexistent document fields

---

.mci.yml
examples/mongocxx/mongodb.com/documentation_examples.cpp
src/mongocxx/test/client_side_encryption.cpp

Resolves CXX-2501 and CXX-2685. Verified by [this patch](https://spruce.mongodb.com/version/64b6bea90305b95a1482729c/tasks).
Only changes required was patching documentation example code that was still using 6.0+ as the Queryable Encryption check ([should be 7.0+](https://github.com/mongodb/specifications/blob/c09f979ad296400552a98c9b784197ec648c2096/source/client-side-encryption/client-side-encryption.rst#create-collection-helper), see also CXX-2642). Drive-by cleanup of some noisy warnings due to `std::cerr` instead of `WARN()` in test code.

CXX-2685 Add 6.0 and 7.0 to EVG server version matrix

---

CMakeLists.txt
docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md

CXX-2703
Allow user to opt in to the default CMake install path by setting `-DUSE_DEFAULT_INSTALL_PATH=ON`

Opt in to the default CMake install path

---

.mci.yml
data/index-management/createSearchIndex.json
data/index-management/createSearchIndexes.json
data/index-management/dropSearchIndex.json
data/index-management/listSearchIndexes.json
data/index-management/updateSearchIndex.json
src/mongocxx/private/search_index_view.hh
src/mongocxx/search_index_view.cpp
src/mongocxx/search_index_view.hpp
src/mongocxx/test/CMakeLists.txt
src/mongocxx/test/search_index_view.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp

This PR will add 5 prose tests that will test search index management against a live Atlas cluster, modify the existing Evergreen config to automatically run these tests in the CI pipeline, and make small changes to the existing spec tests to sync with the [drivers ticket](https://github.com/mongodb/specifications/pull/1442).
[This](https://github.com/mongodb/specifications/pull/1442) ticket (mainly the changes made in the README) gives the vast majority of context needed to understand what prose tests should be added, why they should be added, and how to run them in Evergreen.
Being that running the prose tests could take around 20 minutes in total, there was not a lot of emphasis placed on making them easy to run locally. However, if you do wish to run them locally, here are the steps …

CXX-2700 Add search index management e2e testing against Atlas

---

CMakeLists.txt
docs/content/mongocxx-v3/installation/windows.md

- do not override `CMAKE_BUILD_TYPE` for multi-config generator
- remove `CMAKE_BUILD_TYPE` from Windows install instructions
- specify `--config` in Windows install instructions
Configuring on Windows with Visual Studio results in this log output from CMake:
```
-- No build type selected, default is Release
```
The log message is printed when overriding `CMAKE_BUILD_TYPE`. Overriding `CMAKE_BUILD_TYPE` is [ignored for multi-configuration generators](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#build-configurations):
> For multi-configuration generators like Visual Studio, Xcode, and Ninja Multi-Config, the configuration is chosen by the user at build time and CMAKE_BUILD_TYPE is ignored.
This may mislead users to think the build is Release, when it may be Debug. …

CXX-2726 do not override CMAKE_BUILD_TYPE for multi-config generator

---

src/mongocxx/client_encryption.hpp
src/mongocxx/client_session.hpp
src/mongocxx/options/data_key.hpp

This fixes the lint task that was failing in Evergreen.

fix linter errors

---

CHANGELOG.md
etc/make_release.py
etc/releasing.md
etc/test_make_release.py

This PR proposes adding a changelog to track notable changes in releases.
Changes were tested by locally tagging a commit with `r3.9.0` and temporarily tweaking the script to produce a draft. Here is a sample draft of the produced release notes:
https://github.com/mongodb/mongo-cxx-driver/releases/tag/untagged-fd8ab6ba4086415ac8fa
Having a CHANGELOG may reduce work during releases:
- The [release notes for 3.8.0](https://github.com/mongodb/mongo-cxx-driver/releases/tag/r3.8.0) included written notes not generated by `make_release.py`. Notes can be written incrementally with the changes.
- Tickets requiring release notes can be resolved before a release. Example: CXX-2662.
Listing individual Jira tickets is intentionally removed. IMO a copied list of tickets does not provide much value …

Add CHANGELOG.md

---

.gitignore
CHANGELOG.md
CMakeLists.txt
docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md
etc/test_make_release.py

[Refer to this comment](https://github.com/mongodb/mongo-cxx-driver/pull/994#discussion_r1302269847) for an explainer

Fix configuring a second time with USE_DEFAULT_INSTALL_PATH=TRUE

---

src/bsoncxx/document/value.hpp
src/mongocxx/options/private/transaction.hh
src/third_party/catch/include/catch.hpp

This PR is an alternate solution to the one proposed in #972

CXX-2740 ensure GCC pragmas are not manipulated when compiling with clang

---

etc/calc_release_version.py
etc/calc_release_version_selftest.sh

This PR brings over the changes from the C driver for calc_release_version.py. No CMake code is updated in this PR.

Updates to calc_release_version.py

---

docs/content/mongocxx-v3/configuration.md

Before this PR is merged, mongodb/mongo-c-driver#1392 should be merged and the location of [the page](https://mongoc.org/libmongoc/current/data-compression.html) linked in this PR should be confirmed.

CXX-2736 document data compression

---

CMakeLists.txt

Addresses CXX-2751. Verified by [this patch](https://spruce.mongodb.com/version/6500c1582a60ede1f0422073/).
Ensures `build/VERSION_CURRENT` is not unconditionally included in the distribution list when it may not actually exist (`BUILD_VERSION` set manually or `VERSION_CURRENT` found in the binary directory). This addresses missing rule issues with `dist` target dependency requirements for some CMake generators (i.e. Ninja).

CXX-2751 Fix reference to VERSION_CURRENT file in distribution list

---

.evergreen/install_c_driver.sh
.mci.yml

Followup to https://github.com/mongodb/mongo-c-driver/pull/1403 and https://github.com/mongodb/mongo-c-driver/pull/1404.
This _might_ address [flaky task failures](https://parsley.mongodb.com/evergreen/cxx_driver_auth__os~windows_2k8_mongodb_version~latest_compile_and_test_auth_with_shared_libs_60a3e7c4bf04079116c37a7eb9de5d30f67c02cb_23_09_13_19_02_31/0/task?bookmarks=0,366&shareLine=289) observed in the CXX Driver EVG waterfall due to the following error (cached CMake binary no longer binary/script-compatible with Git?):
```
0 [main] sh (1044) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xFB6410/0xE56410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search …
```

Temporarily use CMake version 3.25.3 instead of find-cmake-latest

---

etc/make_release.py

Check that `LIBMONGOC_DOWNLOAD_VERSION` equals `LIBMONGOC_REQUIRED_VERSION` in `make_release.py`.
Check is intended to ensure `LIBMONGOC_DOWNLOAD_VERSION` matches `LIBMONGOC_REQUIRED_VERSION` before a release.
`LIBMONGOC_DOWNLOAD_VERSION` may differ during development if a non-tagged C driver is needed for testing. `LIBMONGOC_REQUIRED_VERSION` is expected to be a tag intended for `find_package`.
Locally setting `LIBMONGOC_DOWNLOAD_VERSION` to `1.24.1` results in this error:
```bash
% python ./etc/make_release.py HEAD        
Expected LIBMONGOC_DOWNLOAD_VERSION(1.24.1) to match LIBMONGOC_REQUIRED_VERSION(1.24.0)
```

ensure `LIBMONGOC_DOWNLOAD_VERSION` matches `LIBMONGOC_REQUIRED_VERSION`

---

.evergreen/install_c_driver.sh
.mci.yml

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1023. Confirmed in BUILD-17907 that this was not an error due to CMake binary caching. Revert to using `find-cmake-latest` for script simplicity.

Revert to using find-cmake-latest

---

benchmark/CMakeLists.txt

Minor update to `benchmark/CMakeLists.txt` to use CMake library targets rather than link library names so that it properly inherits target properties such as include directories. Motivated by upcoming changes related to CXX-1569.

Update benchmark/CMakeLists.txt to link with library targets

---

etc/releasing.md

Add the Docker Hub publishing instructions to release doc

---

etc/make_release.py

Link was accidentally renamed in the mass replacement of https://github.com/mongodb/mongo-cxx-driver/commit/effc286c962c93b14406ef41d314558e5cad7b5f.
Resolves an observed error when running the release script:
```
% python ./etc/make_release.py \
--dry-run \
--jira-creds-file ~/.secrets/jira_creds.txt \
--github-token-file ~/.secrets/github_token.txt \
r3.8.1 
```
Results in error:
```
File "/Users/kevin.albertson/.venv/lib/python3.11/site-packages/jira/resilientsession.py", line 71, in raise_on_error
raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 401 url: https://jira.mongodb.com/rest/api/2/serverInfo
```

use https://jira.mongodb.org, not https://jira.mongodb.com

---

.evergreen/debian_package_build.sh
debian/rules

Related to CXX-2749. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1019 and https://github.com/mongodb/mongo-cxx-driver/pull/1024. Verified by [this patch](https://spruce.mongodb.com/task/cxx_driver_packaging_debian_package_build_mnmlstc_patch_3d959fb6825f67969cb2e23c8d85a47f03d608fe_652413b39ccd4e8ae4c20411_23_10_09_14_52_36/logs?execution=0).
Applies changes made in prior PRs to install rules and include paths for mnmlstc/core to the Debian packaging rules (removal of custom header file installation/management, addition of mnmlstc directory to include directories). Additionally, default Debian packaging commands disable downloads via `FETCHCONTENT_FULLY_DISCONNECTED=ON`. Disabling this to allow downloads during package build is considered acceptable, as the mnmlstc …

CXX-2749 Fix debian-package-build-mnmlstc

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp

Address the following warning:
```
warning: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Wsign-conversion]
return Impl::make(std::true_type{}, std::forward<Args>(args)...);
~~~~                         ^~~~~~~~~~~~~~~~~~~~~~~~
note: in instantiation of function template specialization 'bsoncxx::stdx::make_unique<int[], int, bsoncxx::stdx::detail::make_unique_impl<int[]>, std::unique_ptr<int[]>>' requested here
auto ptr = bsoncxx::stdx::make_unique<int[]>(3);
^
1 warning generated.
```
given the following code:
```cpp
auto ptr = bsoncxx::stdx::make_unique<int[]>(3);
```
for conformance with specification that states there should be a separate _overload_ for the unbounded array case with an explicit single `std::size_t` parameter which integral …

CXX-2625 Address sign conversion warnings for literal argument to make_unique<T[]>()

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp

Minor followup to https://github.com/mongodb/mongo-cxx-driver/pull/1044 that fixes the `lint` task failure on EVG.

Fix formatting of make_unique.hpp

---

etc/releasing.md

CXX-2768
In order to better support ARM hosts, such as recent Apple computers that use ARM chips, we will provide both AMD64 and ARM64 images on Docker Hub.

document building and pushing a multiarch docker image to Dockerhub

---

.mci.yml

CXX-2766
In order to better support ARM hosts, such as recent Apple computers that use ARM chips, we will provide both AMD64 and ARM64 images on Docker Hub.
libmongocrypt does not currently build on Alpine on ARM64, so the Alpine build is being temporarily removed. The build is fixed with the following [PR](https://github.com/mongodb/libmongocrypt/pull/706) and the Alpine build should be re-enabled once a new libmongocrypt release is done that has that PR.

Arm64 docker build

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1044.
Addresses the following Doxygen warnings due to improper use of `@copydoc`:
```
warning: argument 'args' of command @param is not found in the argument list of bsoncxx::v_noabi::stdx::make_unique(std::size_t count)
warning: The following parameter of bsoncxx::v_noabi::stdx::make_unique(std::size_t count) is not documented:
parameter 'count'
warning: argument 'args' of command @param is not found in the argument list of bsoncxx::v_noabi::stdx::make_unique_for_overwrite(std::size_t count)
warning: The following parameter of bsoncxx::v_noabi::stdx::make_unique_for_overwrite(std::size_t count) is not documented:
parameter 'count'
```
Given these polyfills are intended to conform to their stdlib counterparts, this PR proposes …

Defer to C++ standard library specification for make_unique polyfills

---

CHANGELOG.md
CMakeLists.txt

Incorporates changes from https://docs.google.com/document/d/1qh2-7Q3Zrmdp-h88H2uOKAmkS0bxYLV7Fz_FmmVeswU/edit

Update changelog for 3.9.0

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/document/value.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/test_util/mock.hh

Overlooked during review of https://github.com/mongodb/mongo-cxx-driver/pull/1042. Applies consistent use of `#include <bsoncxx/stdx/type_traits.hpp>` pattern to directives for consistency with other bsoncxx public header include directives.

Use consistent pattern for type_traits header include directives

---

data/index-management/searchIndexIgnoresReadWriteConcern.json
data/index-management/test_files.txt
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/search_index_view.hh
src/mongocxx/test/search_index_view.cpp

Do not apply `readConcern` or `writeConcern` to search index commands
Tests verified with this patch: https://spruce.mongodb.com/version/654b89333e8e86f7a940c6e3
This is a follow-up to https://github.com/mongodb/mongo-cxx-driver/issues/986
Search index commands return an error if `readConcern` or `writeConcern` is included.
Prior to the fix, applying a non-default `readConcern` or `writeConcern` to the `mongocxx::collection`, `mongocxx::database`, or `mongocxx::client` resulted in the `readConcern` or `writeConcern` being included in the search index command.
Prior to the fix, the added test "create and list search indexes with non-default readConcern and writeConcern" fails when run against an Atlas cluster:
```
/Users/kevin.albertson/code/tasks/mongo-cxx-driver-CXX-2697/src/mongocxx/test …
```

CXX-2785 do not apply `readConcern` or `writeConcern` to search index commands

---

.mci.yml
CMakeLists.txt
docs/content/mongocxx-v3/installation/advanced.md
etc/make_release.py
etc/releasing.md
examples/projects/bsoncxx/pkg-config/static/build.sh
examples/projects/mongocxx/pkg-config/static/build.sh

This PR bumps the required C driver to 1.25.0 and includes additional changes intended before the 3.9.0 release:
- Fix documented version of the auto C driver download introduction (3.9.0, not 3.8.1).
- Remove extra step for updating versions in Dockerfile.
- Remove `check_docker_file_versions`.
- Remove reference to removed Evergreen variant.
- Add `-pthread` to pkg-config example projects to work around CDRIVER-4776
Updating `MONGOCXX_VERSION` in Dockerfile before tagging a release may result in error downloading the not-yet-released tarball. This PR assumes it is preferable to update versions in the Dockerfiles after tagging a release.

Bump required C driver to 1.25.0

---

etc/releasing.md

This PR includes tweaks to the releasing instructions applied to the 3.9.0 release:
- Add instructions for vcpkg and Conan.
- Use spruce link, not old Evergreen link.
- Update example announcement.

Update release process

---

src/mongocxx/test/database.cpp

SERVER-79306 clarified this is expected behavior. This PR updates the relevant comment accordingly to avoid misleading implications + to be consistency with the existing comment in [aggregation_examples.cpp](https://github.com/mongodb/mongo-cxx-driver/blob/8c81c21e66b0b52b90bf8bfa43457ecbb3ea903c/examples/mongocxx/mongodb.com/aggregation_examples.cpp#L155).
The equivalent [unified spec test](https://github.com/mongodb/specifications/blob/82da02ba96d5d3ec4f48f6d2d4f2d0ebb1dce241/source/unified-test-format/tests/valid-pass/poc-crud.yml#L174) likely does not encounter this issue due to reuse of the `client0` object used to create collections in `database0` during the `createEntities` stage, which adds entries to the logical session cache that are visible by the time the aggregate command is …

Update comment to more accurately reflect sharded cluster behavior

---

CHANGELOG.md

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1061 documenting the addition of forward headers.

CXX-2288 update CHANGELOG

---

extras/docker/README.md

The C driver dependency was bumped, therefore we must update the link to the Dockerfile after the dependency bump was merged

CXX-2795 Update link to Dockerfile

---

src/mongocxx/test/search_index_view.cpp

This is a follow-up to https://github.com/mongodb/mongo-cxx-driver/pull/1055 to use `majority` read concern instead of `local`.
The test expects that applying a read concern to the command results in an error from Atlas. It was discovered in the specification PR (https://github.com/mongodb/specifications/pull/1474#discussion_r1423258678) that `local` is accepted for the `aggregate` with `$listSearchIndexes`. To avoid a false positive test, the test now uses read concern `majority`. If the driver incorrectly applies the read concern, Atlas returns the error: `$listSearchIndexes cannot run with a readConcern other than 'local'. Current readConcern: majority`.

CXX-2785 use read concern majority in test

---

debian/control
docs/config.toml
docs/content/mongocxx-v3/configuration.md
docs/content/mongocxx-v3/tutorial.md
docs/content/mongocxx-v3/working-with-bson.md
docs/data/mongodb.toml
docs/themes/mongodb/theme.toml
examples/README.md
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/stream/array.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client_session.hpp

Fix broken links in Hugo documentation.
This PR includes additional drive-by improvements:
- replace `http://mongocxx.org` with `https://mongocxx.org`
- replace `mongodb.github.io` with `mongocxx.org`
https://github.com/mongodb/mongo-cxx-driver/pull/1039 replaced use of the inline namespace macros with `inline namespace v_noabi`. I expect this changed the Doxygen page links include the namespace:
Example:
- In 3.8.1: https://mongocxx.org/api/mongocxx-3.8.1/classbsoncxx_1_1oid.html
- In 3.9.0: https://mongocxx.org/api/mongocxx-3.9.0/classbsoncxx_1_1v__noabi_1_1oid.html
This PR is intended as a short-term solution to fix the broken links. Further investigation may be needed to restore links omitting the namespace.
https://github.com/mongodb/mongo-cxx-driver/pull/1026 changed the directory …

Fix broken links

---

.evergreen/compile.sh
.evergreen/install_c_driver.sh
.evergreen/test.sh
.mci.yml
docs/content/mongocxx-v3/installation/windows.md
examples/projects/bsoncxx/cmake/shared/build.sh
examples/projects/bsoncxx/cmake/static/build.sh
examples/projects/mongocxx/cmake/shared/build.sh
examples/projects/mongocxx/cmake/static/build.sh

Resolves CXX-2039. Verified by [this patch](https://spruce.mongodb.com/version/65a6d7943066150d92e11de2).
This PR primarily consists of three steps:
* Move existing VS 2017 tasks from `windows-64-vs2017` to `windows-vsCurrent`.
* Rename VS 2017 fields/properties to accomodate multiple VS versions.
* Extend VS 2017 tasks to VS 2019 (simple duplication).
This should also address the spurious "cygheap base mismatch detected" failures on Evergreen due to BUILD-17907, which were frequently observed on the `windows-64-vs2017` distro (VS 2015 tasks thankfully seem to be unaffected?).
As part of this effort, several drive-by improvements are made to the EVG config and scripts:
* Use `CMAKE_GENERATOR_PLATFORM` or `-A` to specify the [generator …

CXX-2039 Add VS2019 support and migrate VS2017 tasks to windows-vsCurrent distro

---

CHANGELOG.md

This PR adds a changelog entry documenting the changes made in CXX-2790 (inline namespace -> using-declarations). Although these changes are not expected to break source or binary compatibility, the refactor is significant enough that I believe the entry is worth including if only for informative purposes. If these changes _do_ happen to unexpectedly cause breaking changes in downstream users, the entry advises users to submit a bug report accordingly.

CXX-2790 Add changelog entry documenting inline namespace refactor

---

.evergreen/abi-compliance-check-setup.sh
.evergreen/abi-compliance-check-test.sh
.evergreen/abi-prohibited-symbols-test.sh
.evergreen/abi-stability-setup.sh
.evergreen/abidiff-setup.sh
.evergreen/abidiff-test.sh
.mci.yml

This PR resolves both CXX-641 and CXX-2746. Verified by [this patch](https://spruce.mongodb.com/version/65a98804e3c3315314baed3e).
This PR proposes adding three tasks to the CXX Driver EVG config:
- abi-compliance-check: uses [abi-compliance-checker](https://lvc.github.io/abi-compliance-checker/) to generate binary and source compatibility reports.
- abidiff: uses [abidiff](https://sourceware.org/libabigail/manual/abidiff.html) to generate detailed binary compatibility reports.
- abi-prohibited-symbols: uses [nm](https://sourceware.org/binutils/docs/binutils/nm.html) and `grep` to detect symbols that should not be present in the ABI.
These three tasks are run by two build variants: one testing the CXX Driver libraries configured to use a polyfill library (currently mnmlstc/core by …

Add ABI compatibility tasks to EVG config (CXX-641, CXX-2746)

---

.mci.yml
src/mongocxx/test/spec/util.cpp

Similar to https://github.com/mongodb/mongo-c-driver/pull/1517, this PR uses the mongohouse Docker image added in DRIVERS-2543 to fix `test_mongohouse` task.
Verified with this patch build: https://spruce.mongodb.com/version/65aeae81c9ec44ca5f410888
DRIVERS-2543 adds scripts to use the Docker image maintained by the Atlas Data Lake team. https://github.com/mongodb-labs/drivers-evergreen-tools/commit/95ad5f3708b2ecb8cfcbc9005743ea92e9f81027 removed `run-mongohouse-local.sh` from drivers-evergreen-tools.
A new `RUN_MONGOHOUSE_TESTS` environment variable is passed to the test runner to conditionally run the `serverStatus` command. mongohoused does not return an expected `version` field in the response to `serverStatus`:
```
AtlasDataFederation test> db.runCommand({serverStatus: 1})
{ ok: 1, …
```

CXX-2783 use Docker image to run `mongohouse`

---

.evergreen/abi-stability-setup.sh
.evergreen/compile.sh
.evergreen/install_c_driver.sh
.mci.yml

The CXX Driver equivalent of changes in https://github.com/mongodb/mongo-c-driver/pull/1522. Verified by [this patch](https://spruce.mongodb.com/version/65b1705357e85a2a383b69fd).
The only caveat is that the CXX Driver does not have its own ccache detect-and-use routine a la CCache.cmake in the C Driver, so each instance of setting the ccache environment variables is preceeded by a test for `ccache` being present.
For consistency, other instances of the ccache test have been changed to use the same `command -V` method, which prints the path to the ccache binary when present in an informative manner (e.g. `ccache is /usr/bin/ccache`) in lieu of the explicit message that was being used prior.

Allow ccache to reuse results across build directories

---

.evergreen/test.sh
.evergreen/upload-code-coverage.sh
.mci.yml

Partially addresses CXX-2818. See ticket for details. Verified by [this patch](https://spruce.mongodb.com/version/65c650ea2fbabec21a9ed4bd).
Drive-by investigation of xtrace handling led to [DEVPROD-4630](https://jira.mongodb.org/browse/DEVPROD-4630). Currently, no task other than `docker-image-build` seems to enable xtrace, but a small improvement to temporary xtrace disable routines were applied nevertheless.

CXX-2818 Minor improvements to EVG config (codecov, xtrace)

---

cmake/MongocxxUtil.cmake

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1081 (CXX-2803).
Overlooked the removal of `INTERFACE_BSONCXX_ABI_TAG_BUILD_TYPE` in https://github.com/mongodb/mongo-cxx-driver/pull/1081/commits/73e40df285a188e442d63fdd2fb383eb1025299c impacting the derivation of the build type in MongocxxUtil.cmake, e.g.:
```
mongocxx-v_noabi-build_type-NOTFOUNDhs-x64-v142-mdd
```
This PR fixes the ABI tag such that the build type for mongocxx is consistent with bsoncxx.

CXX-2803 Fix build type for mongocxx library's ABI tag

---

etc/releasing.md

Resolves CXX-2974. The EVG Project ID for the CXX Driver now follows the same scheme as other Drivers. Links and references must be updated accordingly.

CXX-2974 Update references to the "latest release" EVG project

---

CHANGELOG.md
README.md
docs/content/_index.md
docs/content/mongocxx-v3/installation/advanced.md
docs/content/mongocxx-v3/installation/linux.md
docs/content/mongocxx-v3/installation/macos.md
docs/content/mongocxx-v3/installation/windows.md
etc/apidocmenu.md
etc/generate-all-apidocs.pl

Cherry-picked commits from the releases/v3.10 branch onto `master`.

CXX-2784 Update documentation for 3.10.0

---

cmake/BsoncxxUtil.cmake

Resolves CXX-2977.
https://github.com/mongodb/mongo-cxx-driver/pull/1081 failed to account for the possibility of generator expressions in `MSVC_RUNTIME_LIBRARY` (either set directly or via `CMAKE_MSVC_RUNTIME_LIBRARY`). This caused the series of `if()`/`elseif()` when `MSVC_RUNTIME_LIBRARY` is not-empty to fallthrough all string-comparison cases and produce output names with a trailing `-` and no runtime library property, e.g. `mongocxx-v_noabi-dhs-x64-v143-.dll`.
This PR adds support for generator expressions by deferring the evaluation of the string comparison to the build generation step via the `$<STREQUAL:str1,str2>` generator expression.

CXX-2977 Support generator expressions in MSVC_RUNTIME_LIBRARY

---

CHANGELOG.md

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1103 and https://github.com/mongodb/mongo-cxx-driver/pull/1106 that adds corresponding changelog entries for 3.10.1.

Update CHANGELOG with CXX-2971 and CXX-2977

---

CHANGELOG.md
etc/make_release.py
etc/releasing.md

This PR is intended to specify consistent updates the `CHANGELOG.md` when releasing:
- Tag the commit updating `CHANGELOG.md`
- Add `[Unreleased]` sections for subsequent releases after a release.
As a drive-by improvement `make_release.py` is updated to ignore the "Release `<version>`" ticket when checking for open tickets.
This PR is associated with: ~~https://github.com/mongodb/mongo-cxx-driver/pull/1108~~ https://github.com/mongodb/mongo-cxx-driver/pull/1107 to add a CHANGELOG.md entry for the upcoming 3.10.1 release.
There are no instructions for updating CHANGELOG.md after a release. This resulted in a follow-up PR to update CHANGELOG.md with the 3.10.0 section: https://github.com/mongodb/mongo-cxx-driver/pull/1105

Include post-release updates to `CHANGELOG.md` in release process

---

docs/content/mongocxx-v3/installation/_index.md

Update documented required CMake to 3.15. 3.15 became the new minimum in C++ driver 3.9.0 as part of https://github.com/mongodb/mongo-cxx-driver/pull/1019.

document minimum CMake as 3.15

---

docs/content/mongocxx-v3/api-abi-versioning.md
docs/content/mongocxx-v3/policies/abi-versioning.md
docs/content/mongocxx-v3/policies/api-versioning.md

Resolves CXX-2967. This is a documentation-only PR.
Running `hugo server` in the `docs` directory to live-preview the changes in a web browser is recommended.
This PR aims to expand and clarify our API and ABI compatibility policies. This will serve as a reference for all stable ABI changes going forward. This should be established before we set the ABI version number to its first integer value and commit to ABI stability. The API compatibility policy is updated accordingly.
Notable points include:
* Explicit definitions of what constitutes the "public API" and "stable ABI" for which we are committed to communicating compatibility for with the API and ABI version numbers respectively (see quotes from SemVer and Drepper).
* Exclude most build system properties from the public API (e.g. …

CXX-2967 Document the Stable ABI Compatibility Policy

---

.mci.yml

The fix for the bug that broke the Alpine build has been merged, therefore we can now re-enable the build for Alpine Linux.

Re-enable the Alpine build

---

docs/config.toml
docs/content/_index.md

Fix broken redirect link on https://mongocxx.org and removes a no-longer-relevant sidebar link.

Fix broken link

---

.evergreen/debian_package_build.sh
.mci.yml

Patch build: https://spruce.mongodb.com/version/664cfcc7bfa1990007d60894/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Fix debian package build v3.10

---

etc/releasing.md
etc/requirements.txt

Related to CXX-3008. Additionally updates `etc/requirements.txt` with output of `pip freeze` to ensure dependencies are pinned, which should resolve some open Snyk issues.

CXX-3008 add instructions to examine Snyk reports during release

---

extras/docker/README.md

In order to conform to the SSDLC policy, add warning that we are no longer making updates to Docker images.

SSDLC Docker README update

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/basic/array.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/document/value.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/index_view.hh

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1142 which addresses a few more instances of Ro3/Ro5 violations which were missed in the prior PR.

CXX-3043 Address additional Ro3/Ro5 violations

---

CMakeLists.txt
docs/content/_index.md
docs/content/legacy-v1/configuration.md
etc/generate-uninstall.cmd
etc/generate-uninstall.sh
etc/ssdlc_compliance_report.md

Resolves CXX-3013, CXX-3024, and CXX-3039.
This PR adapts the [Markdown template](https://gist.github.com/rtimmons/8253d1dfcc5f233bdb2d9c73b8e5c129#file-minimal-md) for the SSDLC Compliance Report to be included with each release.
Contents are deliberately written in such a way to avoid requiring per-release modifications. Instead, the individually linked documents, release artifacts, and reports are expected to be updated per release (and throughout ongoing development) as described by the updated release instructions.
Note: we will likely want to adopt Papertrail (CXX-3011) to satisfy the Authorized Publication reporting requirements (CXX-3024). A link to an appropriate Papertrail webpage will then replace the currently-proposed link to the C/C++ Release Info spreadsheet.

Add etc/ssdlc_compliance_report.md (CXX-3013, CXX-3024, and CXX-3039)

---

etc/releasing.md

Adds additional steps following creation of a new release branch `releases/vX.Y` to ensure Silk and Snyk are aware of, and continue analyzing, the release branch.
Silk commands defer to scripts in the C Driver introduced by https://github.com/mongodb/mongo-c-driver/pull/1619 to minimize redundancy. The CXX Driver will ideally adopt and reuse the same scripts as those used by libmongocrypt and the C Driver.
Snyk commands use the changes proposed in https://github.com/mongodb/libmongocrypt/pull/820 as reference. Note: Snyk does not appear to be able to detect the mnmlstc/core library despite `--detection-depth`, so a [Snyk support ticket](https://support.snyk.io/hc/en-us/requests/new) may be necessary.
Additionally, a new "merge back into `master`" branch is added to release instructions to …

CXX-3008 Add post-release instructions for Silk, Snyk, and patch release tags

---

etc/releasing.md

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1148 and related to https://github.com/mongodb/mongo-c-driver/pull/1647. Improves release instructions and commands following attempts to create a Silk asset group and Snyk project for the current `releases/v3.10` branch.

CXX-3008 Improve Silk/Snyk post-release instructions with explicit commands

---

.evergreen/check-augmented-sbom.sh
etc/augmented.sbom.json

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1143. An unrelated error in the r3.10 project on EVG revealed failing jq commands were not correctly exiting the script.
Fixing the script revealed a significant change in the Augmented SBOM (empty vulnerabilities field).

CXX-3008 fix jq command and update SilkBomb before download

---

.evergreen/check-augmented-sbom.sh

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1154. Sorry, I fell for the multiple herestring trap again (which is not supported by Bash). 🤦
This PR falls back to the old tried-and-true output file method instead of using procsubs and herestrings. Verified (properly) by [this patch](https://spruce.mongodb.com/task/mongo_cxx_driver_silk_silk_check_augmented_sbom_patch_7ddaa1b1405fefa85305fef6f1fb45e35913d6d0_6679999cb23a430007957549_24_06_24_16_06_53/logs?execution=0).

CXX-3008 replace invalid multiple Bash herestrings with output files

---

etc/make_release.py

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1136. Discovered during dry-run of the release script.
```
/bin/sh: 1: ./.evergreen/garasign_dist_file.sh: not found
```

CXX-3010 Fix reference to garasign script in make_release.py

---

CONTRIBUTING.md

Moves contributing guidelines from [this docs page](https://www.mongodb.com/docs/languages/cpp/cpp-driver/current/contributing/) to CONTRIBUTING.md. 
VS Code applied many formatting changes automatically, which I don't think are breaking.

DOCSP-39788 - Add Contributing Guidelines

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/bulk_write.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/bulk_write.cpp
src/mongocxx/test/bulk_write.cpp

[CXX-2742](https://jira.mongodb.org/browse/CXX-2742)
Consider addition of empty() to mongocxx::bulk_write 
[evergreen](https://spruce.mongodb.com/version/6671b7c166038200070e2eef/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Added empty() to mongocxx::bulk_write and added a test for this call.

CXX-2742 Consider addition of empty() to mongocxx::bulk_write

---

examples/mongocxx/pool.cpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/pool.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
src/mongocxx/test/pool.cpp

Overload operator[] for obtaining the underlying database of a pool entry.

CXX-1843: Provide a cleaner API for working with pool entries

---

etc/releasing.md

This PR proposes updates to the release instructions after a thorough audit during the 3.10.2 release process.
Notable changes:
- List of required secrets and credentials is consolated and moved to the top of the file.
- More instructions are now accompanied by the corresponding commands to execute.
- More use of GitHub Alerts (tip, note, warning, etc.)
- Added instructions to update and upload SSDLC reports.
- Removed merge-back step from post-release instructions.
The merge-back of `releases/vX.Y` into `master` post-release introduced in https://github.com/mongodb/mongo-cxx-driver/pull/1148 was meant to ensure all release tags are accessible from `master` to facilitate use of `git describe --tags` and similar patterns. However, GitHub PR merge methods do not permit a "clean" means to …

Refine and update release instructions post 3.10.2 release

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/bulk_write.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/bulk_write.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/bulk_write.hh

Relocate field `_is_empty` to impl class.
The [abi-compliance-check](https://spruce.mongodb.com/task/mongo_cxx_driver_abi_stability_polyfill_abi_compliance_check_9223cfcf72bb3ced16c20275e460ba8d6b76a3e2_24_07_01_19_26_58/files?execution=0) task identified an ABI change from https://github.com/mongodb/mongo-cxx-driver/pull/1150 (under "Problems with Data Types" in the attached [HTML report](https://mciuploads.s3.amazonaws.com/mongo-cxx-driver/master/9223cfcf72bb3ced16c20275e460ba8d6b76a3e2/mongo_cxx_driver_9223cfcf72bb3ced16c20275e460ba8d6b76a3e2/mongo_cxx_driver_abi_stability_polyfill_9223cfcf72bb3ced16c20275e460ba8d6b76a3e2_24_07_01_19_26_58/0/abi-compliance-check/noabi/compat_report.html)). Adding `_is_empty` to `mongocxx::v_noabi::bulk_write` changed the size of the type.
Many C++ …

CXX-2742 relocate `is_empty` to impl class

---

CONTRIBUTING.md
etc/coding_guidelines.md

Resolves CXX-3061. Precursor changes to CXX-2745 concerning documentation of coding guidelines.
Docs changes will be required to make [this page](https://www.mongodb.com/docs/languages/cpp/cpp-driver/current/contributing/) consistent with the new CONTRIBUTING.md file contents.
A large portion of the contents of the `CONTRIBUTING.md` document is very old and describe coding guidelines moreso than contribution guidelines. Furthermore, the instructions are both too detailed in some respects and too vague in others. Given the expected volume of coding guideline updates to come in light of CXX-2745 (Stable ABI), this PR proposes a small tidy-up of this file.
Given our current PR-based contribution, development, and review workflow, this PR proposes keeping the (external) contribution …

CXX-3061 Move coding guidelines into a separate document

---

cmake/BsoncxxUtil.cmake
src/bsoncxx/test/CMakeLists.txt
src/bsoncxx/test/exception_guard.cpp
src/bsoncxx/test/exception_guard.hh
src/bsoncxx/test/string_view.test.cpp
src/bsoncxx/test/type_traits.test.cpp
src/mongocxx/test/client_helpers.cpp
src/mongocxx/test/client_helpers.hh
src/mongocxx/test/collection.cpp
src/mongocxx/test/sdam-monitoring.cpp
src/mongocxx/test/spec/command_monitoring.cpp
src/mongocxx/test/spec/monitoring.cpp
src/mongocxx/test/spec/unified_tests/assert.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp

Resolves CXX-3065. Verified by [this patch](https://spruce.mongodb.com/version/6699827a7979a60007a98203).
Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1015:
> Any user code that currently violates the nothrow requirement will now terminate via `noexcept` rather than be allowed to continue with potentially unbounded libmongoc runtime errors. [...] (consider: [our own test cases](https://github.com/mongodb/mongo-cxx-driver/blob/eae761bb770b7a25101a5fd8a44471471cc8e222/src/mongocxx/test/sdam-monitoring.cpp#L71) violate this requirement in failure conditions, as Catch2 uses exceptions to report test assertion failures))
This PR implements a workaround for such assertions in our test suite.
The "[sdam_monitoring]" test cases (two total) can be used to demonstrate the problem by …

CXX-3065 guard against use of REQUIRE within APM callbacks

---

src/bsoncxx/include/bsoncxx/fwd.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/compiler.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/util.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/fwd.hpp
src/mongocxx/include/mongocxx/fwd.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/fwd.hpp

Partially resolves CXX-3069. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1170.
Adds Doxygen documentation for directories, namespaces, and generated headers. Docs for files and root namespace redeclarations are deferred to a followup PR.
This PR proposes organizing Doxygen documentation at the _bottom_ of header files in the following order:
```cpp
// License notice.
#pragma once
#include <headers> // Include directives and etc.
namespace bsoncxx { ... } // Declarations and definitions.
///
/// @file
/// Documentation for this file.
///
///
/// @dir path/to/dir
/// Documentation for relevant subdirectories.
///
///
/// @namespace ns::qualifier
/// Documentation for relevant namespaces.
///
```
This is to avoid their interference with general development workflows, as …

CXX-3069 document directories, namespaces, and generated headers

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/json.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/type_traits.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client_session.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/client_encryption.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/data_key.hpp

Resolves CXX-3070.
Notable fixes include:
- Misplacement of type aliases between a function and its intended documentation.
- Incorrect `name` in `@param name`.
- Redundant commands without useful documentation.
Some of these warnings were addressed by changing the `@deprecated` to a `@warning`, such as when the command is referring to an entity other than what is currently being documented.
However, these warnings are for the most part ignored and left unaddressed. Applying `[[deprecated]]` or `*_DEPRECATED` (from the export header) to relevant entities produces too many `-Wdeprecated-declarations` warnings. This currently applies to:
- `bsoncxx::v_noabi::types::b_undefined` (type)
- `bsoncxx::v_noabi::types::b_dbpointer` (type)
- `bsoncxx::v_noabi::types::b_symbol` (type)
- …

CXX-3070 Address -Wdocumentation Clang warnings

---

examples/mongocxx/mongodb.com/documentation_examples.cpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/operators.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/document/element.cpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/exception/error_code.cpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/json.cpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/private/b64_ntop.hh
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/types/bson_value/private/value.hh
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.cpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.cpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/types/private/convert.hh
src/bsoncxx/test/bson_builder.cpp
src/mongocxx/lib/CMakeLists.txt
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/client.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/collection.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/database.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/data_key.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/encrypt.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/private/apm.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/private/server_api.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/client_encryption.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/scoped_bson_value.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/read_concern.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/uri.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/write_concern.cpp
src/mongocxx/test/change_streams.cpp
src/mongocxx/test/client_side_encryption.cpp
src/mongocxx/test/collection_mocked.cpp

Resolves CXX-3072. Verified by [this patch](https://spruce.mongodb.com/version/66a11d1ad1fabb000754f19c).
Similar to https://github.com/mongodb/mongo-c-driver/pull/1543 for the C Driver. Addresses 615 Clang warnings (83 unique warnings) with Clang 19.
A long overdue followup to https://github.com/mongodb/mongo-cxx-driver/pull/955:
> It may be worth eventually extracting this helper into a proper a proper component (probably under src/mongocxx/private?), but that work has been deferred for now.
This addresses `-Wunused-member-function` warnings in `options.cpp` due to unused functions with internal linkage (default ctor + `value_for_init`).
A large part of this PR is devoted to addressing `-Wold-style-cast` warnings.
Most cases only needed a trivial change from `(T)expr` to …

CXX-3072 Reduce Warnings - Code Consistency and Quality Improvements

---

README.md
etc/apidocmenu.md
etc/deploy-to-ghpages.pl
etc/patch-apidocs-index-pages.py
etc/releasing.md
etc/requirements.txt
examples/README.md
examples/mongocxx/tutorial.cpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client_session.hpp

Resolves CXX-3081. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1169 and https://github.com/mongodb/mongo-cxx-driver/pull/1174.
This PR adds a new script which is invoked during API doc deployment which patches the index pages of all prior API docs to match that of the latest API doc. This permits each API doc to have an up-to-date list of C++ Driver releases, links to resources, and possibly other information (such as announcements).
Regardless of Doxygen version and API doc version, the following patterns were observed:
- There is an `index.html` file at the top-level directory of each API doc directory corresponding to the "Main Page" for each API doc.
- The `index.html` file contains a `<div class="contents">...</div>` corresponding to main page contents.
- The title, …

CXX-3081 Keep API doc index pages up-to-date with each release

---

CHANGELOG.md
cmake/FetchMnmlstcCore.cmake
cmake/FetchMongoC.cmake

Resolves CXX-3087. Verified by [this patch](https://spruce.mongodb.com/version/66b25d01d973d20007c4d59d).
Addresses the following warning emitted by CMake 3.30 and newer for `mongo-c-driver` and `EP_mnmlstc_core`:
```
CMake Warning (dev) at /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
Calling FetchContent_Populate(mongo-c-driver) is deprecated, call
FetchContent_MakeAvailable(mongo-c-driver) instead.  Policy CMP0169 can be
set to OLD to allow FetchContent_Populate(mongo-c-driver) to be called
directly for now, but the ability to call it with declared details will be
removed completely in a future version.
Call Stack (most recent call first):
cmake/FetchMongoC.cmake:24 (FetchContent_Populate)
CMakeLists.txt:78 (include)
This warning is for project …
```

CXX-3087 Replace single-argument FetchContent_Populate with FetchContent_MakeAvailable

---

CHANGELOG.md
etc/releasing.md

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1160 which forgot to include CHANGELOG entries in the post-release changes PR due to release instructions only committing the patch entries to the release branch. Instructions are also updated accordingly.

Update CHANGELOG with 3.10.2 entries

---

docs/DoxygenLayout.xml
etc/generate-apidocs-from-tag.pl
src/bsoncxx/include/bsoncxx/doc.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/basic/helpers.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/fwd.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1185:
> Aside: Doxygen 1.12.0 was notably released.
The Doxygen changelog was updated with 1.12.0 release notes. I believe the upgrade to be worth implementing now. This PR also demonstrates the relatively few changes required for a less-significant Doxygen version upgrade compared to all the additional diffs to config and layout files in https://github.com/mongodb/mongo-cxx-driver/pull/1185.
The most notable change is the omission of classes in the Namespaces List page.
With 1.11.0:
With 1.12.0:
imo this is a very worthwhile improvement which makes the Namespaces List much easier to navigate. This also lessens the importance of CXX-3086 (although I would still like for it to be implemented if able).
The simpler Namespaces Page …

CXX-3085 Upgrade to Doxygen 1.12.0

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/document/element.cpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/client_encryption.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/exception/operation_exception.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/hint.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/encrypt.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/index_view.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/write_concern.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/change_stream.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/index_view.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/private/search_index_view.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/validation_criteria.cpp

Resolves CXX-3089. Supercedes https://github.com/mongodb/mongo-cxx-driver/pull/1192. Verified by [this patch](https://spruce.mongodb.com/version/66bf670db574900007456c24).
Requesting an additional review from @vorlac to validate these changes in their environment. (I am unable to add you to the list of reviewers.)
`<string_view>` is not specified to include `<string>`. The [STL changes](https://github.com/microsoft/STL/blame/b191409cec71aa837072a5d1ebafb041989c71dd/stl/inc/string_view#L14-L16) cited in https://github.com/mongodb/mongo-cxx-driver/pull/1192 exposed pre-existing Include What You Use (IWYU) violations in C++ Driver headers (use of `std::string` without including `<string>`).
This PR fixes all IWYU violations for `std::string` (only!) in library code (not tests, examples, …

CXX-3089 Ensure <string> is included in all components using std::string

---

etc/releasing.md

Remove Homebrew release step.
Homebrew steps were also removed from C driver in https://github.com/mongodb/mongo-c-driver/pull/1687.
Trying to manually update results in this message:
```bash
% brew bump-formula-pr mongo-cxx-driver --url https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.10.2/mongo-cxx-driver-r3.10.2.tar.gz
Error: Whoops, the mongo-cxx-driver formula has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt
```

remove homebrew release step

---

.evergreen/abi-stability-setup.sh
.evergreen/compile.sh
.evergreen/install_c_driver.sh
.evergreen/test.sh
.mci.yml

Verified by [this patch](https://spruce.mongodb.com/version/66ccc85588f0d50007b1526b).
Addresses task timeouts on VS 2015 distros since [2024-07-22](https://spruce.mongodb.com/version/mongo_cxx_driver_ae07bd2574ae7340f7a047f4dd99186c644a262b/tasks) due to what appears to be an incompatibility with the Python version/environment and its relation to the cryptography package as required by the KMS KMIP mock server:
```
Traceback (most recent call last):
File "kms_kmip_server.py", line 6, in <module>
from kmip.services.server import KmipServer
File "drivers-evergreen-tools\.evergreen\csfle\kmstlsvenv\lib\site-packages\kmip\services\server\__init__.py", line 16, in <module>
from kmip.services.server.server import KmipServer
File "drivers-evergreen-tools\.evergreen\csfle\kmstlsvenv\lib\site-pack …
```

Address task timeouts on VS 2015 distros due to KMS KMIP mock server

---

.evergreen/compile.sh
.mci.yml
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/json.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/json.cpp

Fix build with GCC 4.8.5.
Verified with this [patch build](https://spruce.mongodb.com/version/66c6161c488c38000703c3e4).
Supporting build with GCC 4.8.5 is motivated by a request to build on a customer RHEL 7.9 system. See [slack thread](https://mongodb.slack.com/archives/C0328AQA3/p1723037627729639).
This PR resolves errors observed when building with RHEL 7 with GCC 4.8.5.
```
/root/mongo-cxx-driver/src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp:571:45: error: redeclaration 'bsoncxx::v_noabi::stdx::basic_string_view<Char, Traits>::npos' differs in 'constexpr'
const std::size_t basic_string_view<C, Tr>::npos;
^
/root/mongo-cxx-driver/src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp:136:32: error: from previous declaration …
```

CXX-3088 fix build with GCC 4.8.5

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/exception/error_code.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
src/mongocxx/test/pool.cpp

(This pull request fix one minor bug)
Symptom: When the uri parameter 'waitQueueTimeoutMS' was enabled and set to a smaller value (e.g. 100), the function 'mongoc_client_pool' may return a NULL client.
Solution:  Add a check in the function 'pool::entry pool::acquire()', and throw an exception when correct client was not returned.

CXX-3100 Check return when acquiring client from pool

---

Doxyfile
etc/releasing.md

Related to CXX-3097.
In advance of the next upcoming release, enables the `SITEMAP_URL` so that the generated Doxygen API doc pages will include a `sitemap.xml` which may be referenced by the gh-pages sitemap via manual post-release modifications until a more thorough solution to CXX-3097 is implemented.

CXX-3097 Set SITEMAP_URL for upcoming releases

---

.clang-format
Doxyfile
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/logger.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/server_api.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/read_concern.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/validation_criteria.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/write_concern.hpp

Addresses CXX-3108. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1185.
Sets `WARN_IF_UNDOC_ENUM_VAL = YES` (deferred by https://github.com/mongodb/mongo-cxx-driver/pull/1185), which enables warnings for undocumented enumerators.
This revealed several enumerators in `mongocxx::v_noabi::error_code` which were incorrectly using `//` instead of `///`.
Additionally, the enumerators of the following enumerations were completely undocumented (descriptions may have been present in the enumeration's documentation, but this of course does not generate enumerator tables or enable Doxygen references):
- `mongocxx::v_noabi::log_level`
- `mongocxx::v_noabi::options::server_api::version`
- `mongocxx::v_noabi::read_concern::level`
- `mongocxx::v_noabi::write_concern::level`
- …

CXX-3108 Address missing enum member documentation Doxgyen warnings

---

src/bsoncxx/test/type_traits.test.cpp
src/mongocxx/test/client_helpers.cpp
src/mongocxx/test/client_helpers.hh
src/mongocxx/test/client_side_encryption.cpp
src/mongocxx/test/options/create_collection.cpp
src/mongocxx/test/spec/initial_dns_seedlist_discovery.cpp
src/mongocxx/test/spec/operation.cpp
src/mongocxx/test/spec/unified_tests/assert.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp
src/mongocxx/test/spec/uri_options.cpp

Addresses 40 Clang warnings (35 unique).
> [!NOTE]
> The value of `-Wswitch-enum` is denoting code which may need to be updated given changes to a set of enumerators. The value of `default:` in addition to explicit enumerators is to handle representable values which may not be covered by the set of enumerators. Therefore, having both in the same switch statement is an acceptable pattern, although the `default:` should ideally not be necessary.

Reduce Warnings - implicit-fallthrough, switch-enum, extra-semi-stmt, unneeded-member-function

---

data/crud/unified/aggregate-write-readPreference.json
data/crud/unified/db-aggregate-write-readPreference.json

This PR will sync two spec tests to match the changes made in https://github.com/mongodb/specifications/commit/30b3a75291794794152c377854df9fee1ccc6875.
See DRIVERS-2914. Server 8.0 requires aggregation tests with `$out` to not pre-create the output collection.

CXX-3035 Sync $out aggregation spec tests

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/string/to_string.hpp

A small followup to https://github.com/mongodb/mongo-cxx-driver/pull/1213 which adds a missing code block terminator to the documentation of `bsoncxx::v_noabi::string::to_string`.
Before:
After:

CXX-3110 Fix missing end of code block

---

CHANGELOG.md

For the 3.11.0 release.
Adds entries for JIRA tickets and PRs associated with this release. Modifies wording for existing entries for improved clarity. Reorders entries to prioritize more important and significant changes at the top of each section.

Update CHANGELOG for 3.11.0

---

CHANGELOG.md

Follow-up to https://github.com/mongodb/mongo-cxx-driver/pull/1217
I missed that C++ driver 3.11.0 drops support (not just deprecates) of MongoDB 3.6 due to raising the required C driver to 1.28.0. C driver 1.28.0 dropped 3.6 as part of CDRIVER-4815.

note 3.11.0 drops server 3.6

---

.mci.yml

Second attempt following https://github.com/mongodb/mongo-cxx-driver/pull/1223.
Attempt to resolve [scan-build matrix task failures](https://spruce.mongodb.com/version/mongo_cxx_driver_latest_release_e3665ae00d1293df85bd8f3185bb9d55410fd212/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Escan-build-matrix%24) in the EVG release branch project by ensuring a consistent upload path for the release branch (where `$project` is `mongo-cxx-driver-release` instead of `mongo-cxx-driver`).

Avoid using '$project' in Amazon S3 commands for release branch

---

src/mongocxx/test/spec/util.cpp

Followup to https://github.com/mongodb/mongo-cxx-driver/issues/1206. Missed an instance of `WARN()` being used for skipping.

Use SKIP() in mongocxx::spec::run_tests_in_suite

---

docs/api/bsoncxx/examples/bson_documents/create_array.md
docs/api/bsoncxx/examples/bson_documents/create_doc.md
examples/api/bsoncxx/examples/bson_documents/access_array/algorithms.cpp
examples/api/bsoncxx/examples/bson_documents/access_array/basic.cpp
examples/api/bsoncxx/examples/bson_documents/access_array/find.cpp
examples/api/bsoncxx/examples/bson_documents/access_array/iterators.cpp
examples/api/bsoncxx/examples/bson_documents/access_array/subscript.cpp
examples/api/bsoncxx/examples/bson_documents/create_array/builder_concatenate.cpp
examples/api/bsoncxx/examples/bson_documents/create_array/builder_raw_value.cpp
examples/api/bsoncxx/examples/bson_documents/create_array/builder_raw_view.cpp
examples/api/bsoncxx/examples/bson_documents/create_doc/builder_concatenate.cpp
examples/api/bsoncxx/examples/bson_documents/elements/arr_multi.cpp
examples/api/bsoncxx/examples/bson_documents/elements/arr_single.cpp
examples/api/bsoncxx/examples/bson_documents/values/arr_view.cpp
examples/api/bsoncxx/examples/bson_errors/access_arr_iter_end.cpp
examples/api/bsoncxx/examples/bson_errors/access_arr_key_missing.cpp
examples/api/bsoncxx/examples/bson_errors/query_element_arr_invalid_type.cpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1208. Prompted by CXX-2291.
Overlooked the addition of examples of using `concatenate()`, which are currently only used in error handling examples for sub-document/sub-array exception recovery. Updates documentation of `concatenate()` overloads to avoid implying their use is specific to the stream builders.
As a drive-by improvement, simplifies creation of arrays for examples by using `make_array(args...)` instead of going through `from_json(R"({"v": [args...]})")["v"].get_array().value`. ("When all you have is a hammer, ...")

CXX-3082 Add examples for bsoncxx::v_noabi::builder::concatenate

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/range.hpp

A small followup to https://github.com/mongodb/mongo-cxx-driver/commit/0f990cab33d9b9d4a2ddeb8038ba9221db4fcdc2 to address the following Doxygen warning:
```
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/range.hpp:36: warning: unable to resolve reference to 'trimFactor' for \ref command
```
Demotes mentions of encryptedFields members to inline monospace text rather than ambiguous or non-existent references to Doxygen entities. (Note: the valid references happen to link to the getter overload for each member function.)
Before:
After:

doxygen: address unresolved reference warnings in range.hpp

---

.mci.yml

Copy 7.0 server tasks to test 8.0. Verified with this [patch build](https://spruce.mongodb.com/version/670e809a5c60a20007e96a37).
Atlas search index task groups are scheduled on separate build variants to avoid duplicate tasks on one variant:
```
invalid patched config syntax: task 'test_search_index_helpers' in 'ubuntu2004-debug' is listed more than once, likely through a task group
```

CXX-3031 add 8.0 test tasks

---

examples/CMakeLists.txt

Follow-up to https://github.com/mongodb/mongo-cxx-driver/pull/1190 to remove an extra unused block in `examples/CMakeLists.txt`.

CXX-1201 remove extra cmake config

---

Doxyfile
docs/config.toml
docs/themes/mongodb/theme.toml
etc/deploy-to-ghpages.pl
etc/patch-apidocs-current-redirects.py
etc/releasing.md

Related to CXX-3097. See also https://github.com/mongodb/mongo-cxx-driver/pull/1239.
Adds a new patch script to the page deployment process which inserts redirect routines to API doc pages such that navigating to an `/api/current` page automatically redirects the user to the canonical `/api/mongocxx-<version>` page.
The new patch script behaves in a similar way to the `patch-apidocs-index-pages.py` script introduced in https://github.com/mongodb/mongo-cxx-driver/pull/1180. The `APIDOCSPATH=/path/to/api` environment variable is used to describe the location of the `/api` directory, under which `mongocxx-<version>` API doc directories are present. The latest API doc directory is identified by sorting the directory names by version.
Unlike `patch-apidocs-index-pages.py`, BeautifulSoup4 is …

CXX-3097 add patch-apidocs-current-redirects.py

---

.evergreen/compile.sh
.mci.yml
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp

Verified by [this patch](https://spruce.mongodb.com/version/6720f2c1b48a5c00078003e1).
https://github.com/mongodb/mongo-cxx-driver/pull/1194 added the RHEL 7.9 distro to test against GCC 4.8.5 and the bsoncxx polyfill impls via `BSONCXX_POLYFILL: impls`. However, the `"compile"` EVG function doesn't know about this env var, as it is only used by the scan-build tasks. Therefore, the task has actually been [compiling against mnmlstc/core instead](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_rhel79_compile_compile_without_tests_761aeb891d96dd7317258a72ed79873b5d2c7ac0_24_10_23_14_08_44/0/task?bookmarks=0,1779&shareLine=192).
This PR extends the `BSONCXX_POLYFILL` pattern to the `"compile"` EVG function and `compile.sh` script for consistency, replacing the `USE_POLYFILL_BOOST` env …

Fix polyfill selection for compile tasks + use large distros

---

examples/mongocxx/with_transaction.cpp

This is a very small change to the with_transaction example, as requested in https://jira.mongodb.org/browse/DRIVERS-2606. The read concern and read preference settings are removed as strictly unnecessary. The write concern is left in-place, with a comment explaining that it's redundant if you are using the suggested Atlas connection string.

CXX-2679 simplify options in with_transaction example

---

cmake/MacroGuardTest.cmake
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/list.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/gridfs/downloader.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/gridfs/uploader.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/data_key.hpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/range.hpp

Long-awaited followup to https://github.com/mongodb/mongo-cxx-driver/pull/1043. Verified by [this patch](https://spruce.mongodb.com/version/6725389950efee000716da7a). With these changes, all current public headers have proper one-to-one match of prelude and postlude header include directives.

CXX-2770 Add missing postlude header include directives

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp

Resolves CXX-2769. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1043 which postponed this change as a possible API breaking change for users who may be depending on this out-of-place macro guard.

CXX-2769 Remove out-of-place BSONCXX_ENUM macro guards

---

CHANGELOG.md
examples/bsoncxx/builder_list.cpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/list.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp
src/bsoncxx/test/bson_builder.cpp
src/mongocxx/include/mongocxx/v_noabi/mongocxx/events/topology_description.hpp

Resolves CXX-3155. Verified by [this patch](https://spruce.mongodb.com/version/6728f94aa8204a0007a8f82f). (Task failures appear to be unrelated.)

CXX-3155 Remove undocumented using-directives and using-declarations

---

CHANGELOG.md
CMakeLists.txt

Resolves CXX-3170. Verified by [this patch](https://spruce.mongodb.com/version/672d008e1a72ee000787bbbf).
Followup to https://github.com/mongodb/mongo-cxx-driver/pull/994 and https://github.com/mongodb/mongo-cxx-driver/pull/1012 which added a CMake option to opt out of legacy implicit install prefix override behavior. This PR removes the legacy behavior and this opt-out option in favor of full consistency with CMake's default behavior instead (explicit `CMAKE_PREFIX_PATH` for custom install prefix specification, default install paths otherwise).

CXX-3170 Remove MONGOCXX_OVERRIDE_DEFAULT_INSTALL_PREFIX

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/fwd.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1251 which forgot to remove Doxygen documentation of the `bsoncxx/util` directory.

CXX-3003 Remove documentation of bsoncxx/util directory

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp

A small fix to https://github.com/mongodb/mongo-cxx-driver/pull/1185 which made a copy-paste error in the return type documentation of the array overload of `concatenate()`.

doxygen: fix return type for array concatenate()

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.hpp

For consistency with declarations of for-internal-use-only interfaces in public headers. The `not_view` type trait appears to be unused + just a simple negation of the `is_bson_view_compatible` type trait, so it is removed.

Move stray bson_value::view type traits into detail namespace

---

.evergreen/config_generator/components/atlas_search_indexes.py
.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/integration.py
.evergreen/config_generator/components/mongohouse.py
.evergreen/config_generator/components/sanitizers.py
.evergreen/config_generator/components/uninstall_check.py
.evergreen/config_generator/components/valgrind.py
.evergreen/config_generator/components/versioned_api.py
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/build_snapshot_rpm.sh
.evergreen/scripts/compile-scan-build.sh
.evergreen/scripts/compile.sh
.evergreen/scripts/install-c-driver.sh
CHANGELOG.md
CMakeLists.txt

Resolves CXX-3179. Verified by [this patch](https://spruce.mongodb.com/version/673283e445a9270007fcea3c).
Changes the default value of `ENABLE_TESTS` from `ON` to `OFF`.
Tweaked descriptions of CMake options to better document how they are conditioned on `ENABLE_TESTS=ON` (e.g. `BUILD_TESTING=ON` alone does _not_ enable test targets). In particular, the difference between `BUILD_TESTING` (add test targets to "all") and `ENABLE_TESTS` (enable the test targets which may be added to "all") is clarified by the addition of a warning when `BUILD_TESTING=ON` + `ENABLE_TESTS=OFF` (which suggests a conflict of intent).
All instances of `ENABLE_TESTS=OFF` in Evergreen scripts (except in `spec.patch`) are removed in favor of using off-by-default behavior. All EVG tasks which require test targets or …

CXX-3179 Set ENABLE_TESTS=OFF by default

---

.evergreen/config_generator/components/abi_stability.py
.evergreen/config_generator/etc/utils.py
pyproject.toml
uv.lock

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1244. Enabled by https://github.com/evergreen-ci/shrub.py/pull/39 which added the missing field (+ extra) to the upstream class definition.

evg: remove workaround for missing teardown_task_can_fail_task field

---

CHANGELOG.md
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/change_stream.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/change_stream.cpp
src/mongocxx/test/spec/gridfs.cpp

Resolves CXX-3163. Verified by [this patch](https://spruce.mongodb.com/version/6733aa7e18af6a000732ca5b).
Following https://github.com/mongodb/mongo-cxx-driver/pull/1257, workarounds that were required for mnmlstc/core `optional<T>` compatibility are no longer required.
These former workarounds consist of improper initialization of underlying objects affecting the behavior of the type (fixed in https://github.com/mnmlstc/core/commit/776eb3e5340d4fa06e81e06252c3ca1a26163b5b but never released). The `mongocxx::v_noabi::options::change_stream` class's `_start_at_operation_time` data member (and related accessors) are most notably affected by this issue and the primary change in this PR. Related workarounds in test code are also replaced.

CXX-3163 Remove workarounds for core::optional<T>

---

.evergreen/config_generator/components/silk.py
.evergreen/generated_configs/tasks.yml
etc/augmented.sbom.json

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1257. Verified by [this patch](https://spruce.mongodb.com/version/67366c3ac323860007b53810).
https://github.com/mongodb/mongo-cxx-driver/pull/1257 updated the `purls.txt` and SBOM Lite files. There was a delay until the Augmented SBOM observed the updates to SBOM Lite file. The [silk-check-augmented-sbom](https://spruce.mongodb.com/task/mongo_cxx_driver_silk_silk_e6e2696826a5c64e87c76bf31673dcf16aefc83f_24_11_13_17_48_46/logs?execution=1) task failure indicated the Augmented SBOM was finally updated accordingly.
This PR also restores the name of the `silk-check-augmented-sbom` task (changed in https://github.com/mongodb/mongo-cxx-driver/pull/1244) for consistency with [release …

CXX-2797 Update Augmented SBOM with mnmlstc/core removal

---

CHANGELOG.md

Resolves CXX-3168. Updated the entry for the 3.11.0 release for consistency + references to the C Driver to clarify how the C++ Driver inherits MongoDB Server minimum version requirements through the C Driver minimum version requirement.

CXX-3168 Add deprecation entry for MongoDB Server 4.0

---

etc/releasing.md
etc/ssdlc_compliance_report.md

Updates SSDLC-related files and release instructions to better align with latest state of requirements.
Of note, completely transitions away from using the [SSDLC Report: mongo-cxx-driver](https://docs.google.com/spreadsheets/d/1sp0bLjj29xO9T8BwDIxUk5IPJ493QkBVCJKIgptxEPc/edit?usp=sharing) spreadsheet (primarily used to track static analysis issues) in favor of using the Coverity CSV export file for static analysis reports, which will be archived alongside other SSDLC compliance files in the [definitive SSDLC compliance files folder](https://drive.google.com/drive/folders/1_qwTwYyqPL7VjrZOiuyiDYi1y2NYiClS) rather than our project-specific folder. Triaging and handling of Coverity issues is, and will be, handled entirely within Coverity.
The SBOM Lite (`cyclonedx.sbom.json`) and Augmented …

Update SSDLC-related files and release instructions

---

.evergreen/config_generator/components/compile_only.py
.evergreen/generated_configs/tasks.yml

Excludes the rhel79 distro from the compile-only matrix to avoid the noisy git compatibility error when executing `calc_release_version.py` in patch builds (not on a branch -> use of an unsupported git flag due to git binary version).

Exclude rhel79 from compile-only matrix in patch builds

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/data_key.hpp

Document the KMIP "delegated" masterKey option. Fix rendering of documentation for `data_key::master_key`:
Before:
After:

CXX-2813 document KMIP "delegated" option

---

README.md

After further review, the change from branch to tag was determined to be unnecessary and potentially disruptive to existing users/scripts which expect `releases/stable` to be a branch rather than a tag.

CXX-3150 Revert "releases/stable" from tag to branch

---

.evergreen/check-augmented-sbom.sh

Addresses check-silk-augmented-sbom task failure on the new EVG project waterfall for v3.

Update the silk asset group being compared against to v3.11

---

etc/releasing.md

To avoid excessive e-mails when updating the `debian/unstable` branch, the GitHub Webhook is updated to limit posting to selected branches. As a consequence, this requires updating the settings on each minor release.
Quoting https://wiki.corp.mongodb.com/display/INTX/Githook:
> The default behavior of this webhook is to post commit to all branches in a repo to JIRA.  If you want to limit the commit activity to a specific repository or set of repositories, you must do the following:
> - https://githook.mongodb.com/?branches=master --> Master only
> - https://githook.mongodb.com/?branches=master..legacy..someotherbranch --> Master, Legacy and Someotherbranch.  The syntax is strange (.. not &)

add release instruction for webhook

---

.evergreen/spec.patch

This fixes the RPM build on the master branch. Some tweaks were needed following the 4.0.0 release.
Evergreen patch build: https://spruce.mongodb.com/version/674611f7ad999d000774f68e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

RPM packaging updates

---

.evergreen/scripts/check-augmented-sbom.sh
CHANGELOG.md

To trigger a commit build for the v4.0 EVG project + update Silk asset group to track the `releases/v4.0` branch.

Add 4.0.1 changelog section and update Silk asset group

---

etc/releasing.md

Update post-release instructions to submit a commit to the `releases/vX.Y` branch after updating the corresponding EVG project settings to trigger a commit build for the latest commit in the (new/updated) branch.

Update post-release instructions for non-patch releases

---

CHANGELOG.md

Excuse to trigger another EVG commit build with the project settings updated with the correct path to the relocated EVG configuration file.

Sync CHANGELOG with 021528e

---

.evergreen/config_generator/components/integration.py
.evergreen/config_generator/components/versioned_api.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/compile.sh
CHANGELOG.md

Similar to https://github.com/mongodb/mongo-c-driver/pull/1791, motivated by [DEVPROD-21](https://jira.mongodb.org/browse/DEVPROD-21). Verified by [this patch](https://spruce.mongodb.com/version/674f3b6232d276000785a7ce/).
MongoDB Server 5.0 tasks remain on `macos-14` (Intel) due to lack of availability on `macos-14-arm64`.
Also an attempt to avoid spurious Clang internal compiler errors as observed in [this patch](https://spruce.mongodb.com/task/mongo_cxx_driver_integration_matrix_integration_macos_1100_release_static_extra_alignment_latest_single_e55829024adbd437e48d8310bf959f644d67dc07_24_12_02_21_11_39/).
```
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 12.0.0 …
```

CXX-3194 Migrate from macos-1100 to macos-14-arm64

---

.evergreen/config_generator/components/integration.py
.evergreen/generated_configs/tasks.yml

Resolves CXX-3194. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1293. Verified by [this patch](https://spruce.mongodb.com/version/675230629678270007e78266/).
[DEVPROD-13222](https://jira.mongodb.org/browse/DEVPROD-13222) may have been a fluke or misdiagnosis, as reattempting the migration appears to succeed without notable changes to the implementation.

CXX-3194 Migrate from macos-1100 to macos-11-arm64

---

.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/integration.py
.evergreen/config_generator/etc/utils.py
pyproject.toml
uv.lock

Followup to https://github.com/evergreen-ci/shrub.py/commit/3038539b2e411c6f9f2fae5b3eacffe5aaa97045 (which adds `batchtime` to `EvgTaskRef`) and https://github.com/evergreen-ci/shrub.py/commit/089d270db048c1999dbdb53b60eb8146501b9a26 (which addresses Python 3.12 compatibility and the `UserWarning: Valid config keys have changed in V2` pydantic warning).

Bump shrub.py to 3.6.0 and remove batchtime workarounds

---

.evergreen/config_generator/components/compile_only.py
.evergreen/generated_configs/variants.yml

Address Evergreen finalization errors for patch builds (causing the "Evergreen error" on GitHub PRs) due to [DEVPROD-13331](https://jira.mongodb.org/browse/DEVPROD-13331), which appears to be caused by display tasks interacting poorly with `patchable: false`. Resolve the issue by removing the display task.

Remove display task for compile-only matrix (DEVPROD-13331)

---

src/bsoncxx/test/catch.cpp
src/bsoncxx/test/catch.hh

Resolves CXX-1110. Verified by [this patch](https://spruce.mongodb.com/version/675877e0c945f10007c344e2/) (containing the proposed changes in https://github.com/mongodb/mongo-cxx-driver/pull/1298).
Precursor changes to faciliate the improvement and addition of tests for bsoncxx and mongocxx error codes and error categories as part of CXX-834 and CXX-2745.
The two new macros `(CHECK|REQUIRE)_THROWS_WITH_CODE` mirror the existing Catch2 exception assertion macros `(CHECK|REQUIRE)_THROWS_WITH`. It is expected to be used as follows:
```cpp
CHECK_THROWS_WITH_CODE(throwing-expr, error-code-enumerator);
CHECK_THROWS_WITH_CODE(throwing-expr, error-code);
CHECK_THROWS_WITH_CODE(throwing-expr, error-condition);
```
The exception type must be or derive from `std::system_error` which provides the …

CXX-1110 add CHECK_THROWS_WITH_CODE

---

etc/deploy-to-ghpages.pl

Companion PR to https://github.com/mongodb/mongo-cxx-driver/pull/1302 which adds the new `404.html` file to the list of rsync exclude filters so it is not deleted by the script during deployment.

CXX-3195 avoid deleting custom 404 page

---

404.html

Resolves CXX-3195. Precursor changes to CXX-2745 to gracefully handle API doc pages which are no longer present in the latest API documentation, such as in https://github.com/mongodb/mongo-cxx-driver/pull/1301.
Implemented according to [GitHub Pages Docs](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) using a Hugo-generated custom 404 homepage as a template which was stripped down to its current state with site-wide contents preserved (e.g. content security policy, stylesheets, site visit tracker, etc.).
404 and redirection behavior has not yet been tested with GitHub Pages deployment. Behavior will be tested and validated after deployment with followup PRs if necessary.
GitHub Pages supports using a custom 404 …

CXX-3195 add 404 page with automatic redirection

---

.evergreen/config_generator/components/abi_stability.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/abi-stability-setup.sh

EVG task failures due to a distro image misconfiguration revealed that Clang 18 is available on the newly-available rhel95 distro. Addresses task failures by migrating to the rhel95 distro with Clang 18 for improved C++23 compilation coverage.
Additionally added some missing early return handlers to correctly report failures during setup.

Migrate ABI stability tasks to rhel95 distro (Clang 18)

---

.evergreen/config_generator/components/packaging.py
.evergreen/config_generator/etc/utils.py
.evergreen/generated_configs/tasks.yml

Adds the `allowed_requesters` field to packaging tasks such that they are not scheduled by GitHub operations. The "trigger" and "ad_hoc" requesters are left in their default enabled state (despite AFAIK also being unused; they can also be disabled if preferable). This effectively limits the requesters which may schedule the packaging tasks to commit builds (EVG waterfall) and manually requested patch builds.
~~The proposed config does not apply to this PR's own patch build.~~ Disregard, it _does_ apply. 😄

Avoid running packaging tasks during GitHub operations

---

etc/clang-format-all.sh

Follow-up to https://github.com/mongodb/mongo-cxx-driver/pull/1299. Verified with this [patch build](https://spruce.mongodb.com/version/6772fc401713a80007c98ce4).
Use `grep` instead of `-regextype` to fix observed error running `etc/clang-format-all.sh` on macOS:
```
find: -regextype: unknown primary or operator
```
Also allow overriding the used `clang-format`. This is intended to ease my current set-up and can be reverted if desired. I installed LLVM 1.19 with `brew install llvm`, and it is not on a system path to avoid interfering with AppleClang.

CXX-3198 support `clang-format-all.sh` on macOS

---

.evergreen/scripts/compile.sh

Addresses recent Evergreen flaky test failures on MacOS distros due to unexpectedly compiling with a system-installed libmongoc (CMake reports version 1.29.1 despite `MONGOC_DOWNLOAD_VERSION` being 1.29.0). This leads to the libbson library having a `BSON_EXTRA_ALIGN` that is inconsistent with test expectations. Filed [DEVPROD-13793](https://jira.mongodb.org/browse/DEVPROD-13793).
This PR sets `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>=ON` when a preinstalled C Driver is not detected (the presence of the `bson-config.h` header, as used by the extra alignment consistency checks). This forces CMake to "fail" to find an existing C Driver, thus ensuring it fetch-and-builds the C Driver as expected by integration tests.

Do not compile with system libmongoc during integration tests

---

.evergreen/config_generator/components/atlas_search_indexes.py
.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/funcs/compile.py
.evergreen/config_generator/components/funcs/install_uv.py
.evergreen/config_generator/components/funcs/run_kms_servers.py
.evergreen/config_generator/components/integration.py
.evergreen/config_generator/components/lint.py
.evergreen/config_generator/components/macro_guards.py
.evergreen/config_generator/components/mongohouse.py
.evergreen/config_generator/components/sanitizers.py
.evergreen/config_generator/components/uninstall_check.py
.evergreen/config_generator/components/valgrind.py
.evergreen/config_generator/components/versioned_api.py
.evergreen/generated_configs/functions.yml
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/compile.sh
.evergreen/scripts/test.sh
.evergreen/scripts/uv-installer.sh

Motivated by an attempt to resolve ongoing task failures on the (deprecated) `windows-64-vs2015` distro due to the [absence of a compatible Python version](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_compile_only_matrix_compile_only_vs2015_x64_debug_shared_2f53a561afa7ff06c12b7c6ec7a7f3bd6a5e135b_25_01_06_16_30_46/0/task?bookmarks=0,87&shareLine=44) after https://github.com/mongodb-labs/drivers-evergreen-tools/pull/567 dropped support for Python 3.8 (EOL).
This PR does _not_ succeed in resolving the original vs2015 distro issue, as unfortunately uv appears to have an [unresolved regression since 0.5.9](/astral-sh/uv/issues/10231) that is [preventing its use](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_compile_only_matrix_compile_only_vs2015_x64_debug_shared_patch_2f53 …

Migrate most windows-64-vs2015 tasks to windows-vsCurrent distro

---

etc/releasing.md
pyproject.toml
uv.lock

Addresses [task failures](https://spruce.mongodb.com/version/mongo_cxx_driver_dcc49bb7953b9b6a0ce756ca84972d988277c107/tasks) on PowerPC and zSeries distros due to [failure](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_compile_only_matrix_compile_only_rhel83_zseries_release_shared_dcc49bb7953b9b6a0ce756ca84972d988277c107_25_01_07_16_26_39/0/task?bookmarks=0,107&shareLine=66) to build the `cryptography` package (43.0.3) despite no notable updates to Rust toolchain dependencies in uv release notes since 0.5.9. Attempts to limit or pin the cryptography package version failed. Therefore, this PR proposes using [dependency groups](https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups) to by-default exclude packages required by the `make_release.py` script which …

Exclude cryptography package by default for tasks on PowerPC/zSeries distros

---

.evergreen/config_generator/components/compile_only.py
.evergreen/generated_configs/tasks.yml
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/exception/authentication_exception.cpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1311 which overlooked use of the now-deprecated `authentication_exception` class in the [authentication_exception.cpp](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_compile_only_matrix_compile_only_rhel79_release_shared_impls_dcc49bb7953b9b6a0ce756ca84972d988277c107_25_01_07_16_26_39/0/task?bookmarks=0,842&selectedLineRange=L802) file leading to deprecation warnings that are caught by the RHEL 7.9 release build.
Additionally removes a now-obsolete workaround for RHEL 7.9 concerning Python binary version compatibility due to use of Astral uv instead to invoke `calc_release_version.py`.

Address deprecation warnings-as-errors on RHEL 7.9

---

etc/clang-format-all.sh

To fix instruction to run format script with `uv`:
```bash
% uv run --frozen etc/clang-format-all
error: Failed to spawn: `etc/clang-format-all`
Caused by: No such file or directory (os error 2)
% uv run --frozen etc/clang-format-all.sh
clang-format version 19.1.5
[...]
```

add trailing `.sh` to instruction

---

.evergreen/config_generator/components/compile_only.py
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/compile.sh

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1312.
Due to [DEVPROD-13875](https://jira.mongodb.org/browse/DEVPROD-13875), this PR proposes we resort to using a manual workaround for the C++ Driver instead until we drop VS 2015 coverage. The Python 3.8 binary which was being used prior to https://github.com/mongodb-labs/drivers-evergreen-tools/pull/567 is now manually invoked only on the `windows-64-vs2015` distro which requires it.

Manually invoke python3 on windows-64-vs2015

---

.git-blame-ignore-refs

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1299 and https://github.com/mongodb/mongo-cxx-driver/pull/1306 as requested.

Add git blame ignore refs for f1ad6b63 and 2f53a561

---

cmake/BsoncxxUtil.cmake
cmake/MongocxxUtil.cmake
src/bsoncxx/CMakeLists.txt
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp
src/mongocxx/CMakeLists.txt

An intermediate PR related to CXX-2745 following https://github.com/mongodb/mongo-cxx-driver/pull/1318.
Add advanced, for-development-only CMake options `BSONCXX_API_OVERRIDE_DEFAULT_ABI` and `MONGOCXX_API_OVERRIDE_DEFAULT_ABI` to permit toggling the ABI namespace that is used by root namespace redeclarations.
> [!IMPORTANT]
> These options are NOT intended for public use. This is strictly for development purposes. Enabling these options will emit CMake configuration warnings:
> ```
> CMake Warning at src/bsoncxx/CMakeLists.txt:29 (message):
>   BSONCXX_API_OVERRIDE_DEFAULT_ABI is an experimental feature
> CMake Warning at src/mongocxx/CMakeLists.txt:29 (message):
>   MONGOCXX_API_OVERRIDE_DEFAULT_ABI is an experimental feature
> ```
> The options are also marked as "advanced" so they do …

CXX-2745 Add advanced CMake options to toggle root namespace redeclarations

---

.evergreen/config_generator/components/compile_only.py
.evergreen/generated_configs/tasks.yml

https://github.com/mongodb/mongo-cxx-driver/pull/1313/ incorrectly reverted a patch-only workaround introduced in https://github.com/mongodb/mongo-cxx-driver/pull/1313, which unintentionally reintroduced `compile-only-rhel79-release-shared-impls` task failure in GitHub PR patch builds.

Re-exclude rhel79 from compile-only matrix in patch builds

---

examples/api/runner.cpp

Preemptive changes to improve task failure output observed during work on CXX-2665.
Adds try-catch blocks when build with MSVC to improve the uncaught exceptions experience on Windows: uncaught exceptions are printed to stderr rather than a popup dialog box (local execution) or completely-absent program termination message (in CI).
Additionally, the try-catch block used for live server detection may incorrectly catch mongocxx exceptions thrown by a live server component, which would misleadingly emit both the "failed: uncaught exception" message _and_ the "Skipping API examples that require a live server" message, subsequently failing to terminate with `EXIT_FAILURE` as it should.

Miscellaneous improvements to API examples runner

---

.evergreen/scripts/install-c-driver.sh
.evergreen/scripts/start-mongod.sh
examples/mongocxx/gridfs.cpp

Preemptive changes to address macos-14-arm64 task failures observed during work on CXX-2665.
- The curl command to obtain the tag name of the latest release seems to spuriously fail due to unknown reasons specifically when executed on MacOS distros. Following https://github.com/mongodb/mongo-c-driver/pull/1521, a `VERSION_CURRENT` file is guaranteed for latest releases, so that file is detected and used instead when available.
- The `start-mongod.sh` script occasionally fails on MacOS distros due to permission errors. A call to `chmod -x` is added to ensure binaries under `MONGODB_BINARIES` are actually executable as they should be. An obsolete workaround for rhel9 distros is removed in favor of a simple fallback routine for legacy mongo shell binaries.
- A `-Wsign-conversion` warning …

Attempt to address miscellaneous integration task errors on macos-14-arm64

---

.evergreen/scripts/compile-scan-build.sh
.evergreen/scripts/compile.sh
.evergreen/scripts/install-c-driver.sh
.evergreen/scripts/test.sh
etc/run-clang-tidy.sh
examples/projects/bsoncxx/cmake/shared/build.sh
examples/projects/bsoncxx/cmake/static/build.sh
examples/projects/bsoncxx/pkg-config/shared/build.sh
examples/projects/bsoncxx/pkg-config/static/build.sh
examples/projects/mongocxx/cmake/shared/build.sh
examples/projects/mongocxx/cmake/static/build.sh
examples/projects/mongocxx/pkg-config/shared/build.sh
examples/projects/mongocxx/pkg-config/static/build.sh

Followup to https://github.com/mongodb/mongo-c-driver/pull/1853 by applying similar improvements to the C++ Driver. Includes some minor drive-by improvements to the `build-example-projects` scripts to ensure they inherit and better (re)use existing environment variables.

ccache: expand usage and /Zi -> /Z7 for MSVC debug flags

---

src/mongocxx/lib/CMakeLists.txt
src/mongocxx/lib/mongocxx/private/ssl.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/client.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/tls.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
src/mongocxx/test/catch_helpers.hh
src/mongocxx/test/client.cpp
src/mongocxx/test/pool.cpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1323 to address `atlas-search-indexes-matrix` task failures due to incorrect SSL configuration detection based on `MONGOCXX_ENABLE_SSL` and `MONGOC_ENABLE_SSL` macros which (incorrectly) may not be defined due to missing include directives, leading to false-positive "SSL support not available" exceptions.

CXX-2745 fix missing include directives for SSL-related config macros

---

etc/augmented.sbom.json
etc/cyclonedx.sbom.json

Resolves CXX-3224 for the master branch. Similar changes to https://github.com/mongodb/libmongocrypt/pull/960, but applied to the C++ Driver.
The Augmented SBOM file for this PR (and related) were updated using Evergreen patch builds with pending updates to the EVG configuration to support SilkBomb 2.0. These changes will be proposed in a followup PR.

CXX-3224 Regenerate SBOM Lite for silkbomb:2.0 forward compatibility

---

etc/releasing.md

SilkBomb 2.0 has been updated to support a `--generate-new-serial-number` flag. This flag supports the (re)generation of the SBOM Lite with a new unique serial number together with the `--sbom-in`/`-i` flag. This removes the need to deal with manual UUID generation or restoration of copyright and licenses fields.

CXX-3228 update release instructions with --generate-new-serial-number

---

cmake/BsoncxxUtil.cmake
cmake/MongocxxUtil.cmake

Minor followup to https://github.com/mongodb/mongo-cxx-driver/pull/1318, which relocated all generated config headers out of `v_noabi`. Addresses the following compilation warnings with Clang 21 in a fresh binary directory:
```
warning: no such include directory: 'src/mongocxx/lib/mongocxx/v_noabi' [-Wmissing-include-dirs]
```
All generated headers under `v1` and `private` continue to use the existing root-level include path (i.e. `${PROJECT_BINARY_DIR}/lib`).

CXX-2745 remove obsolete include paths for generated config headers

---

Doxyfile
src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt

Workaround [doxgyen/doxygen#11495](/doxygen/doxygen/issues/11495) and [doxygen/doxygen#11496](/doxygen/doxygen/issues/11496) which are affecting CXX-2745 API documentation by tidying up the preprocessor-related Doxygen configuration options following https://github.com/mongodb/mongo-cxx-driver/pull/1301. Since all relevant macro definitions are now visible, they can be expanded as-is with `MACRO_EXPANSION = YES` without using `EXPAND_AS_DEFINED`.
`EXPAND_ONLY_PREDEF = YES` and `SKIP_FUNCTION_MACROS = YES` are no longer required to guard against the attempted expansion of complex macros, as all problematic expansions are already being guarded with `\cond DOXYGEN_DISABLE` (these options do not help us avoid these issues) and we do not parse non-header files (where most other macros, …

doxygen: fix and improve macro expansion configuration options

---

Doxyfile
src/bsoncxx/CMakeLists.txt
src/mongocxx/CMakeLists.txt

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1353. After further investigation, it seems preferable to [predefine the non-standard attribute syntax](/doxygen/doxygen/issues/11495#issuecomment-2730431058) as macros rather than predefining/redefining the library macros which they are used with. This avoids the need for Doxygen preprocessor handling in the export headers (reverted the changes in https://github.com/mongodb/mongo-cxx-driver/pull/1353), simplifies the list of predefined macros in the Doxygen configuration file, and extends Doxygen parser confusion mitigation to all non-standard syntax (declspec and pragmas).
This revealed some Doxygen preprocessor confusion concerning how v_noabi prelude headers transitively include v1 headers, such that macros in …

doxygen: predefine non-standard specifiers and fix include paths

---

.clang-format

To ensure all source files have an EOF newline.
No source file currently requires modifications (they already have an EOF newline).

ClangFormat: set InsertNewlineAtEOF to true

---

src/mongocxx/test/bulk_write.cpp

Observed during local testing:
```
failed: unexpected exception with message: 'E11000 duplicate key error collection: db.coll index: _id_ dup key: { _id: 1 }: generic server error'
```
The bulk_write tests do not ensure the `db.coll` collection is empty prior to inserting keys with `_id: 1`.
A more comprehensive strategy to ensure a fresh database or collection (i.e. as implemented for the [API examples runner](https://github.com/mongodb/mongo-cxx-driver/blob/22337913e5d9df873491e69612612dd7fda4f575/examples/api/db_lock.hh#L24)) is deferred for later.

Fix potential duplicate key errors in bulk_write tests

---

.evergreen/config_generator/components/abi_stability.py
.evergreen/config_generator/components/atlas_search_indexes.py
.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/integration.py
.evergreen/config_generator/components/macro_guards.py
.evergreen/config_generator/components/sanitizers.py
.evergreen/config_generator/components/scan_build.py
.evergreen/config_generator/components/uninstall_check.py
.evergreen/config_generator/components/valgrind.py
.evergreen/config_generator/components/versioned_api.py
.evergreen/generated_configs/variants.yml

Abandoning the initiative started by https://github.com/mongodb/mongo-cxx-driver/pull/1083 to use display tasks (aka "execution tasks") for structured task lists.
> The "display tasks" EVG feature is used to reduce verbosity of the EVG results page. This also allows for the uploaded files to be conveniently grouped by display task [...]
This is due to deprioritization of related feature requests and bug fixes ([DEVPROD-5091](https://jira.mongodb.org/browse/DEVPROD-5091), [DEVPROD-7440](https://jira.mongodb.org/browse/DEVPROD-7440), [DEVPROD-12402](https://jira.mongodb.org/browse/DEVPROD-12402), [DEVPROD-13331](https://jira.mongodb.org/browse/DEVPROD-13331) (https://github.com/mongodb/mongo-cxx-driver/pull/1298), [DEVPROD-14794](https://jira.mongodb.org/browse/DEVPROD-14794), …

Remove display tasks from EVG config

---

src/bsoncxx/test/catch.cpp

Addresses the following `stderr` output by the `test_bson` test binary on Windows:
```
unable to get hostname: 0
```
This message is emitted by a call to `gethostname` in [`_bson_context_get_hostname`](https://github.com/mongodb/mongo-c-driver/blob/7a05b03ac246cbbe317c5a304b02a7b00c5bd499/src/libbson/src/bson/bson-context.c#L88) by the following stack trace:
```
bsoncxx::v_noabi::oid::oid()
- bson_oid_init(bson_oid_t *oid, bson_context_t *context)
- bson_context_get_default()
- _bson_context_init_default()
- _bson_context_init(bson_context_t *context, bson_context_flags_t flags)
- _bson_context_init_random (bson_context_t *context, bool init_seq)
- _bson_context_get_hostname (char out[HOST_NAME_MAX])
- gethostname (char *name, int namelen)
```
Patching the mongoc library to print the …

Address gethostname failure due to missing WinSock initialization

---

data/change-streams/unified/change-streams-pre_and_post_images.json
data/change-streams/unified/change-streams.json

Preemptive changes to unblock failing tasks on Evergreen until a proper solution is implemented for [DRIVERS-3151](https://jira.mongodb.org/browse/DRIVERS-3151).

CXX-3261 temporarily restrict updateDescription tests to 8.1 or older

---

src/mongocxx/test/change_streams.cpp

Attempt to address [spurious EVG task failure](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_integration_matrix_linux_integration_ubuntu2004_arm64_debug_shared_cxx17_8.0_replica_cb7afd1b886b0e1be3c4dec8bbc075258b8c070c_25_04_02_14_32_38/0/task?bookmarks=0,1581&selectedLineRange=L1524) due to the following error:
```
failed: *cs.get_resume_token() == token3 for: { "_data" : "8267ED4C1E0000000E2B0429296E1404" }
==
{ "_data" : "8267ED4C1D000000082B042C0100296E5A100405365E4936E74ED08129D739E8BB4509463C6F7065726174696F6E54797065003C696E736572740046646F63756D656E744B65790046645F6964006467ED4C1D6AA5CE39D608020D000004" }
```
I suspect it may be due to the change stream being created from the client object which does not inherit "majority" read _or_ write concern despite the write …

Remove assertion of change streams end iterator document

---

.evergreen/config_generator/components/sbom.py
.evergreen/config_generator/components/valgrind.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml

Unblocks patch builds executing the sbom and valgrind tasks due to a regression in the system packages installed on the rhel80 distro (currently being investigated). The next highest-host-availabity compatible distro appears to be `rhel8.8`. The valgrind task names are manually left unchanged from `rhel80` to avoid breaking task history with this workaround.

Temporarily relocate sbom and valgrind from rhel80 to rhel8.8

---

src/mongocxx/lib/mongocxx/private/mongoc.hh

Followup to https://github.com/mongodb/mongo-c-driver/pull/1953. No further changes appear to be necessary.

CDRIVER-5942 remove mongoc_collection_count_with_opts

---

src/mongocxx/lib/mongocxx/private/mongoc.hh

Followup to https://github.com/mongodb/mongo-c-driver/pull/1963. No further changes appear to be necessary.

CDRIVER-5952 remove mongoc_uri_get_ssl

---

.evergreen/config_generator/components/sbom.py
.evergreen/config_generator/components/valgrind.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml

The issues motivating https://github.com/mongodb/mongo-cxx-driver/pull/1370 have been addressed by [DEVPROD-16404](https://jira.mongodb.org/browse/DEVPROD-16404). Verified by [this patch](https://spruce.mongodb.com/version/67eec32e7df94c0007adc3de/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

Revert "Temporarily relocate sbom and valgrind tasks from rhel80 to rhel8.8 (#1370)"

---

src/mongocxx/test/change_streams.cpp
src/mongocxx/test/client.cpp
src/mongocxx/test/client_helpers.cpp
src/mongocxx/test/client_helpers.hh
src/mongocxx/test/client_session.cpp
src/mongocxx/test/client_side_encryption.cpp
src/mongocxx/test/collection.cpp
src/mongocxx/test/database.cpp
src/mongocxx/test/index_view.cpp
src/mongocxx/test/sdam-monitoring.cpp
src/mongocxx/test/spec/client_side_encryption.cpp
src/mongocxx/test/spec/command_monitoring.cpp
src/mongocxx/test/spec/gridfs.cpp
src/mongocxx/test/spec/retryable-reads.cpp
src/mongocxx/test/spec/unified_tests/runner.cpp
src/mongocxx/test/spec/util.cpp
src/mongocxx/test/spec/util.hh
src/mongocxx/test/transactions.cpp
src/mongocxx/test/versioned_api.cpp

Remove `client` arg from test helpers that cache results.
Verified with this patch build: https://spruce.mongodb.com/version/67ee96310b754c000700e66c
When working on CXX-3209 I was surprised to discover calling `test_util::get_max_wire_version` on a differently versioned `mongocryptd` returned the same value as the running `mongod`:
```c++
// Check maxWireVersion of mongocryptd:
mongocxx::client mongocryptd_client(uri("mongodb://localhost:27020"));
auto mwv = test_util::get_max_wire_version(mongocryptd_client); // same as the running mongod?!
```
The cause appeared to be due to cached results in test helpers:
```c++
// These frequently used network calls are cached to avoid bottlenecks during tests.
document::value get_is_master(client const& client) {
static auto reply = …
```

Remove client arg from test helpers

---

CHANGELOG.md
cmake/FetchMongoC.cmake

Resolves CXX-3266.
> [!IMPORTANT]
> This PR is only concerned with a C Driver project whose CMake targets are imported via `add_subdirectory()` instead of `find_package()`. This may either be an auto-downloaded C Driver (via `FetchMongoC.cmake`) or a manual call to `add_subdirectory()` by a higher-level CMake project.
The API version numbers embedded in the C Driver v2 install paths revealed suspicious behavior during local development and testing for CXX-3101. Given `LIBMONGOC_DOWNLOAD_VERSION` (+ related variables) set to `2.0.0` and using the [latest commit](fe7bfd3599c0dd7e1f6b9aacbef362c193f36c37) (targeting a 4.1.0 release), the following install directory structure was observed (the API version for C Driver libraries is `0.0.0`?!):
```
<prefix>
├── include
│   ├── bson-0.0.0
│ …
```

CXX-3266 avoid inheriting BUILD_VERSION by auto-downloaded C Driver

---

src/mongocxx/include/mongocxx/v_noabi/mongocxx/uri.hpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/uri.cpp
src/mongocxx/test/uri.cpp

- Add method to `mongocxx::uri` to set `serverSelectionTryOnce` URI option.
Intended to help simplify a a [workaround](https://github.com/10gen/mongo/blob/e758d87c23d7ffc70bb767e618692063dccaa826/src/mongo/db/modules/enterprise/src/streams/exec/mongocxx_utils.cpp#L72-L110) in Atlas Stream Processing. The workaround applies `serverSelectionTryOnce=false` to a URI if the option is not already specified. I expect this new setter can be used in [streams after constructing the mongocxx::uri](https://github.com/10gen/mongo/blob/e758d87c23d7ffc70bb767e618692063dccaa826/src/mongo/db/modules/enterprise/src/streams/exec/mongocxx_utils.cpp#L332) like:
```c++
auto uri = std::make_unique<mongocxx::uri>(uri);
// Set default "serverSelectionTryOnce=false" if not included in URI:
if …
```

CXX-3204 add URI setter for `server_selection_try_once`

---

.mci.yml

Address task failures on the [releases/v3.11](https://spruce.mongodb.com/version/mongo_cxx_driver_v3_c0f72cd90229479a05e8c84c92b8ecb84109ae50/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) branch due to incorrectly cloning the latest version of the mongo-c-driver repository without pinning to a compatible release version, e.g.:
```
error: 'bson_as_json' was not declared in this scope
```

Restrict cloned mongo-c-driver to mongoc_version_minimum

---

.evergreen/test.sh
.mci.yml

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1354. Disables VS 2015 tasks until [DEVPROD-16074](https://jira.mongodb.org/browse/DEVPROD-16074) (required by CXX-3253) is resolved.

Temporarily disable VS 2015 tasks for releases/v3.11

---

src/mongocxx/test/change_streams.cpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1367.
Attempt to resolve [more flaky task failures](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_integration_matrix_macos_integration_macos_14_debug_shared_cxx11_4.2_replica_fe7bfd3599c0dd7e1f6b9aacbef362c193f36c37_25_04_03_17_34_55/0/task?bookmarks=0,1662&selectedLineRange=L1613):
```
change_streams.cpp:388: FAILED: std::distance(stream.begin(), stream.end()) == 1 for: 0 == 1
```
```
change_streams.cpp:594: FAILED: one != x.end() for: {?} != {?}
```
Assuming these are due to the tests not consistently using majority write concern for their operations, as is the case for the prose test that was the focus of the previous PR:
> Change streams only notify on data changes that have persisted to a majority of data-bearing …

Use majority concern for all change stream test collections

---

src/mongocxx/test/collection.cpp

Attempt to address the following [flaky test failure](https://spruce.mongodb.com/task/mongo_cxx_driver_integration_matrix_macos_integration_macos_14_arm64_debug_shared_cxx17_csfle_8.0_sharded_patch_a50c2f6018a804e11c03e8aafb2439c0e7122637_67f6cd788236020007393486_25_04_09_19_41_47/logs?execution=0):
```
collection.cpp:2413: FAILED: iter != cursor.end() for: {?} != {?} with 1 message: 'k_tailable_await'
```
Applies majority concern in a manner similar to https://github.com/mongodb/mongo-cxx-driver/pull/1375.

Use majority concern for tailable cursor tests

---

.github/CODEOWNERS

To meet requirement of DRIVERS-3098. Follows pattern from other drivers: [PHP](https://github.com/mongodb/mongo-php-library/blob/a4ccccd9011bad978e6f0d52efd1a512ef64d35a/.github/CODEOWNERS), [C#](https://github.com/mongodb/mongo-csharp-driver/blob/main/CODEOWNERS).

CXX-3268 add CODEOWNERS

---

.evergreen/config_generator/components/funcs/install_valgrind.py
.evergreen/config_generator/components/funcs/test.py
.evergreen/config_generator/components/valgrind.py
.evergreen/generated_configs/functions.yml
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/test.sh
.evergreen/scripts/valgrind-installer.sh

Unblock ongoing Valgrind task failures while [DEVPROD-16589](https://jira.mongodb.org/browse/DEVPROD-16589) continues to be investigated. Proposes using a pattern similar to [install_uv.py](https://github.com/mongodb/mongo-cxx-driver/blob/88cad643775be0bc2dd53a96cc2fc565ef6441c6/.evergreen/config_generator/components/funcs/install_uv.py#L9), where a recent version of Valgrind is downloaded (verified by SHA1 checksum) and built-from-source. This is meant to be a temporary solution until [DEVPROD-16589](https://jira.mongodb.org/browse/DEVPROD-16589) is resolved (temporary to minimize our use of `curl` commands in CI scripts). Use of a 60 second timeout for curl (`-m 60`) is arbitrary and may be extended if it is observed to be too short (the total download+build+install time is currently …

Download and build-from-source valgrind 3.24.0 when not present

---

etc/calc_release_version.py
etc/calc_release_version_selftest.sh

Addresses rhel76 task failure in proposed changes to https://github.com/mongodb/mongo-cxx-driver/pull/1381 due to the available git version (2.43.6) not supporting the `--format` flag used by `calc_release_version.py`.
This PR proposes changing the git command from `git tag --list` to `git for-each-ref "refs/tags/*"`, as `for-each-ref` [is supported](https://git-scm.com/docs/git-for-each-ref/2.43.0) by 2.43 and also supports the required `--format` flag.
> [!NOTE]
> This PR also includes the same [update](https://github.com/mongodb/mongo-cxx-driver/pull/1379/commits/46f020b81e3dd7d3d0152c0836ca5105c1714b6a) to self-test scripts in https://github.com/mongodb/mongo-cxx-driver/pull/1379. Either PR may be merged first.

CXX-3099 use for-each-ref for Git 2.43 compatibility

---

data/change-streams/unified/change-streams-clusterTime.json
data/change-streams/unified/change-streams-disambiguatedPaths.json
data/change-streams/unified/change-streams-nsType.json
data/change-streams/unified/change-streams-showExpandedEvents.json
data/change-streams/unified/change-streams.json
data/change-streams/unified/test_files.txt
src/mongocxx/test/spec/unified_tests/runner.cpp

Cherry-picks https://github.com/mongodb/mongo-cxx-driver/commit/cb7afd1b886b0e1be3c4dec8bbc075258b8c070c (https://github.com/mongodb/mongo-cxx-driver/pull/1366) onto the v3.11 release branch to address task failures against latest MongoDB servers.

CXX-3261 sync change streams unified spec tests with 0aee4aad (#1366)

---

.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/funcs/install_c_driver.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/functions.yml
.evergreen/generated_configs/tasks.yml
.evergreen/scripts/compile.sh
etc/run-clang-tidy.sh
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/validate.cpp
src/mongocxx/lib/mongocxx/private/change_stream.hh
src/mongocxx/lib/mongocxx/private/client_session.hh
src/mongocxx/lib/mongocxx/private/index_view.hh
src/mongocxx/lib/mongocxx/private/mock.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/command_failed_event.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/command_started_event.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/events/server_description.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/options/transaction.hh
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/read_preference.cpp
src/mongocxx/lib/mongocxx/v_noabi/mongocxx/uri.cpp
src/mongocxx/test/client_helpers.cpp
src/mongocxx/test/spec/operation.cpp
src/mongocxx/test/spec/unified_tests/operations.cpp

Resolves CXX-3253. Followup to https://github.com/mongodb/mongo-c-driver/pull/1991.

CXX-3253 reintroduce VS 2015 task coverage

---

etc/garasign_dist_file.sh
etc/garasign_release_tag.sh
etc/make_release.py
etc/releasing.md

This PR attempts to implement the "signed release tag" requirement of the new Repository and Commit Security policy. This is primarily accomplished by the new `garasign_release_tag.sh` script, which mirrors the existing `garasign_dist_file.sh` script.
The `garasign-git` Artifactory image provides an environment where `git` commands may be executed using the same Release Signing Key provided by `garasign-gpg`, which is currently used by `garasign_dist_file.sh` to sign the release tarball. This allows us to create a GPG-signed release tag using `git tag --sign` in a manner which satisfies the policy requirements while (hopefully) minimizing disruption to the release process or regular development. (We do not want to impose any GPG key management overhead if possible.)
> [!NOTE]
> …

CXX-3002 update release instructions to support signed release tags

---

CHANGELOG.md
src/mongocxx/include/mongocxx/v_noabi/mongocxx/read_preference.hpp
src/mongocxx/test/read_preference.cpp

Deprecates `mongocxx::v_noabi::read_preference::hedge()`.

CXX-3241 deprecated hedged reads

---

etc/garasign_dist_file.sh
etc/garasign_release_tag.sh

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1388 which fixes/improves two observed issues.
---
The `gpgv` command for verifying the dist tarball signature was failing due to the following error(s):
```
gpgv: unknown type of key resource 'trustedkeys.kbx'
gpgv: keyblock resource '/tmp/tmp.qioUjF6CI1/trustedkeys.kbx': General error
gpgv: Signature made Tue Apr 22 09:32:28 2025 CDT
gpgv:                using RSA key DC7F679B8A34DD606C1E54CAC4FC994D21532195
gpgv: Can't check signature: No public key
```
This is apparently due to `gpgv` expecting a keyring named `trustedkeys.kbx`, whereas `gpg` uses `pubring.kbx` by default. (Note: this was not an issue prior to https://github.com/mongodb/mongo-cxx-driver/pull/1388 due to using a temporary file as the keyring rather than a …

CXX-3002 fix keyring and trust for verifying GPG signatures

---

etc/calc_release_version.py

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1384.
> due to the available git version (2.43.6)
This was incorrect: RHEL 7.6 distros apparently may contain Git versions as old as 1.8.3 (?!), not just 2.43.6. Although `for-each-ref`, `--format`, and `%(refname)` are supported, `:strip=2` is not (requires [Git 2.7+](https://git-scm.com/docs/git-for-each-ref/2.7.6)):
```
fatal: unknown refname: format strip=2
Traceback (most recent call last):
File "etc/calc_release_version.py", line 372, in <module>
RELEASE_VER = main()
^^^^^^
File "etc/calc_release_version.py", line 346, in main
branch_tags = get_branch_tags(active_branch_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "etc/calc_release_version.py", line 236, in get_branch_tags
tags_by_obj = get_object_tags() …
```

CXX-3099 perform refname:split=2 within Python

---

etc/make_release.py
etc/releasing.md

Update release scripts and instructions to use a Jira Personal Access Token.
The access token for the Jira service account used in `make_release.py` expired:
```
$ python ./etc/make_release.py --dry-run r4.1.0
[...]
response text = oauth_problem=token_expired
```
This token was for the service account created in [OFFICEIT-32460](https://jira.mongodb.org/browse/OFFICEIT-32460). Rather than requesting a new token, this PR proposes switching to use a Jira Personal Access Token (PAT). Using a PAT was recommended [in slack](https://mongodb.slack.com/archives/C0UK2L7RC/p1745325102967929?thread_ts=1745259700.741349&cid=C0UK2L7RC) and appears to have several advantages: the releasing developer can create the PAT, set automatic expiration, and revoke. The PAT is created with the same permissions …

Use Jira Personal Access Token (PAT)

---

.evergreen/scripts/valgrind-installer.sh

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1383 to address spurious task failure due to the [following error](https://parsley.mongodb.com/evergreen/mongo_cxx_driver_valgrind_matrix_valgrind_rhel80_shared_8.0_replica_eec6bd435ea06e0e87243b900f03af9b5e873f9f_25_04_22_20_21_01/0/task?bookmarks=0,73&shareLine=51):
```
curl: (16) Error in the HTTP2 framing layer
```
`curl` does not appear to `--retry` for this error code. Considered using `--retry-all-errors`, but docs state:
> This option is the "sledgehammer" of retrying. Do not use this option by default (for example in your curlrc), there may be unintended consequences such as sending or receiving duplicate data. Do not use with redirected input or output. You'd be much better off handling your unique problems in shell …

Retry valgrind curl command via script instead of --retry

---

CHANGELOG.md
Doxyfile
README.md
etc/apidocmenu.md
etc/augmented.sbom.json
etc/cyclonedx.sbom.json
etc/generate-latest-apidocs.sh
etc/releasing.md

Apply changes associated with the 4.1.0 release and some release step tweaks.
Steps to update the `etc/apidocmenu.md` file are moved before creating the tag. This is intended to include the change in the published docs. The `doxygen-latest` target (used by `doxygen-deploy`) builds from the latest tag.
Outside of this PR, the `dbx-c-cxx-releases` team was added to the bypass list for [Restrict Updates (Branches)](https://github.com/mongodb/mongo-cxx-driver/settings/rules/4939020) to permit the force push of the `releases/stable` branch.

Apply changes after 4.1.0 release

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/vector/iterators.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1356, where a `-Wsign-conversion` Clang warning due to the following expression was overlooked:
```cpp
0xFFu << (-element_end.bit & 7u)
```
`element_end.bit` is a `std::uint8_t`. The unary negation operator implicitly promotes the result to an `int`, whose signedness is inconsistent with `7u` (warning: `signed & unsigned`). The literal is made a signed `int` for consistency. This should not impact the behavior of the overall expression ([tested exhaustively](https://godbolt.org/z/M3Tvfe68h)). (Updated link: static assert `unsigned << signed -> unsigned` (after promotion) + test `UINT8_MAX` as well.)

Address -Wsign-conversion warnings with Clang

---

.evergreen/config_generator/components/benchmarks.py
.evergreen/generated_configs/functions.yml
.evergreen/scripts/send-perf-data.sh

The perf.send command is no longer being maintained and is in a maintenance state and will be decommissioned eventually. It has been replaced instead by a new end point that users are able to call from their evergreen files; [this doc](https://github.com/10gen/performance-tooling-docs/blob/main/getting_started/migrating_from_perfSend_to_sps.md) outlines a drop in solution that we apply to the existing evergreen config file in this PR.
This PR updates the Mongo-cxx-driver project to send performance data downstream using the newest supported method. I added a new send-perf-data.sh script that is called within the `benchmarks-run` function. I also added this to the config generator and recreated the functions.yml file using the generator.
Successful patch: …

DEVPROD-17369 - Update generated config to use new data send script to replace perf.send

---

src/mongocxx/test/client_side_encryption.cpp

CXX-3278 update invalid URIs in CSE endpoint tests

---

.evergreen/config_generator/components/macro_guards.py
.evergreen/generated_configs/tasks.yml
CHANGELOG.md
CMakeLists.txt

Resolves CXX-3288. Split from https://github.com/mongodb/mongo-cxx-driver/pull/1403.
This PR delays the call to `include(FetchMongoC)` until _after_ all top-level cache variables have been initialized (notably, including the `ENABLE_TESTS` option) to avoid the C Driver's own cache variable initialization taking priority over the C++ Driver when conditionally importing the auto-downloaded C Driver via `add_subdirectory()`.
---
The auto-downloaded C Driver is observed to overwrite the default value (OFF) of the C++ Driver's `ENABLE_TESTS` cache variable with its own default (ON):
```
$ cmake -B local-build -LA
...
-- Required MongoDB C Driver libraries not found via find_package()
-- MongoDB C Driver library sources will be downloaded from GitHub
-- Downloading and configuring MongoDB C …
```

CXX-3288 do not initialize ENABLE_TESTS with the auto-downloaded C Driver

---

src/bsoncxx/lib/CMakeLists.txt
src/bsoncxx/lib/bsoncxx/private/immortal.hh
src/bsoncxx/lib/bsoncxx/private/type_traits.hh

Related to CXX-2745. Precursor changes to CXX-3232.
Adds two new internal bsoncxx components which are used by upcoming v1 interfaces.
---
The `bsoncxx::immortal<T>` class is used to define error category objects in a manner that avoids generating exit-time destructors (hence, "immortal") as can be diagnosed by the `-Wexit-time-destructors` Clang warning.
The pattern will look as follows:
```cpp
std::error_category const& example() {
class type final : public std::error_category { ... };
// The error category object instance. This is never destroyed!
static bsoncxx::immortal<type> const instance;
return instance.value();
}
```
---
Several new type traits are introduce to ensure consistency and correctness of v1 interfaces via static assertions. These type traits are derived from patterns …

CXX-2745 add immortal.hh and type_traits.hh

---

.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml

Per DevProd guidance. RHEL 7.9 is the latest RHEL 7 minor release and the one which is currently recommended for use by DevProd. This distro does not significantly change the available toolchain used for compilation test coverage (still GCC 4.8.5).

Migrate EVG tasks from RHEL 7.6 to RHEL 7.9

---

CHANGELOG.md
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/index.hpp

Fixes a bug introduced by https://github.com/mongodb/mongo-cxx-driver/pull/1360 as followup to CDRIVER-5946 where `BSONCXX_ABI_EXPORT_CDECL` is incorrectly used to export `mongocxx::v_noabi::options::index::storage_engine` instead of `MONGOCXX_ABI_EXPORT_CDECL`, as detected by this MSVC warning:
```
src\mongocxx\lib\mongocxx\v_noabi\mongocxx\options\index.cpp(163): warning C4273: 'mongocxx::v_noabi::options::index::storage_engine': inconsistent dll linkage [build\src\mongocxx\mongocxx_shared.vcxproj]
src\mongocxx\include\mongocxx\v_noabi\mongocxx/options/index.hpp(307): note: see previous definition of 'storage_engine'
```

CXX-3312 Fix export of mongocxx::v_noabi::options::index::storage_engine

---

CHANGELOG.md
src/mongocxx/include/mongocxx/v_noabi/mongocxx/options/index.hpp

Cherry-picks https://github.com/mongodb/mongo-cxx-driver/pull/1426 onto `releases/v4.1` to target a 4.1.2 patch release.

CXX-3312 Fix export macro for mongocxx::v_noabi::options::index::storage_engine (#1426)

---

src/mongocxx/test/v_noabi/uri.cpp

Followup to https://github.com/mongodb/mongo-c-driver/pull/2047 which modified the error message for an invalid URI connection scheme.

Update Invalid URI test for CDRIVER-5983

---

.evergreen/config_generator/components/abi_stability.py
.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/components/mongohouse.py
.evergreen/generated_configs/functions.yml
.evergreen/scripts/abi-stability-setup.sh

Cherry-picks https://github.com/mongodb/mongo-cxx-driver/pull/1421 to address ongoing ABI Stability Check task failures on the releases/v4.1 branch.

Fix and update EVG configuration for releases/v4.1

---

CHANGELOG.md

Resolves CXX-3193. Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1293 and https://github.com/mongodb/mongo-cxx-driver/pull/1328. Support for macOS 11 and macOS 12 were deprecated in the 4.1.0 release; this PR officially declares support is removed in the upcoming 4.2.0 release. The prior PRs already updated the EVG configuration accordingly. (Oddly, we seem to have completely skipped macOS 13 task coverage...? Which is probably okay, given limited macOS host availability.)

CXX-3193 add changelog entry dropping macOS 11 and macOS 12

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/json.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/json.cpp

Resolves CXX-3325.
The `""_bson` user-defined literal (UDL) was introduced in https://github.com/mongodb/mongo-cxx-driver/pull/724. At the time, it was declared as (ignoring export macros):
```cpp
document::value operator"" _bson(const char* str, size_t len);
```
https://github.com/mongodb/mongo-cxx-driver/pull/1066 attempted to reformat this declaration to address the `-Wdeprecated-literal-operator` warning observed with newer Clang compilers (per [Compiler Explorer](https://godbolt.org/z/dsrbhj57a), supported since Clang 17 and enabled by default since Clang 20):
```
error: identifier '_bson' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
```
```cpp
document::value operator""_bson(const char* json, size_t len);
```
but this …

CXX-3325 address -Wdeprecated-literal-operator warnings

---

src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/json.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/json.cpp

Cherry-picks https://github.com/mongodb/mongo-cxx-driver/pull/1441 onto the `releases/v4.1` branch to target the upcoming 4.1.2 patch release for Clang 20+ forward compatibility.

CXX-3325 address -Wdeprecated-literal-operator warnings (#1441)

---

examples/bsoncxx/view_and_value.cpp
src/mongocxx/test/spec/mongohouse.cpp

Minor PR addressing some stray unused variable warnings with Clang.

Fix -Wunused-variable Clang warnings

---

src/bsoncxx/include/bsoncxx/v1/detail/bit.hpp

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1412.
Addresses the following annoyingly-aggressive warning emitted by STL `<bit>` pre-C++20 despite using the `__cpp_lib_endian` feature test macro correctly ([CE](https://godbolt.org/z/GPc4n11TP)):
```
The contents of <bit> are available only with C++20 or later.
```
Conditioning on `__cplusplus >= 202002L` (C++20) is not enough due to [`/Zc:__cplusplus`](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) issues somehow resulting in an even worse outcome ([CE](https://godbolt.org/z/dG3jGrTW9)):
```
error C3083: 'endian': the symbol to the left of a '::' must be a type
error C2039: 'native': is not a member of 'std'
```
Therefore, `_MSVC_LANG >= 202002L` is used instead, but only when …

Silence MSVC warnings when including <bit> pre-C++20

---

CHANGELOG.md
src/bsoncxx/include/bsoncxx/v_noabi/bsoncxx/json.hpp
src/bsoncxx/lib/bsoncxx/v_noabi/bsoncxx/json.cpp

Follow-up to https://github.com/mongodb/mongo-cxx-driver/pull/1441. Quoting the PR description:
> following #1415, GCC 4.8 is no longer within our range of supported (minimum required) compilers.
However, GCC 4.8 is still supported on the v4.1 release branch. Therefore, the fix is conditioned on GCC 4.8. This is needed for the 4.1.2 release.
Fixes failing RHEL 7.6 tasks: https://spruce.mongodb.com/version/68b7661dc208c10007ea47f3

CXX-3325 condition fix on GCC version

---

.evergreen/config_generator/components/compile_only.py
.evergreen/config_generator/etc/distros.py
.evergreen/generated_configs/tasks.yml

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1464. Following the resolution of [DEVPROD-22169](https://jira.mongodb.org/browse/DEVPROD-22169), distros previously skipped due to absence of a system `uv` binary can now be enabled, with the caveat that the `debian11` distro is [no longer being built by DevProd](https://jira.mongodb.org/browse/DEVPROD-22169?focusedCommentId=7744278&focusedId=7744278&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7744278), so the task has been moved to `debian11-latest` as suggested by DevProd. For consistenc, `debian12` tasks have also been migrated to `debian12-latest`.

Re-enable distros previously missing system uv binaries

---

.evergreen/scripts/cmake-compat.sh
CHANGELOG.md
CMakeLists.txt
etc/augmented.sbom.json
etc/cyclonedx.sbom.json
etc/purls.txt

Only backports a bump to the auto-downloaded version (`MONGOC_DOWNLOAD_VERSION`) not the required version (`MONGOC_REQUIRED_VERSION`) to avoid a minor version dependency bump in a patch release.
Fixes referenced tag for C driver from `vA.B.C` to `A.B.C` (related to CXX-3364).
Some test scripts detect of a C driver install. These were updated from checking `bson-config.h` to `bson.h` to account for header renames made in CDRIVER-4153.
Tested with this patch build: https://spruce.mongodb.com/version/68e532fd024a630007afc38c

[v4.1] CXX-3663 bump downloaded C driver to 2.1.2
